/**
 * @file Defines the Mongoose schemas and model for tracking browser automation sessions and their steps.
 * @module app/modules/browserUse/browserUse.model
 * @author Your Name/Organization
 */

import mongoose from 'mongoose';

/**
 * @typedef {object} Step
 * @property {string} id - A unique identifier for the step.
 * @property {number} step - The sequential number of the step within a task.
 * @property {string} [evaluation_previous_goal] - The evaluation of the previous goal before this step.
 * @property {string} [next_goal] - The goal to achieve in this step.
 * @property {string} [url] - The URL at which this step was performed.
 */
/**
 * Mongoose schema for a single step within a browser automation task.
 * This schema is embedded within the `responseSchema`.
 * @type {mongoose.Schema<Step>}
 */
const stepSchema = new mongoose.Schema(
  {
    /**
     * A unique identifier for the step.
     * @type {string}
     * @required
     */
    id: { type: String, required: true },
    /**
     * The sequential number of the step within a task.
     * @type {number}
     */
    step: { type: Number },
    /**
     * The evaluation of the previous goal before this step.
     * @type {string}
     */
    evaluation_previous_goal: { type: String },
    /**
     * The goal to achieve in this step.
     * @type {string}
     */
    next_goal: { type: String },
    /**
     * The URL at which this step was performed.
     * @type {string}
     */
    url: { type: String },
  },
  { _id: false } // Do not create an _id for subdocuments
);

/**
 * @typedef {object} Response
 * @property {string} taskId - A unique identifier for the browser automation task.
 * @property {'created'|'running'|'finished'|'stopped'|'paused'|'failed'} status - The current status of the task.
 * @property {string} prompt - The initial prompt or instruction given for the task.
 * @property {string|null} [output=null] - The final textual output generated by the task.
 * @property {mongoose.Schema.Types.Mixed} [structured_output] - Any structured output generated by the task.
 * @property {string|null} [live_url=null] - A URL to view the live progress or result of the task.
 * @property {string} [error_message] - An error message if the task failed.
 * @property {Date|null} [finished_at=null] - The timestamp when the task was finished.
 * @property {Step[]} [steps=[]] - An array of individual steps performed during the task.
 */
/**
 * Mongoose schema for a single response or task execution within a browser session.
 * This schema is embedded within the `browserSessionSchema`.
 * @type {mongoose.Schema<Response>}
 */
const responseSchema = new mongoose.Schema(
  {
    /**
     * A unique identifier for the browser automation task.
     * @type {string}
     * @required
     * @unique
     */
    taskId: { type: String, required: true, unique: true },
    /**
     * The current status of the task.
     * @type {'created'|'running'|'finished'|'stopped'|'paused'|'failed'}
     * @enum {string}
     * @default 'created'
     */
    status: {
      type: String,
      enum: ['created', 'running', 'finished', 'stopped', 'paused', 'failed'],
      default: 'created',
    },
    /**
     * The initial prompt or instruction given for the task.
     * @type {string}
     * @required
     */
    prompt: { type: String, required: true },
    /**
     * The final textual output generated by the task.
     * @type {string|null}
     * @default null
     */
    output: { type: String, default: null },
    /**
     * Any structured output generated by the task. Can be any mixed type.
     * @type {mongoose.Schema.Types.Mixed}
     */
    structured_output: { type: mongoose.Schema.Types.Mixed },
    /**
     * A URL to view the live progress or result of the task.
     * @type {string|null}
     * @default null
     */
    live_url: { type: String, default: null },
    /**
     * An error message if the task failed.
     * @type {string}
     */
    error_message: { type: String },
    /**
     * The timestamp when the task was finished.
     * @type {Date|null}
     * @default null
     */
    finished_at: { type: Date, default: null },
    /**
     * An array of individual steps performed during the task.
     * @type {mongoose.Types.DocumentArray<Step>}
     * @default []
     */
    steps: {
      type: [stepSchema],
      default: [],
    },
  },
  { timestamps: true } // Adds createdAt and updatedAt timestamps
);

/**
 * @typedef {object} BrowserSession
 * @property {mongoose.Types.ObjectId} user - The ID of the user who initiated the browser session.
 * @property {mongoose.Types.ObjectId|null} [tenantId=null] - The ID of the tenant associated with this session.
 * @property {mongoose.Schema.Types.Mixed} [metadata={}] - Flexible key-value store for platform-level data, like admin overrides or special configurations.
 * @property {mongoose.Types.DocumentArray<Response>} responses - An array of responses/tasks performed within this session.
 * @property {Date} createdAt - The timestamp when the session was created.
 * @property {Date} updatedAt - The timestamp when the session was last updated.
 */
/**
 * Mongoose schema for a complete browser automation session initiated by a user.
 * It aggregates multiple responses/tasks performed within that session.
 * @type {mongoose.Schema<BrowserSession>}
 */
const browserSessionSchema = new mongoose.Schema(
  {
    /**
     * The ID of the user who initiated the browser session.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref 'User'
     * @required
     */
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    /**
     * The ID of the tenant associated with this session. Null for platform-level operations.
     * @type {mongoose.Schema.Types.ObjectId|null}
     * @ref 'Tenant'
     * @default null
     */
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tenant',
      default: null,
      // A single-field index on tenantId is not needed as it is the prefix of two other compound indexes.
      // Removing it reduces write overhead and index storage space.
    },
    /**
     * Flexible key-value store for platform-level data.
     * Useful for Platform Owners to track admin overrides, applied configurations, or other audit metadata.
     * @type {mongoose.Schema.Types.Mixed}
     * @default {}
     */
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    /**
     * An array of responses/tasks performed within this session.
     * @type {mongoose.Types.DocumentArray<Response>}
     */
    responses: [responseSchema],
  },
  { timestamps: true } // Adds createdAt and updatedAt timestamps
);

// === INDEXES ===
// Indexes are critical for performance, especially for Platform Owner oversight and global logging.

/**
 * Platform Owner Global Log Index: Enables efficient querying for the most recent sessions across ALL tenants.
 * Crucial for a global activity feed or system-wide monitoring.
 * @memberof BrowserSession
 * @index
 * @property {-1} createdAt - Descending order for creation date.
 */
browserSessionSchema.index({ createdAt: -1 });

/**
 * Primary Tenant-User Index: For efficient querying by tenant, user, and creation date.
 * This is the main index for drilling down into specific tenant and user activity.
 * This index also covers queries for `tenantId` alone and `{ tenantId, user }`.
 * @memberof BrowserSession
 * @index
 * @property {1} tenantId - Ascending order for tenant ID.
 * @property {1} user - Ascending order for user ID.
 * @property {-1} createdAt - Descending order for creation date.
 */
browserSessionSchema.index({ tenantId: 1, user: 1, createdAt: -1 });

/**
 * Tenant-wide Log Index: For efficient querying of a specific tenant's recent activity.
 * This is necessary for queries that filter by tenant and sort by date without specifying a user.
 * @memberof BrowserSession
 * @index
 * @property {1} tenantId - Ascending order for tenant ID.
 * @property {-1} createdAt - Descending order for creation date.
 */
browserSessionSchema.index({ tenantId: 1, createdAt: -1 });

/**
 * Legacy/User-centric Index: Fallback for efficient querying by user and creation date,
 * especially in non-tenant or user-centric views.
 * @memberof BrowserSession
 * @index
 * @property {1} user - Ascending order for user ID.
 * @property {-1} createdAt - Descending order for creation date.
 */
browserSessionSchema.index({ user: 1, createdAt: -1 });

/**
 * Mongoose model for a BrowserSession.
 * Represents a collection of browser automation tasks performed by a user, potentially within a tenant.
 * The collection name in the database will be 'browser-use'.
 * @type {mongoose.Model<BrowserSession>}
 */
const BrowserSession = mongoose.model(
  'BrowserSession',
  browserSessionSchema,
  'browser-use'
);

export default BrowserSession;