import { Storage } from '@google-cloud/storage';
import axios from 'axios';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import config from '../../../../../config/index.js';

/**
 * @file This service handles uploading and deleting presentation files to/from Google Cloud Storage (GCS).
 * It supports uploading files from both remote URLs and local file paths, including specific handling
 * for files originating from the Presenton API's local storage.
 * It ensures files are stored in an organized manner within GCS and handles potential filename conflicts.
 */

// Resolve __filename and __dirname for ES Modules to correctly locate files
/**
 * The absolute path of the current module file.
 * @type {string}
 */
const __filename = fileURLToPath(import.meta.url);
/**
 * The absolute path of the directory containing the current module file.
 * @type {string}
 */
const __dirname = path.dirname(__filename);

/**
 * Google Cloud Storage client instance.
 * Initialized with project ID and service account key file path from configuration.
 * The keyFilename is resolved to an absolute path for robustness.
 * @type {Storage}
 */
const storage = new Storage({
  projectId: config.google.gcp_project_id,
  // FIX: Resolve keyFilename to an absolute path for robustness.
  // This prevents issues if the application's working directory changes.
  // Assuming 'alti_gcp.json' is located at the project root, 4 levels up from this service file.
  keyFilename: path.join(__dirname, '../../../../alti_gcp.json'),
});

/**
 * The name of the Google Cloud Storage bucket designated for presentation files.
 * @type {string}
 */
const PRESENTATION_BUCKET = config.gcs.presentation_bucket;

/**
 * Determines the appropriate MIME content type based on a file's extension.
 * Supports common presentation and document formats like PPTX, PDF, and JSON.
 *
 * @param {string} filePath - The full path or filename of the file.
 * @returns {string} The MIME content type string (e.g., 'application/pdf') or 'application/octet-stream' if unknown.
 */
const getContentType = (filePath) => {
  const ext = path.extname(filePath).toLowerCase();
  const contentTypeMap = {
    '.pptx':
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    '.pdf': 'application/pdf',
    '.json': 'application/json',
  };
  return contentTypeMap[ext] || 'application/octet-stream';
};

/**
 * Checks if a given string is a valid URL (http or https).
 *
 * @param {string} pathOrUrl - The string to check.
 * @returns {boolean} True if the string is a valid HTTP/HTTPS URL, false otherwise.
 */
const isUrl = (pathOrUrl) => {
  try {
    const url = new URL(pathOrUrl);
    return url.protocol === 'http:' || url.protocol === 'https:';
  } catch {
    return false;
  }
};

/**
 * Uploads a presentation file to Google Cloud Storage.
 * This function can handle files from either a remote URL or a local file path.
 * For local files, it includes security checks to prevent path traversal attacks,
 * specifically mapping paths from the Presenton API's `/app_data` to a local shared volume.
 * Files are organized in GCS by `userId/conversationId/fileName` and made publicly accessible.
 * If a file with the same name already exists, a unique name is generated by appending a counter.
 *
 * @param {string} presentonPathOrUrl - The URL or local file path of the presentation.
 *                                      If a local path, it's expected to be in the format `/app_data/...`
 *                                      as returned by the Presenton API.
 * @param {string} fileName - The desired name for the file in GCS (e.g., "my_presentation.pptx").
 * @param {string} userId - The ID of the user, used for organizing files in GCS.
 * @param {string} conversationId - The ID of the conversation, used for organizing files in GCS.
 * @returns {Promise<Object>} An object containing the upload result:
 * @property {boolean} success - True if the upload was successful.
 * @property {string} publicUrl - The publicly accessible URL of the uploaded file.
 * @property {string} gcsPath - The full path of the file within the GCS bucket (e.g., `userId/conversationId/fileName.pptx`).
 * @property {string} bucket - The name of the GCS bucket where the file was uploaded.
 * @property {number} size - The size of the uploaded file in bytes.
 * @throws {Error} If the file cannot be downloaded, read, or uploaded to GCS, or if a path traversal attempt is detected.
 */
export const uploadPresentationToGCS = async (
  presentonPathOrUrl,
  fileName,
  userId,
  conversationId
) => {
  try {
    let fileBuffer;

    // Check if it's a URL or local file path
    if (isUrl(presentonPathOrUrl)) {
      // Download file from URL
      console.log('Downloading presentation from URL:', presentonPathOrUrl);
      const response = await axios.get(presentonPathOrUrl, {
        responseType: 'arraybuffer',
      });
      fileBuffer = Buffer.from(response.data);
    } else {
      // Read file from local file system
      console.log('Reading presentation from local path:', presentonPathOrUrl);

      // Handle paths from Presenton API
      // Presenton returns paths like: /app_data/exports/file.pptx
      // In Docker, Presenton's /app_data is mounted to our /app/presenton_files via shared volume
      let filePath;

      // FIX: Implement robust path traversal prevention.
      // Map Presenton's /app_data path to our shared volume mount at /app/presenton_files.
      const presentonBaseDir = '/app/presenton_files';

      // Ensure the input path starts with the expected Presenton prefix to prevent unexpected file access.
      if (!presentonPathOrUrl.startsWith('/app_data/')) {
        throw new Error('Invalid Presenton file path format. Expected to start with /app_data/.');
      }

      // Extract the relative path after '/app_data/'.
      const relativePresentonPath = presentonPathOrUrl.substring('/app_data/'.length);

      // Resolve the path against our base directory for Presenton files.
      // path.resolve will normalize the path and handle '..' segments.
      const resolvedFilePath = path.resolve(presentonBaseDir, relativePresentonPath);

      // CRITICAL SECURITY CHECK: Ensure the resolved path is still within the intended base directory.
      // This prevents path traversal attacks where 'relativePresentonPath' might contain '..'
      // to escape 'presentonBaseDir' and access arbitrary files on the server.
      if (!resolvedFilePath.startsWith(presentonBaseDir + path.sep) && resolvedFilePath !== presentonBaseDir) {
        throw new Error('Attempted path traversal detected. File access denied.');
      }

      filePath = resolvedFilePath;

      console.log('Resolved file path:', filePath);
      fileBuffer = await fs.readFile(filePath);
      console.log('File read successfully, size:', fileBuffer.length);
    }

    const contentType = getContentType(fileName);

    // Create organized path: userId/conversationId/fileName
    // Handle duplicate filenames by adding numbers
    const bucket = storage.bucket(PRESENTATION_BUCKET);
    let gcsPath = `${userId}/${conversationId}/${fileName}`;
    let file = bucket.file(gcsPath);

    // Check if file exists and find unique name
    let counter = 1;
    let exists = await file.exists();

    while (exists[0]) {
      // File exists, add counter before extension
      const ext = path.extname(fileName);
      const nameWithoutExt = path.basename(fileName, ext);
      const newFileName = `${nameWithoutExt}_${counter}${ext}`;
      gcsPath = `${userId}/${conversationId}/${newFileName}`;
      file = bucket.file(gcsPath);
      exists = await file.exists();
      counter++;
    }

    // Upload to GCS
    await file.save(fileBuffer, {
      metadata: {
        contentType,
      },
      resumable: false,
    });

    // FIX: Uncomment to make the file publicly accessible if the 'publicUrl' is intended to work.
    // If public access is not desired, the 'publicUrl' should be removed or replaced with a signed URL.
    await file.makePublic();

    // Get public URL
    const publicUrl = `https://storage.googleapis.com/${PRESENTATION_BUCKET}/${gcsPath}`;

    return {
      success: true,
      publicUrl,
      gcsPath,
      bucket: PRESENTATION_BUCKET,
      size: fileBuffer.length,
    };
  } catch (error) {
    console.error('Error uploading presentation to GCS:', error);
    throw new Error(`Failed to upload presentation to GCS: ${error.message}`);
  }
};

/**
 * Deletes a specified file from the Google Cloud Storage presentation bucket.
 *
 * @param {string} gcsPath - The full path of the file within the GCS bucket (e.g., `userId/conversationId/fileName.pptx`).
 * @returns {Promise<boolean>} True if the file was successfully deleted, false otherwise.
 */
export const deleteFromGCS = async (gcsPath) => {
  try {
    const bucket = storage.bucket(PRESENTATION_BUCKET);
    const file = bucket.file(gcsPath);
    await file.delete();
    return true;
  } catch (error) {
    console.error('Error deleting file from GCS:', error);
    return false;
  }
};