// MODIFICATION: Switched from consumer-grade '@google/generative-ai' to the enterprise-ready '@google-cloud/vertexai' SDK.
import { VertexAI, HarmCategory, HarmBlockThreshold } from '@google-cloud/vertexai';
import config from '../../../../config/index.js';
import { logger } from '../../../shared/logger.js';
import LangchainChain from './langchain-chain.model.js';
import LangchainChainVersion from './langchain-version.model.js';
import { LangchainExecutionService } from './langchainExecution.service.js';

// MODIFICATION: Initialize the enterprise VertexAI client.
// This uses Application Default Credentials (ADC) and requires GCP Project ID and Location to be configured in the environment.
// It is more secure and suitable for backend services than using a simple API key.
let vertexAIClient = null;
if (config.gcp_project_id && config.gcp_location) {
  vertexAIClient = new VertexAI({
    project: config.gcp_project_id,
    location: config.gcp_location,
  });
} else {
  // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging.
  logger.error({
    message: 'GCP_PROJECT_ID or GCP_LOCATION is not configured. Vertex AI services will not function.',
    component: 'LangchainEvaluatorService'
  });
}

/**
 * MODIFICATION: Added PII (Personally Identifiable Information) redaction utilities.
 * This is a crucial security and privacy measure to prevent sensitive user data
 * from being transmitted to the generative model.
 */

/**
 * Masks common PII patterns in a given string.
 * @param {string} text The text to sanitize.
 * @returns {string} The sanitized text with PII masked.
 */
const maskPII = (text) => {
  if (typeof text !== 'string') return text;
  // Mask email addresses
  let sanitizedText = text.replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, '[EMAIL_REDACTED]');
  // Mask phone numbers (basic North American and international formats)
  sanitizedText = sanitizedText.replace(/(\+\d{1,3}[- ]?)?\(?\d{3}\)?[-. ]?\d{3}[-. ]?\d{4}/g, '[PHONE_REDACTED]');
  // Mask common social security numbers (USA)
  sanitizedText = sanitizedText.replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[SSN_REDACTED]');
  return sanitizedText;
};

/**
 * Recursively traverses an object or array and masks PII in all string values.
 * @param {any} data The data to process (object, array, string, etc.).
 * @returns {any} A deep copy of the data with PII masked.
 */
const recursivelyMaskData = (data) => {
  if (typeof data === 'string') {
    return maskPII(data);
  }
  if (Array.isArray(data)) {
    return data.map(item => recursivelyMaskData(item));
  }
  if (typeof data === 'object' && data !== null) {
    const maskedObject = {};
    for (const key in data) {
      if (Object.prototype.hasOwnProperty.call(data, key)) {
        maskedObject[key] = recursivelyMaskData(data[key]);
      }
    }
    return maskedObject;
  }
  return data;
};


/**
 * @typedef {object} GradeResult
 * @property {object} relevance - The relevance score and justification.
 * @property {number} relevance.score - A score between 0.0 and 1.0 indicating relevance.
 * @property {string} relevance.justification - A brief explanation for the relevance score.
 * @property {object} factualAccuracy - The factual accuracy score and justification.
 * @property {number} factualAccuracy.score - A score between 0.0 and 1.0 indicating factual accuracy.
 * @property {string} factualAccuracy.justification - A brief explanation for the factual accuracy score.
 * @property {object} structureAdherence - The structure adherence score and justification.
 * @property {number} structureAdherence.score - A score between 0.0 and 1.0 indicating structure adherence.
 * @property {string} structureAdherence.justification - A brief explanation for the structure adherence score.
 */

/**
 * Grades the output of a chain run using the Gemini AI model based on provided input and criteria.
 * It constructs a detailed prompt for Gemini, parses its JSON response, and handles potential parsing failures.
 *
 * @param {object} input - The input variables or context provided to the AI model.
 * @param {any} output - The actual output generated by the AI model. Can be an object or string.
 * @param {string} [expectedCriteria='Produce a relevant, helpful, and high-quality response.'] - The specific criteria against which the output should be evaluated.
 * @returns {Promise<GradeResult>} A promise that resolves to an object containing relevance, factual accuracy, and structure adherence scores and justifications.
 */
const gradeOutputWithGemini = async (input, output, expectedCriteria) => {
  // MODIFICATION: Check for the correctly initialized Vertex AI client.
  if (!vertexAIClient) {
    // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging.
    logger.warn({
      message: 'Attempted to grade output, but Vertex AI is not initialized due to missing configuration. Returning default scores.',
      component: 'LangchainEvaluatorService'
    });
    return {
      relevance: { score: 0.0, justification: 'Grading skipped: Vertex AI not configured' },
      factualAccuracy: { score: 0.0, justification: 'Grading skipped: Vertex AI not configured' },
      structureAdherence: { score: 0.0, justification: 'Grading skipped: Vertex AI not configured' }
    };
  }

  // PLATFORM-OWNER-OPTIMIZATION: Model name is now configurable, allowing platform owners to update the evaluator model without code changes.
  const modelName = config.langchain?.evaluator_model_name || 'gemini-1.5-flash-preview-0514';

  // PLATFORM-OWNER-OPTIMIZATION: Safety settings are now configurable. This is a critical security control
  // that allows platform owners to enforce system-wide content policies.
  const safetySettings = config.langchain?.evaluator_safety_settings || [
    { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
  ];

  const model = vertexAIClient.getGenerativeModel({
    model: modelName,
    safetySettings, // Apply the safety settings to the model instance.
    generationConfig: {
      // MODIFICATION: Enforce JSON output from the model for more reliable parsing.
      responseMimeType: 'application/json',
      // PLATFORM-OWNER-OPTIMIZATION: Temperature is now configurable, allowing fine-tuning of the evaluator's determinism.
      temperature: config.langchain?.evaluator_temperature ?? 0.2,
    },
  });

  // MODIFICATION: Sanitize input and output data to remove PII before sending to the model.
  const sanitizedInput = recursivelyMaskData(input);
  const sanitizedOutput = recursivelyMaskData(output);

  const evaluationPrompt = `
You are an expert AI evaluator. Grade the quality of an AI model's output based on a given input and evaluation criteria.

Input Variables/Scope:
${JSON.stringify(sanitizedInput, null, 2)}

Expected Evaluation Criteria:
${expectedCriteria || 'Produce a relevant, helpful, and high-quality response.'}

AI Model Output to Grade:
${typeof sanitizedOutput === 'object' ? JSON.stringify(sanitizedOutput, null, 2) : String(sanitizedOutput)}

You MUST grade this output on three vectors, providing a score between 0.0 and 1.0 (where 0.0 is completely failed/irrelevant, and 1.0 is absolute perfection) and a brief justification.

You MUST return your response as a valid JSON object ONLY, with no extra text or markdown formatting blocks. Do not put markdown like \`\`\`json. Return exactly this JSON structure:
{
  "relevance": {
    "score": 0.85,
    "justification": "Explanation here..."
  },
  "factualAccuracy": {
    "score": 0.9,
    "justification": "Explanation here..."
  },
  "structureAdherence": {
    "score": 1.0,
    "justification": "Explanation here..."
  }
}
`;

  try {
    // MODIFICATION: Updated model call to match the Vertex AI SDK structure.
    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: evaluationPrompt }] }]
    });

    const response = result.response;
    // MODIFICATION: Robustly check the response structure from the Vertex AI SDK.
    if (!response.candidates?.[0]?.content?.parts?.[0]?.text) {
      // Log the finish reason if available, which can help debug safety blocks or other issues.
      const finishReason = response.candidates?.[0]?.finishReason;
      const safetyRatings = response.candidates?.[0]?.safetyRatings;
      // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging.
      logger.error({
        message: `Invalid or empty response structure from Vertex AI. Finish Reason: ${finishReason || 'UNKNOWN'}`,
        component: 'LangchainEvaluatorService',
        context: { safetyRatings }
      });
      throw new Error(`Invalid response structure from Vertex AI. Finish Reason: ${finishReason || 'UNKNOWN'}`);
    }

    // Since we requested JSON output via responseMimeType, the text should be a parsable JSON string.
    const text = response.candidates[0].content.parts[0].text;

    try {
      // The SDK should return a clean JSON string, so we can parse it directly.
      const parsed = JSON.parse(text);
      return {
        relevance: parsed.relevance || { score: 0.5, justification: 'Unknown' },
        factualAccuracy: parsed.factualAccuracy || { score: 0.5, justification: 'Unknown' },
        structureAdherence: parsed.structureAdherence || { score: 0.5, justification: 'Unknown' }
      };
    } catch (e) {
      // If JSON parsing fails, it's better to log the raw response and return a default "failed to grade" result,
      // rather than attempting an unreliable partial parse.
      // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging.
      logger.warn({
        message: 'Failed to parse Gemini grader output JSON.',
        component: 'LangchainEvaluatorService',
        context: {
          rawResponse: text,
          error: e.message
        }
      });
      return {
        relevance: { score: 0.0, justification: 'Failed to parse Gemini response' },
        factualAccuracy: { score: 0.0, justification: 'Failed to parse Gemini response' },
        structureAdherence: { score: 0.0, justification: 'Failed to parse Gemini response' }
      };
    }
  } catch (err) {
    // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging, including error stack.
    logger.error({
      message: 'Gemini grader failed',
      component: 'LangchainEvaluatorService',
      error: {
        message: err.message,
        stack: err.stack
      }
    });
    return {
      relevance: { score: 0.0, justification: `Grading failed: ${err.message}` },
      factualAccuracy: { score: 0.0, justification: `Grading failed: ${err.message}` },
      structureAdherence: { score: 0.0, justification: `Grading failed: ${err.message}` }
    };
  }
};

/**
 * @typedef {object} BenchmarkTestCase
 * @property {object} inputs - The input variables for this specific test case.
 * @property {string} expectedCriteria - The criteria for evaluating the output of this test case.
 */

/**
 * @typedef {object} VersionSummary
 * @property {string} label - A label for the version (e.g., "Current (v1)", "v2").
 * @property {number} avgLatencyMs - Average latency in milliseconds across all test cases.
 * @property {number} avgTokens - Average total tokens used across all test cases.
 * @property {number} avgRelevance - Average relevance score across all test cases.
 * @property {number} avgFactualAccuracy - Average factual accuracy score across all test cases.
 * @property {number} avgStructureAdherence - Average structure adherence score across all test cases.
 * @property {number} overallQualityScore - An overall quality score, typically an average of the three grading vectors.
 */

/**
 * @typedef {object} BenchmarkComparison
 * @property {number} testCaseIndex - The index of the test case in the provided suite.
 * @property {object} inputs - The inputs used for this test case.
 * @property {string} expectedCriteria - The expected criteria for this test case.
 * @property {object} versionA - Results for version A.
 * @property {boolean} versionA.success - Whether version A execution was successful.
 * @property {string} [versionA.error] - Error message if version A execution failed.
 * @property {number} versionA.durationMs - Execution duration for version A in milliseconds.
 * @property {object} versionA.tokenUsage - Token usage statistics for version A.
 * @property {number} versionA.tokenUsage.totalTokens - Total tokens used by version A.
 * @property {GradeResult} versionA.grades - Grading results for version A's output.
 * @property {object} versionA.outputs - The outputs generated by version A.
 * @property {object} versionB - Results for version B.
 * @property {boolean} versionB.success - Whether version B execution was successful.
 * @property {string} [versionB.error] - Error message if version B execution failed.
 * @property {number} versionB.durationMs - Execution duration for version B in milliseconds.
 * @property {object} versionB.tokenUsage - Token usage statistics for version B.
 * @property {number} versionB.tokenUsage.totalTokens - Total tokens used by version B.
 * @property {GradeResult} versionB.grades - Grading results for version B's output.
 * @property {object} versionB.outputs - The outputs generated by version B.
 */

/**
 * @typedef {object} BenchmarkResult
 * @property {boolean} success - Indicates if the benchmarking process completed successfully.
 * @property {string} chainId - The ID of the benchmarked chain.
 * @property {string} chainName - The name of the benchmarked chain.
 * @property {string} userId - The ID of the user who initiated the benchmark, for auditing.
 * @property {string} versionA - The identifier for version A.
 * @property {string} versionB - The identifier for version B.
 * @property {object} summary - Overall summary of the benchmark.
 * @property {VersionSummary} summary.versionA - Summary statistics for version A.
 * @property {VersionSummary} summary.versionB - Summary statistics for version B.
 * @property {object} summary.deltas - Differences between version B and version A.
 * @property {number} summary.deltas.qualityScoreImprovement - Improvement in overall quality score (B - A).
 * @property {number} summary.deltas.latencyDeltaMs - Change in average latency (B - A).
 * @property {number} summary.deltas.tokenEfficiencyDelta - Change in average token usage (B - A).
 * @property {BenchmarkComparison[]} comparisons - Detailed results for each test case comparison.
 */

/**
 * Runs a comparative benchmark between two prompt chain version configurations against a provided test suite.
 * It executes both versions for each test case, grades their outputs using Gemini, and aggregates performance and quality metrics.
 *
 * @param {string} chainId - The unique identifier of the Langchain chain to benchmark.
 * @param {(string|number)} versionA - The identifier for the first version to compare. Can be 'current' or a specific version number.
 * @param {(string|number)} versionB - The identifier for the second version to compare. Can be 'current' or a specific version number.
 * @param {BenchmarkTestCase[]} [testSuite] - An array of test cases, each containing inputs and expected criteria. If empty, a default test case is used.
 * @param {string} userId - The ID of the user initiating the benchmark, used for execution tracking.
 * @returns {Promise<BenchmarkResult>} A promise that resolves to an object containing the comprehensive benchmark results.
 * @throws {Error} If the specified chain or any of the version snapshots are not found.
 */
const benchmarkVersions = async (chainId, versionA, versionB, testSuite, userId) => {
  // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging.
  logger.info({
    message: 'Starting chain benchmark.',
    component: 'LangchainEvaluatorService',
    context: {
      chainId,
      versionA: String(versionA),
      versionB: String(versionB),
      userId,
      testCaseCount: testSuite?.length || 0
    }
  });

  // PLATFORM-OWNER-OPTIMIZATION: Add a configurable limit to prevent excessive resource usage and cost overruns during benchmarks.
  const maxTestCases = config.langchain?.max_benchmark_test_cases || 50;
  if (testSuite && testSuite.length > maxTestCases) {
    throw new Error(`Test suite size (${testSuite.length}) exceeds the maximum allowed limit of ${maxTestCases}.`);
  }

  // Resolve chain
  // Optimization: Use .lean() to get a plain JavaScript object, reducing Mongoose overhead.
  const chain = await LangchainChain.findById(chainId).lean();
  if (!chain) {
    throw new Error(`Chain not found: ${chainId}`);
  }

  // Resolve steps for Version A
  let stepsA = null;
  let labelA = `v${versionA}`;
  if (String(versionA).toLowerCase() === 'current') {
    stepsA = chain.steps;
    labelA = `Current (v${chain.version || 1})`;
  } else {
    // Optimization: Use .lean() to get a plain JavaScript object, reducing Mongoose overhead.
    // Indexing Recommendation: Consider adding an index on { chainId: 1, versionNumber: 1 } to LangchainChainVersion model for faster lookups.
    const snapA = await LangchainChainVersion.findOne({ chainId, versionNumber: Number(versionA) }).lean();
    if (!snapA) {
      throw new Error(`Version snapshot v${versionA} not found for chain ${chainId}`);
    }
    stepsA = snapA.steps;
  }

  // Resolve steps for Version B
  let stepsB = null;
  let labelB = `v${versionB}`;
  if (String(versionB).toLowerCase() === 'current') {
    stepsB = chain.steps;
    labelB = `Current (v${chain.version || 1})`;
  } else {
    // Optimization: Use .lean() to get a plain JavaScript object, reducing Mongoose overhead.
    // Indexing Recommendation: Consider adding an index on { chainId: 1, versionNumber: 1 } to LangchainChainVersion model for faster lookups.
    const snapB = await LangchainChainVersion.findOne({ chainId, versionNumber: Number(versionB) }).lean();
    if (!snapB) {
      throw new Error(`Version snapshot v${versionB} not found for chain ${chainId}`);
    }
    stepsB = snapB.steps;
  }

  const normalizedTestSuite = testSuite && testSuite.length > 0
    ? testSuite
    : [
        {
          inputs: chain.inputVariables.reduce((acc, curr) => ({ ...acc, [curr]: 'Test input value' }), {}),
          expectedCriteria: 'Generate a structured response addressing inputs.'
        }
      ];

  // PERFORMANCE FIX: Execute test cases in parallel using Promise.all to significantly improve benchmark speed
  // by concurrently running chain executions and grading for multiple test cases.
  const comparisonPromises = normalizedTestSuite.map(async (testCase, i) => {
    const inputs = testCase.inputs || {};
    const expected = testCase.expectedCriteria || '';

    // Run Version A
    const startA = Date.now();
    let resultA;
    try {
      resultA = await LangchainExecutionService.executeSteps(stepsA, inputs, userId);
    } catch (err) {
      resultA = { success: false, error: err.message, outputs: {}, tokenUsage: { totalTokens: 0 } };
      // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging, including error stack.
      logger.error({
        message: `Error executing version A for test case ${i}`,
        component: 'LangchainEvaluatorService',
        context: { chainId, version: String(versionA), testCaseIndex: i },
        error: {
          message: err.message,
          stack: err.stack
        }
      });
    }
    const durationA = Date.now() - startA;

    // Run Version B
    const startB = Date.now();
    let resultB;
    try {
      resultB = await LangchainExecutionService.executeSteps(stepsB, inputs, userId);
    } catch (err) {
      resultB = { success: false, error: err.message, outputs: {}, tokenUsage: { totalTokens: 0 } };
      // GCP-LOGGING-AUDIT: Formatted log for Stackdriver structured logging, including error stack.
      logger.error({
        message: `Error executing version B for test case ${i}`,
        component: 'LangchainEvaluatorService',
        context: { chainId, version: String(versionB), testCaseIndex: i },
        error: {
          message: err.message,
          stack: err.stack
        }
      });
    }
    const durationB = Date.now() - startB;

    // Grade outcomes
    const outA = resultA.outputs || {};
    const outB = resultB.outputs || {};

    const gradesA = resultA.success
      ? await gradeOutputWithGemini(inputs, outA, expected)
      : { relevance: { score: 0.0, justification: 'Execution failed' }, factualAccuracy: { score: 0.0, justification: 'Execution failed' }, structureAdherence: { score: 0.0, justification: 'Execution failed' } };

    const gradesB = resultB.success
      ? await gradeOutputWithGemini(inputs, outB, expected)
      : { relevance: { score: 0.0, justification: 'Execution failed' }, factualAccuracy: { score: 0.0, justification: 'Execution failed' }, structureAdherence: { score: 0.0, justification: 'Execution failed' } };

    return {
      testCaseIndex: i,
      inputs,
      expectedCriteria: expected,
      versionA: {
        success: resultA.success,
        error: resultA.error,
        durationMs: durationA,
        tokenUsage: resultA.tokenUsage || { totalTokens: 0 },
        grades: gradesA,
        outputs: outA
      },
      versionB: {
        success: resultB.success,
        error: resultB.error,
        durationMs: durationB,
        tokenUsage: resultB.tokenUsage || { totalTokens: 0 },
        grades: gradesB,
        outputs: outB
      },
      // Include raw scores and durations for aggregation after Promise.all
      _durationA: durationA,
      _durationB: durationB,
      _tokensA: resultA.tokenUsage?.totalTokens || 0,
      _tokensB: resultB.tokenUsage?.totalTokens || 0,
      _relevanceA: gradesA.relevance.score,
      _relevanceB: gradesB.relevance.score,
      _accuracyA: gradesA.factualAccuracy.score,
      _accuracyB: gradesB.factualAccuracy.score,
      _structureA: gradesA.structureAdherence.score,
      _structureB: gradesB.structureAdherence.score,
    };
  });

  const allComparisonsResults = await Promise.all(comparisonPromises);

  // Aggregate results after all promises have resolved
  let totalDurationA = 0;
  let totalDurationB = 0;
  let totalTokensA = 0;
  let totalTokensB = 0;

  let totalRelevanceA = 0;
  let totalRelevanceB = 0;
  let totalAccuracyA = 0;
  let totalAccuracyB = 0;
  let totalStructureA = 0;
  let totalStructureB = 0;

  const comparisons = [];

  const numCases = normalizedTestSuite.length; // Use this for division, ensure it's not zero.

  for (const compResult of allComparisonsResults) {
    totalDurationA += compResult._durationA;
    totalDurationB += compResult._durationB;
    totalTokensA += compResult._tokensA;
    totalTokensB += compResult._tokensB;

    totalRelevanceA += compResult._relevanceA;
    totalRelevanceB += compResult._relevanceB;
    totalAccuracyA += compResult._accuracyA;
    totalAccuracyB += compResult._accuracyB;
    totalStructureA += compResult._structureA;
    totalStructureB += compResult._structureB;

    // Remove aggregation-specific properties before pushing to final comparisons array
    const { _durationA, _durationB, _tokensA, _tokensB, _relevanceA, _relevanceB, _accuracyA, _accuracyB, _structureA, _structureB, ...rest } = compResult;
    comparisons.push(rest);
  }

  // BUG FIX: Handle division by zero if numCases is 0 (e.g., empty test suite and no default inputs).
  const summaryA = {
    label: labelA,
    avgLatencyMs: numCases > 0 ? totalDurationA / numCases : 0,
    avgTokens: numCases > 0 ? totalTokensA / numCases : 0,
    avgRelevance: numCases > 0 ? totalRelevanceA / numCases : 0,
    avgFactualAccuracy: numCases > 0 ? totalAccuracyA / numCases : 0,
    avgStructureAdherence: numCases > 0 ? totalStructureA / numCases : 0,
    overallQualityScore: numCases > 0 ? (totalRelevanceA + totalAccuracyA + totalStructureA) / (3 * numCases) : 0
  };

  const summaryB = {
    label: labelB,
    avgLatencyMs: numCases > 0 ? totalDurationB / numCases : 0,
    avgTokens: numCases > 0 ? totalTokensB / numCases : 0,
    avgRelevance: numCases > 0 ? totalRelevanceB / numCases : 0,
    avgFactualAccuracy: numCases > 0 ? totalAccuracyB / numCases : 0,
    avgStructureAdherence: numCases > 0 ? totalStructureB / numCases : 0,
    overallQualityScore: numCases > 0 ? (totalRelevanceB + totalAccuracyB + totalStructureB) / (3 * numCases) : 0
  };

  const deltaQuality = summaryB.overallQualityScore - summaryA.overallQualityScore;
  const deltaLatency = summaryB.avgLatencyMs - summaryA.avgLatencyMs;
  const deltaTokens = summaryB.avgTokens - summaryA.avgTokens;

  const resultSummary = {
    versionA: summaryA,
    versionB: summaryB,
    deltas: {
      qualityScoreImprovement: parseFloat(deltaQuality.toFixed(3)),
      latencyDeltaMs: parseFloat(deltaLatency.toFixed(1)),
      tokenEfficiencyDelta: parseFloat(deltaTokens.toFixed(1))
    }
  };

  // PLATFORM-OWNER-OPTIMIZATION: Add a structured summary log upon completion for better global oversight and auditing of benchmark runs.
  logger.info({
    message: 'Chain benchmark completed successfully.',
    component: 'LangchainEvaluatorService',
    context: {
      chainId,
      userId,
      versionA: String(versionA),
      versionB: String(versionB),
      summary: resultSummary
    }
  });

  return {
    success: true,
    chainId,
    chainName: chain.name,
    userId, // PLATFORM-OWNER-OPTIMIZATION: Include userId in the result for clear audit trails.
    versionA: String(versionA),
    versionB: String(versionB),
    summary: resultSummary,
    comparisons
  };
};

/**
 * @namespace langchainEvaluatorService
 * @description Service object for Langchain evaluation operations, including benchmarking different chain versions.
 */
export const langchainEvaluatorService = {
  /**
   * @function benchmarkVersions
   * @memberof langchainEvaluatorService
   * @see {@link benchmarkVersions}
   */
  benchmarkVersions
};