steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gen-lang-client-0273900650/agent-research', '-f', 'agents/agent-research/Dockerfile', '.']
images: ['gcr.io/gen-lang-client-0273900650/agent-research']
