import { ai } from '../llm.js';
import {
  codeGenerator,
  codeExplainer,
  codeDebugger,
  bestPracticesAdvisor,
  generalCodeAssistant,
} from '../services/geminiCodeService.js';

/**
 * @typedef {object} ConversationState
 * @property {Array<object>} history - An array of message objects representing the conversation history.
 * @property {string} [intent] - The detected intent of the user's last message.
 * @property {object} [response] - The response generated by a code service.
 */

/**
 * Node: Detects the user's intent using a Large Language Model (LLM).
 * It analyzes the last message in the conversation history and classifies its primary intent
 * into categories like code generation, explanation, debugging, best practices, or general conversation.
 *
 * @param {ConversationState} state - The current state of the conversation, containing the history.
 * @returns {Promise<{intent: string}>} A promise that resolves to an object containing the detected intent string.
 *   The intent will be one of: "generate_code", "explain_code", "debug_code", "best_practices", or "general_conversation".
 */
export const detectIntentNode = async (state) => {
  console.log('--- Node: detectIntentNode ---');
  const { history } = state;
  const userMessage = history[history.length - 1].content;

  const intentDetectionPrompt = `
        Analyze the following user message in a coding assistant conversation and classify its primary intent.
        Choose from one of the following intents:
        - "generate_code": User wants to create new code from a description.
        - "explain_code": User is asking for an explanation of existing code.
        - "debug_code": User is describing an error or a problem with their code and needs help fixing it.
        - "best_practices": User is asking for code reviews, improvements, or best practices.
        - "general_conversation": User is asking a follow-up question, refining a previous request, or having a general chat about the code.

        User Message: "${userMessage}"

        Return only the single intent string (e.g., "generate_code").
    `;

  let intent = 'general_conversation'; // Default intent in case of failure or unexpected response
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: intentDetectionPrompt,
    });
    // Ensure response.text exists and is a string before trimming
    if (response && typeof response.text === 'string') {
      intent = response.text.trim();
    } else {
      console.warn('LLM response.text was not a string or was empty. Defaulting to general_conversation.');
    }
  } catch (error) {
    console.error('Error detecting intent:', error);
    // Fallback to general conversation if intent detection fails due to API error, network issue, etc.
    intent = 'general_conversation';
  }
  console.log('Detected Intent:', intent);
  return { intent };
};

/**
 * Router: Directs the workflow based on the detected intent.
 * This function examines the `intent` property in the conversation state
 * and returns the name of the next node to execute.
 *
 * @param {ConversationState} state - The current state of the conversation, including the detected intent.
 * @returns {string} The name of the next node to transition to (e.g., "generate_code", "explain_code", "general_conversation").
 *   If the intent is not recognized or specific, it defaults to "general_conversation".
 */
export const routeOnIntent = (state) => {
  console.log(`--- Router: Routing on intent: ${state.intent} ---`);
  const intent = state.intent;

  const validIntents = [
    'generate_code',
    'explain_code',
    'debug_code',
    'best_practices',
  ];

  if (validIntents.includes(intent)) {
    return intent;
  }
  // If the intent is not specific, not recognized, or intent detection failed,
  // use the general assistant as a fallback.
  return 'general_conversation';
};

/**
 * A higher-order function that creates a generic node to execute a specific code service.
 * This reduces code duplication by providing a common error handling and state update mechanism.
 *
 * @param {function(Array<object>): Promise<object>} serviceFunction - The asynchronous function
 *   from `geminiCodeService.js` to execute (e.g., `codeGenerator`, `codeExplainer`).
 *   It should accept the conversation history and return a promise resolving to the service's response.
 * @returns {function(ConversationState): Promise<{response: object|{error: string}}>} An async node function
 *   that takes the conversation state, executes the provided service function, and returns the service's response
 *   or an error object if the service call fails.
 */
const executeTaskNode = (serviceFunction) => async (state) => {
  console.log(`--- Node: Executing task for intent: ${state.intent} ---`);
  const { history } = state;
  let response = null;
  try {
    response = await serviceFunction(history);
  } catch (error) {
    console.error(`Error executing task for intent ${state.intent}:`, error);
    // Return an error message in the response to be handled by subsequent nodes or the workflow.
    // This prevents unhandled promise rejections and allows the workflow to gracefully fail.
    response = { error: `Failed to process your request: ${error.message || 'Unknown error'}` };
  }
  return { response };
};

/**
 * Node: Executes the code generation service.
 * This node is responsible for generating new code based on the user's request
 * using the `codeGenerator` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{response: object|{error: string}}>} A promise that resolves to an object
 *   containing the generated code or an error message if the service call fails.
 */
export const generateCodeNode = executeTaskNode(codeGenerator);

/**
 * Node: Executes the code explanation service.
 * This node provides explanations for existing code snippets or concepts
 * using the `codeExplainer` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{response: object|{error: string}}>} A promise that resolves to an object
 *   containing the code explanation or an error message if the service call fails.
 */
export const explainCodeNode = executeTaskNode(codeExplainer);

/**
 * Node: Executes the code debugging service.
 * This node helps identify and suggest fixes for errors or issues in code
 * using the `codeDebugger` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{response: object|{error: string}}>} A promise that resolves to an object
 *   containing debugging suggestions or an error message if the service call fails.
 */
export const debugCodeNode = executeTaskNode(codeDebugger);

/**
 * Node: Executes the best practices advisory service.
 * This node provides code reviews, suggestions for improvements, and advice on best practices
 * using the `bestPracticesAdvisor` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{response: object|{error: string}}>} A promise that resolves to an object
 *   containing best practices advice or an error message if the service call fails.
 */
export const bestPracticesNode = executeTaskNode(bestPracticesAdvisor);

/**
 * Node: Executes the general code assistant service.
 * This node handles general conversational queries, follow-up questions, or refinements
 * that don't fall into specific code-related categories, using the `generalCodeAssistant` service.
 * It acts as a fallback for unrecognized or non-specific intents.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{response: object|{error: string}}>} A promise that resolves to an object
 *   containing the general assistant's response or an error message if the service call fails.
 */
export const generalConversationNode = executeTaskNode(generalCodeAssistant);