import { PubSub } from '@google-cloud/pubsub';
import { routeToSpecializedCodingAgent } from '../services/geminiCodeService.js';

// --- GCP Pub/Sub Configuration ---
// This file is now responsible for offloading tasks, not executing them.
// The long-running service functions (codeGenerator, etc.) are executed by a separate background worker.

// Initialize the Pub/Sub client.
// In a real-world GCP environment, authentication is handled automatically
// via Application Default Credentials on services like Cloud Run or Cloud Functions.
const pubsub = new PubSub();

// Define the Pub/Sub topic where all code assistant tasks will be published.
// A single topic is used, and a 'task' attribute in the message will be used for routing by the worker.
const WORKFLOW_TOPIC_NAME = process.env.CODE_ASSISTANT_TOPIC || 'code-assistant-workflow';

/**
 * Helper function to publish a task to the Pub/Sub topic.
 * @param {string} taskName - The name of the task to be executed by the worker (e.g., 'detect_intent').
 * @param {ConversationState} state - The current conversation state to be passed to the worker.
 * @returns {Promise<string>} The message ID of the published message.
 */
const publishTask = async (taskName, state) => {
  const topic = pubsub.topic(WORKFLOW_TOPIC_NAME);
  const message = {
    json: state,
    attributes: {
      task: taskName,
    },
  };
  const messageId = await topic.publishMessage(message);
  console.log(`Task '${taskName}' published with message ID: ${messageId}`);
  return messageId;
};

/**
 * @typedef {object} ConversationState
 * @property {Array<object>} history - An array of message objects representing the conversation history.
 * @property {string} [intent] - The detected intent of the user's last message.
 * @property {object} [response] - The response generated by a code service.
 */

/**
 * Node: Offloads the user's intent detection to a background worker via Pub/Sub.
 * Instead of calling the LLM directly in the request-response cycle, this function
 * publishes a message to a Pub/Sub topic. A separate worker service will subscribe
 * to this topic, execute the LLM call, and then trigger the next step in the workflow.
 *
 * @param {ConversationState} state - The current state of the conversation, containing the history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating that the task has been successfully queued. The API can immediately respond to the user.
 */
export const detectIntentNode = async (state) => {
  console.log('--- Node: Offloading detectIntentNode ---');
  try {
    // The 'detect_intent' task is the entry point for the asynchronous workflow.
    const messageId = await publishTask('detect_intent', state);
    // The function now returns immediately after publishing the task.
    // The actual LLM call happens asynchronously in a background worker.
    return { status: 'queued', messageId };
  } catch (error) {
    console.error('Error publishing detect_intent task:', error);
    // If publishing fails, the error should be handled appropriately by the caller.
    throw new Error('Failed to queue intent detection task.');
  }
};

/**
 * Router: Directs the workflow based on the detected intent.
 * NOTE: In an asynchronous, offloaded architecture, this function is no longer called
 * by the main application thread. Instead, it should be used by the background worker
 * after the 'detect_intent' task is complete to determine which task to run next.
 *
 * @param {ConversationState} state - The current state of the conversation, including the detected intent.
 * @returns {string} The name of the next node/task to execute (e.g., "generate_code", "explain_code").
 */
export const routeOnIntent = (state) => {
  console.log(`--- Worker Router: Routing on intent: ${state.intent} ---`);
  const intent = state.intent;

  const validIntents = [
    'generate_code',
    'explain_code',
    'debug_code',
    'best_practices',
  ];

  if (validIntents.includes(intent)) {
    return intent;
  }
  // If the intent is not specific, not recognized, or intent detection failed,
  // use the general assistant as a fallback.
  return 'general_conversation';
};

/**
 * A higher-order function that creates a generic node to offload a specific code service task.
 * Instead of executing a service function directly, it returns a function that publishes a
 * message to Pub/Sub, allowing a background worker to handle the heavy lifting.
 *
 * @param {string} taskName - The identifier for the task, which the background worker will use
 *   to select the correct service function (e.g., 'generate_code', 'explain_code').
 * @returns {function(ConversationState): Promise<{status: string, messageId: string}>} An async node function
 *   that takes the conversation state, publishes it as a task to Pub/Sub, and returns a confirmation.
 */
const offloadTaskNode = (taskName) => async (state) => {
  console.log(`--- Node: Offloading task for intent: ${taskName} ---`);
  try {
    let typeAgent = state.selectedAgent;
    let styleAgent = state.selectedStyle;
    let purposeAgent = state.selectedPurpose;
    let isSwarm = state.isSwarm;

    if (!typeAgent) {
      const lastMessage = state.userInput || (state.history && state.history[state.history.length - 1]?.content) || '';
      const routing = await routeToSpecializedCodingAgent(lastMessage);
      typeAgent = routing.typeAgent;
      styleAgent = routing.styleAgent;
      purposeAgent = routing.purposeAgent;
      isSwarm = routing.isSwarm;
      console.log(`[Smart Router] Routed code request:`, routing);
    }

    const stateUpdate = {
      ...state,
      selectedAgent: typeAgent,
      selectedStyle: styleAgent,
      selectedPurpose: purposeAgent,
      isSwarm
    };

    const messageId = await publishTask(taskName, stateUpdate);
    return {
      status: 'queued',
      messageId,
      selectedAgent: typeAgent,
      selectedStyle: styleAgent,
      selectedPurpose: purposeAgent,
      isSwarm
    };
  } catch (error) {
    console.error(`Error publishing task ${taskName}:`, error);
    throw new Error(`Failed to queue task: ${taskName}`);
  }
};

/**
 * Node: Offloads the code generation task to a background worker.
 * A worker will subscribe to the Pub/Sub topic, receive this task, and execute the `codeGenerator` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating the task has been queued.
 */
export const generateCodeNode = offloadTaskNode('generate_code');

/**
 * Node: Offloads the code explanation task to a background worker.
 * A worker will subscribe to the Pub/Sub topic, receive this task, and execute the `codeExplainer` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating the task has been queued.
 */
export const explainCodeNode = offloadTaskNode('explain_code');

/**
 * Node: Offloads the code debugging task to a background worker.
 * A worker will subscribe to the Pub/Sub topic, receive this task, and execute the `codeDebugger` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating the task has been queued.
 */
export const debugCodeNode = offloadTaskNode('debug_code');

/**
 * Node: Offloads the best practices advisory task to a background worker.
 * A worker will subscribe to the Pub/Sub topic, receive this task, and execute the `bestPracticesAdvisor` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating the task has been queued.
 */
export const bestPracticesNode = offloadTaskNode('best_practices');

/**
 * Node: Offloads the general code assistant task to a background worker.
 * A worker will subscribe to the Pub/Sub topic, receive this task, and execute the `generalCodeAssistant` service.
 *
 * @param {ConversationState} state - The current state of the conversation, including history.
 * @returns {Promise<{status: string, messageId: string}>} A promise that resolves to an object
 *   indicating the task has been queued.
 */
export const generalConversationNode = offloadTaskNode('general_conversation');

// NOTE ON WORKER IMPLEMENTATION:
// A separate background worker service (e.g., a Cloud Run service or Cloud Function) is required
// to process these tasks. The worker would subscribe to the 'code-assistant-workflow' Pub/Sub topic.
// On receiving a message, it would:
// 1. Read the 'task' attribute from the message (e.g., 'detect_intent', 'generate_code').
// 2. Parse the JSON payload to get the conversation state.
// 3. Import and execute the corresponding long-running service function (e.g., from `geminiCodeService.js`).
// 4. For 'detect_intent', the worker would call the LLM, use `routeOnIntent` to determine the next step,
//    and then publish a *new* task message to the same topic (e.g., with task='generate_code').
// 5. For final tasks (like 'generate_code'), the worker would deliver the result to the user,
//    for example, by writing to a database, sending a WebSocket message, or calling a webhook.