/**
 * Defines the state for the coding assistant graph.
 */
export const codeAssistantState = {
  // The user's most recent message.
  userInput: { value: null },

  // The detected intent of the user's message.
  intent: { value: null },

  // A structured log of the conversation for full context.
  history: {
    value: (x, y) => x.concat(y),
    default: () => [],
  },

  // The response generated by the assistant.
  response: { value: null },
};
