/**
 * Defines the state for the coding assistant graph.
 * This state object is designed to be secure and tenant-aware,
 * including all necessary context for a multi-user, multi-role environment.
 */
export const codeAssistantState = {
  // --- User and Tenant Context (CRITICAL for Security and Integration) ---
  // The ID of the user making the request. Essential for authorization, ownership, and audit trails.
  userId: { value: null },

  // The role of the user (e.g., 'admin', 'manager', 'user'). Used to enforce role-based access control (RBAC).
  userRole: { value: null },

  // The workspace context. This is CRITICAL to prevent data leakage between tenants (IDOR vulnerability).
  // All operations within the graph must be scoped to this workspaceId.
  workspaceId: { value: null },

  // --- Conversation State ---
  // A unique identifier for the current conversation thread, ensuring stateful interactions.
  conversationId: { value: null },

  // The user's most recent message.
  userInput: { value: null },

  // The detected intent of the user's message.
  intent: { value: null },

  // A structured log of the conversation for full context.
  history: {
    value: (x, y) => x.concat(y),
    default: () => [],
  },

  // The response generated by the assistant.
  response: { value: null },

  // --- Usage and Limits Tracking ---
  // Tracks resource consumption (e.g., tokens) for this interaction.
  // This data must be propagated to the workspace/admin level for billing and limit enforcement.
  usage: {
    value: (existingUsage, newUsage) => ({
      prompt_tokens: (existingUsage.prompt_tokens || 0) + (newUsage.prompt_tokens || 0),
      completion_tokens: (existingUsage.completion_tokens || 0) + (newUsage.completion_tokens || 0),
      total_tokens: (existingUsage.total_tokens || 0) + (newUsage.total_tokens || 0),
    }),
    default: () => ({ prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 }),
  },

  // --- Error Handling ---
  // To capture and handle any unhandled exceptions or errors gracefully during the process.
  error: { value: null },
};