import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { analyzeImageIntent } from './imageIntentAnalyzer.js';

// Mock config first, as it's imported early and its values are used in ChatGoogleGenerativeAI constructor
const mockConfig = {
  gemini_secret_key: 'mock_gemini_key_from_config',
  google: {
    gcp_project_id: 'mock-gcp-project',
    vertex_ai_region: 'mock-region',
  },
};

vi.mock('../../../../../config/index.js', () => ({
  default: mockConfig,
}));

// Mock LangChain components
// We need to mock ChatGoogleGenerativeAI to control its behavior.
// The `analyzeImageIntent` function creates a ChatGoogleGenerativeAI instance,
// then pipes it twice to form a chain. We need to mock this chain's final `invoke` method.
const mockInvoke = vi.fn();
const mockChatGoogleGenerativeAI = vi.fn(() => ({
  // Simulate the `pipe` method returning a new Runnable, which also has a `pipe` method,
  // and the final result has an `invoke` method.
  pipe: vi.fn(() => ({
    pipe: vi.fn(() => ({
      invoke: mockInvoke,
    })),
  })),
}));

vi.mock('@langchain/google-genai', () => ({
  ChatGoogleGenerativeAI: mockChatGoogleGenerativeAI,
}));

// Mock console.log to prevent output during tests and to assert calls if needed
let consoleSpy;

describe('analyzeImageIntent', () => {
  // Store original config values and env var to restore them after tests
  let originalGeminiKey;
  let originalEnvGeminiKey;

  beforeEach(() => {
    // Reset mocks before each test
    mockInvoke.mockClear();
    mockChatGoogleGenerativeAI.mockClear();
    consoleSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

    // Store original config and env var values
    originalGeminiKey = mockConfig.gemini_secret_key;
    originalEnvGeminiKey = process.env.GEMINI_API_KEY;

    // Reset config and env var for consistent testing
    mockConfig.gemini_secret_key = 'mock_gemini_key_from_config'; // Default for most tests
    delete process.env.GEMINI_API_KEY;
  });

  afterEach(() => {
    consoleSpy.mockRestore();

    // Restore original config and env var values
    mockConfig.gemini_secret_key = originalGeminiKey;
    if (originalEnvGeminiKey !== undefined) {
      process.env.GEMINI_API_KEY = originalEnvGeminiKey;
    } else {
      delete process.env.GEMINI_API_KEY;
    }
  });

  const mockSuccessfulGenerateResponse = {
    isEditable: false,
    intent: 'generate',
    editType: null,
    reasoning: 'User wants to create a new image from scratch.',
    needsMoreInfo: false,
    questions: [],
  };

  const mockSuccessfulEditResponse = {
    isEditable: true,
    intent: 'edit',
    editType: 'background change',
    reasoning: 'User wants to change the background of the provided image.',
    needsMoreInfo: false,
    questions: [],
  };

  const mockUnclearResponse = {
    isEditable: false,
    intent: 'unclear',
    editType: null,
    reasoning: 'The request is too vague to determine a clear intent.',
    needsMoreInfo: true,
    questions: ['What kind of image do you want?', 'Do you have an image you want to modify?'],
  };

  it('should analyze a "generate" intent correctly with default parameters', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    const request = 'Generate a picture of a cat playing with a ball.';
    const result = await analyzeImageIntent(request);

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith({
      apiKey: 'mock_gemini_key_from_config', // From mocked config
      model: 'gemini-3.5-flash',
      project: 'mock-gcp-project',
      location: 'mock-region',
      temperature: 0,
    });

    expect(mockInvoke).toHaveBeenCalledTimes(1);
    const invokeArgs = mockInvoke.mock.calls[0][0];
    expect(invokeArgs.request).toBe(request);
    expect(invokeArgs.hasImage).toBe('No'); // Default hasImage is false
    expect(invokeArgs.context).toBe('No previous context.'); // Default context
    expect(invokeArgs.format_instructions).toBeDefined(); // Should be generated by parser

    expect(result).toEqual(mockSuccessfulGenerateResponse);
    expect(consoleSpy).toHaveBeenCalledWith('Analyzing image intent for request using Vertex AI');
  });

  it('should analyze an "edit" intent with hasImage and context', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulEditResponse);

    const request = 'Change the background of this image to a beach scene.';
    const hasImage = true;
    const context = 'User previously uploaded an image.';
    const result = await analyzeImageIntent(request, hasImage, context);

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith({
      apiKey: 'mock_gemini_key_from_config',
      model: 'gemini-3.5-flash',
      project: 'mock-gcp-project',
      location: 'mock-region',
      temperature: 0,
    });

    expect(mockInvoke).toHaveBeenCalledTimes(1);
    const invokeArgs = mockInvoke.mock.calls[0][0];
    expect(invokeArgs.request).toBe(request);
    expect(invokeArgs.hasImage).toBe('Yes');
    expect(invokeArgs.context).toBe(context);
    expect(invokeArgs.format_instructions).toBeDefined();

    expect(result).toEqual(mockSuccessfulEditResponse);
  });

  it('should prioritize apiKey from options over config and env', async () => {
    process.env.GEMINI_API_KEY = 'env_gemini_key';
    const optionsApiKey = 'options_gemini_key';

    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('test request', false, 'context', { apiKey: optionsApiKey });

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        apiKey: optionsApiKey,
      })
    );
  });

  it('should use apiKey from config if not provided in options or env', async () => {
    // Ensure no options.apiKey and no process.env.GEMINI_API_KEY
    mockConfig.gemini_secret_key = 'config_gemini_key';
    delete process.env.GEMINI_API_KEY;

    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('test request');

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        apiKey: 'config_gemini_key',
      })
    );
  });

  it('should use apiKey from environment variable if not provided in options or config', async () => {
    // Ensure no options.apiKey and no config.gemini_secret_key
    mockConfig.gemini_secret_key = undefined;
    process.env.GEMINI_API_KEY = 'env_gemini_key';

    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('test request');

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        apiKey: 'env_gemini_key',
      })
    );
  });

  it('should use provided modelName', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);
    const customModel = 'gemini-pro';

    await analyzeImageIntent('test request', false, 'context', { modelName: customModel });

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        model: customModel,
      })
    );
  });

  it('should use default modelName if not provided', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('test request');

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        model: 'gemini-3.5-flash', // Default
      })
    );
  });

  it('should propagate errors from the LLM chain', async () => {
    const mockError = new Error('LLM chain failed');
    mockInvoke.mockRejectedValue(mockError);

    const request = 'Generate a picture.';
    await expect(analyzeImageIntent(request)).rejects.toThrow(mockError);
  });

  it('should handle unclear intent', async () => {
    mockInvoke.mockResolvedValue(mockUnclearResponse);

    const request = 'Do something with an image.';
    const result = await analyzeImageIntent(request);

    expect(result).toEqual(mockUnclearResponse);
    expect(mockInvoke).toHaveBeenCalledTimes(1);
  });

  it('should correctly pass "Yes" for hasImage when true', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('request', true);

    const invokeArgs = mockInvoke.mock.calls[0][0];
    expect(invokeArgs.hasImage).toBe('Yes');
  });

  it('should correctly pass "No" for hasImage when false', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('request', false);

    const invokeArgs = mockInvoke.mock.calls[0][0];
    expect(invokeArgs.hasImage).toBe('No');
  });

  it('should use default context if not provided', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('request', false);

    const invokeArgs = mockInvoke.mock.calls[0][0];
    expect(invokeArgs.context).toBe('No previous context.');
  });

  it('should pass project and location from config to ChatGoogleGenerativeAI', async () => {
    mockInvoke.mockResolvedValue(mockSuccessfulGenerateResponse);

    await analyzeImageIntent('test request');

    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledTimes(1);
    expect(mockChatGoogleGenerativeAI).toHaveBeenCalledWith(
      expect.objectContaining({
        project: 'mock-gcp-project',
        location: 'mock-region',
      })
    );
  });
});