import { GoogleGenAI } from '@google/genai';
import * as fs from 'node:fs';
import * as path from 'node:path';
import dotenv from 'dotenv';
import Redis from 'ioredis';
import { RateLimiterRedis } from 'rate-limiter-flexible';
import { GCPStorageService } from '../services/gcpStorageService.js';
import config from '../../../../../config/index.js';
import { RedisClient } from '../../../../shared/redis.js';

dotenv.config();

// --- Enterprise Rate Limiting & DDOS Guard ---
// Establish a connection to the Redis server for rate limiting.
// It's configured to fail fast if Redis is unavailable, preventing requests from hanging.
const redisClient = RedisClient.isEnabled
  ? new Redis(config.redis.url, { enableOfflineQueue: false })
  : null;

if (redisClient) {
  redisClient.on('error', err => console.error('Redis client error in imagegen4:', err));
}

// Rate limiter for authenticated users, identified by their unique userId.
// This is a generous limit for legitimate users, allowing 20 image generations per hour.
// It protects against abuse from a single compromised account.
const userRateLimiter = redisClient
  ? new RateLimiterRedis({
      storeClient: redisClient,
      keyPrefix: 'rate_limit_imagegen_user',
      points: 20, // 20 requests
      duration: 3600, // per 1 hour
      blockDuration: 3600, // Block for 1 hour if limit is exceeded
    })
  : null;

// A much stricter rate limiter for unauthenticated (public) users, identified by their IP address.
// This is a critical defense against anonymous DDOS and cost-runaway attacks.
// It allows only 5 image generations per day from a single IP.
const ipRateLimiter = redisClient
  ? new RateLimiterRedis({
      storeClient: redisClient,
      keyPrefix: 'rate_limit_imagegen_ip',
      points: 5, // 5 requests
      duration: 86400, // per 1 day (24 * 60 * 60)
      blockDuration: 86400, // Block for 1 day if limit is exceeded
    })
  : null;

// A global burst limiter to protect the overall system from sudden traffic spikes.
// It ensures that the service can't be overwhelmed by a flood of requests, even from many different users/IPs.
// It allows a maximum of 10 requests to be processed every 10 seconds across the entire service.
const globalBurstLimiter = redisClient
  ? new RateLimiterRedis({
      storeClient: redisClient,
      keyPrefix: 'rate_limit_imagegen_global_burst',
      points: 10, // 10 requests
      duration: 10, // per 10 seconds
    })
  : null;
// --- End of Rate Limiting Setup ---

/**
 * @const {string} gcpKeyPath
 * @description The absolute path to the GCP service account key file (`alti_gcp.json`), resolved from the current working directory.
 * @private
 */
const gcpKeyPath = path.join(process.cwd(), 'alti_gcp.json');

/**
 * @const {GCPStorageService} gcpStorage
 * @description An instance of the GCPStorageService, configured for the 'alti_assistant_generated_photo' bucket.
 * This service handles the uploading of generated images to Google Cloud Storage.
 * @private
 */
const gcpStorage = new GCPStorageService(
  'alti_assistant_generated_photo',
  gcpKeyPath
);

/**
 * Generates an image using Google's Vertex AI Imagen 4.0 model based on a text prompt,
 * and then uploads the resulting image to a Google Cloud Storage bucket.
 *
 * This service function is protected by multiple layers of rate limiting to prevent abuse,
 * control costs, and ensure service stability.
 *
 * @async
 * @function imagegen_4
 * @param {string} prompt - The text prompt to be used for image generation.
 * @param {string} [outputFilename] - Optional. The desired filename for the uploaded image in GCP Storage.
 *                                    If a full path is provided (e.g., '/tmp/my_image.png'), only the basename ('my_image.png') will be used.
 *                                    If not provided, a default filename like 'imagen-1.png' will be generated by the API response handler.
 * @param {object} rateLimitContext - The context for applying rate limits.
 * @param {string} rateLimitContext.ip - The IP address of the requester, used for unauthenticated rate limiting.
 * @param {string} [rateLimitContext.userId] - The ID of the authenticated user. If provided, a more generous rate limit is applied.
 * @returns {Promise<string>} A promise that resolves with the public URL of the uploaded image in GCP Storage.
 * @throws {Error} Throws an error if the rate limit is exceeded, if the image generation via the GenAI API fails,
 *                 or if the upload to GCP Storage fails. Rate limit errors will have a `statusCode` of 429.
 */
export async function imagegen_4(prompt, outputFilename, { ip, userId }) {
  try {
    // --- DDOS Guard & Rate Limiting Enforcement ---
    if (redisClient && redisClient.status === 'ready') {
      try {
        // 1. Apply the global burst limiter first to handle sudden traffic spikes.
        if (globalBurstLimiter) {
          await globalBurstLimiter.consume('global');
        }

        // 2. Apply user-specific or IP-specific limits based on authentication status.
        if (userId && userRateLimiter) {
          // If a user is authenticated, consume from their personal rate limit bucket.
          await userRateLimiter.consume(userId);
        } else if (ipRateLimiter) {
          // For anonymous requests, consume from the much stricter IP-based rate limit bucket.
          await ipRateLimiter.consume(ip);
        }
      } catch (rateLimitError) {
        if (rateLimitError instanceof Error) {
          console.error('Redis connection or execution error in rate limiter:', rateLimitError);
          // Fail open on connection errors
        } else {
          // Actual rate limit exceeded
          const err = new Error('Rate limit exceeded. Please try again later.');
          err.statusCode = 429;
          throw err;
        }
      }
    }
    // --- End of DDOS Guard ---

    const ai = new GoogleGenAI({
      vertexAI: {
        project: config.google.gcp_project_id,
        location: config.google.vertex_ai_region || 'us-central1',
      },
    });

    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1, // Currently configured to generate a single image.
        personGeneration: 'allow_all',
        imageSize: '1K',
      },
    });

    let idx = 1;
    let uploadedUrl = null;

    // Iterate through generated images. With numberOfImages: 1, this loop runs exactly once.
    for (const generatedImage of response.generatedImages) {
      const imgBytes = generatedImage.image.imageBytes;
      const buffer = Buffer.from(imgBytes, 'base64');

      // Determine the filename for the uploaded image in GCP Storage.
      // If outputFilename is provided, use its basename. Otherwise, generate a default.
      const filename = outputFilename
        ? path.basename(outputFilename)
        : `imagen-${idx}.png`;

      // Upload the image buffer to the GCP bucket.
      uploadedUrl = await gcpStorage.uploadBuffer(buffer, filename, 'image/png');
      idx++; // Increment for potential future multiple images, though currently only 1.
    }

    return uploadedUrl;
  } catch (error) {
    // Check if the error is from the rate limiter.
    if (error.msBeforeNext) {
      const retryAfter = Math.ceil(error.msBeforeNext / 1000);
      // Create a specific error that the upstream controller can use to send a 429 response.
      const rateLimitError = new Error(
        `Rate limit exceeded. Try again in ${retryAfter} seconds.`
      );
      rateLimitError.statusCode = 429; // Standard HTTP status code for "Too Many Requests"
      rateLimitError.retryAfter = retryAfter; // Value for the 'Retry-After' header
      throw rateLimitError;
    }

    // Log other errors for debugging purposes.
    console.error('Error during image generation or upload:', error);
    // Re-throw a more descriptive error to the caller, ensuring unhandled promise rejections are avoided.
    throw new Error(`Failed to generate or upload image: ${error.message}`);
  }
}