import mongoose from 'mongoose';

/**
 * @typedef {object} QueryMemoryDocument
 * @property {string} tenantId - The ID of the tenant this query memory belongs to. Essential for data isolation and platform oversight.
 * @property {string} userId - The ID of the user associated with this query memory entry.
 * @property {string} query - The original query text submitted by the user.
 * @property {string} answer - The answer generated by the LlamaIndex engine in response to the query.
 * @property {string} [engine='vector'] - The identifier of the LlamaIndex engine that produced this answer (e.g., 'vector', 'chat'). Defaults to 'vector'.
 * @property {string[]} [topics=[]] - An array of extracted topics from this query, used for relevance matching in subsequent queries.
 * @property {string[]} [queryTokens=[]] - An array of tokenized words from the query, used for fast Jaccard pre-filtering.
 * @property {number} [confidence=0.0] - The routing confidence score at the time this query memory was recorded.
 * @property {Date} createdAt - The timestamp when this query memory entry was created.
 * @property {Date} updatedAt - The timestamp when this query memory entry was last updated.
 * @property {Date} expiresAt - The timestamp when this document should be automatically deleted. Enables tenant-specific retention policies.
 */

/**
 * Mongoose Schema for the QueryMemory Model.
 *
 * This schema defines the structure for persisting meaningful query-answer pairs
 * from LlamaIndex sessions. It is utilized by the Cross-Session Query Memory
 * service to inject relevant prior context into subsequent queries, thereby
 * enabling conversational continuity across sessions without requiring
 * client-side session management.
 *
 * @description
 * **Multi-Tenancy:** The `tenantId` field is crucial for isolating data between different tenants,
 * enabling the Platform Owner to perform global oversight, manage tenant-specific data, and generate
 * tenant-level statistics. All indexes are prefixed with `tenantId` to ensure efficient, tenant-scoped queries.
 *
 * **TTL (Time-To-Live):** Data retention is managed via the `expiresAt` field, which is indexed for
 * automatic TTL deletion. This approach allows for flexible, tenant-specific retention policies
 * to be configured at the platform level, overriding any default settings. The application layer
 * is responsible for setting the `expiresAt` value upon document creation based on the tenant's configuration.
 *
 * @type {mongoose.Schema<QueryMemoryDocument>}
 */
const QueryMemorySchema = new mongoose.Schema(
  {
    // PLATFORM OWNER FEATURE: Added tenantId for multi-tenancy, data isolation, and global oversight.
    tenantId: {
      type: String,
      required: true,
    },
    userId: {
      type: String,
      required: true,
    },
    query: {
      type: String,
      required: true,
    },
    answer: {
      type: String,
      required: true,
    },
    engine: {
      type: String,
      default: 'vector',
    },
    topics: {
      type: [String],
      default: [],
    },
    queryTokens: {
      type: [String],
      default: [],
    },
    confidence: {
      type: Number,
      default: 0.0,
    },
    // PLATFORM OWNER FEATURE: Added expiresAt to enable configurable, per-tenant data retention policies.
    expiresAt: {
      type: Date,
      required: true,
    },
  },
  {
    timestamps: true, // Automatically manages createdAt and updatedAt
  }
);

// PLATFORM OWNER OPTIMIZATION: All indexes are tenant-aware for performance and data isolation.

// Compound index for fetching recent history for a specific user within a tenant.
QueryMemorySchema.index({ tenantId: 1, userId: 1, createdAt: -1 });

// Compound multikey index for fast Jaccard pre-filtering of tokens for a user within a tenant.
QueryMemorySchema.index({ tenantId: 1, userId: 1, queryTokens: 1 });

// Compound multikey index for fast topic relevance matching for a user within a tenant.
QueryMemorySchema.index({ tenantId: 1, userId: 1, topics: 1 });

// PLATFORM OWNER FEATURE: TTL index on `expiresAt` for flexible, per-tenant data retention.
// The document will be deleted when the `expiresAt` date is reached.
// The application logic must set this field based on tenant configuration (e.g., createdAt + 90 days).
QueryMemorySchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

/**
 * Mongoose Model for QueryMemory.
 *
 * Represents the collection of stored query-answer pairs used for cross-session
 * conversational memory. This model provides the interface for interacting
 * with the `querymemories` collection in MongoDB.
 *
 * @type {mongoose.Model<QueryMemoryDocument>}
 * @constant
 */
const QueryMemory =
  mongoose.models.QueryMemory || mongoose.model('QueryMemory', QueryMemorySchema);

export default QueryMemory;