import mongoose from 'mongoose';

/**
 * @typedef {object} DocumentMetadataSchema
 * @property {string} docId - The unique identifier for the document.
 * @property {string} userId - The unique identifier of the user who owns this document.
 * @property {string} fileName - The original name of the document file.
 * @property {string} summary - A brief summary of the document's content.
 * @property {string[]} topics - An array of main topics identified within the document.
 * @property {string[]} entities - An array of key entities (e.g., persons, organizations, locations) mentioned in the document.
 * @property {'Elementary'|'Intermediate'|'Advanced'|'Highly Technical'} complexity - The estimated complexity level of the document's content.
 * @property {string} audience - The intended audience for the document (e.g., 'General', 'Developers', 'Researchers').
 * @property {string} temporalContext - Describes the temporal relevance or context of the document (e.g., 'Timeless', '2023 Q4', 'Historical').
 * @property {Date} createdAt - The timestamp when the document metadata was created.
 * @property {Date} updatedAt - The timestamp when the document metadata was last updated.
 */

/**
 * Mongoose Schema for Document Metadata.
 *
 * Defines the structure for storing metadata about documents processed by LlamaIndex.
 * This metadata includes document identification, user ownership, file details,
 * content summary, topics, entities, and contextual information like complexity and audience.
 *
 * @type {mongoose.Schema<DocumentMetadataSchema>}
 */
const DocumentMetadataSchema = new mongoose.Schema(
  {
    /**
     * The unique identifier for the document.
     * This ID is typically generated by the LlamaIndex processing pipeline.
     * @type {string}
     * @required
     * @index
     */
    docId: {
      type: String,
      required: true,
      index: true
    },
    /**
     * The unique identifier of the user who owns this document.
     * This allows for multi-tenancy and user-specific document management.
     * @type {string}
     * @required
     * @index
     */
    userId: {
      type: String,
      required: true,
      index: true
    },
    /**
     * The original name of the document file.
     * @type {string}
     * @required
     */
    fileName: {
      type: String,
      required: true
    },
    /**
     * A brief summary of the document's content, generated during processing.
     * @type {string}
     * @required
     */
    summary: {
      type: String,
      required: true
    },
    /**
     * An array of main topics identified within the document.
     * @type {string[]}
     * @default []
     */
    topics: {
      type: [String],
      default: []
    },
    /**
     * An array of key entities (e.g., persons, organizations, locations) mentioned in the document.
     * @type {string[]}
     * @default []
     */
    entities: {
      type: [String],
      default: []
    },
    /**
     * The estimated complexity level of the document's content.
     * @type {'Elementary'|'Intermediate'|'Advanced'|'Highly Technical'}
     * @enum {string[]}
     * @default 'Intermediate'
     */
    complexity: {
      type: String,
      enum: ['Elementary', 'Intermediate', 'Advanced', 'Highly Technical'],
      default: 'Intermediate'
    },
    /**
     * The intended audience for the document.
     * @type {string}
     * @default 'General'
     */
    audience: {
      type: String,
      default: 'General'
    },
    /**
     * Describes the temporal relevance or context of the document.
     * @type {string}
     * @default 'Timeless'
     */
    temporalContext: {
      type: String,
      default: 'Timeless'
    }
  },
  {
    /**
     * Mongoose option to automatically add `createdAt` and `updatedAt` timestamps.
     * @type {boolean}
     */
    timestamps: true
  }
);

/**
 * Compound unique index to ensure that each user has only one metadata entry per document.
 * This prevents duplicate metadata records for the same document owned by the same user.
 * @property {number} userId - Ascending index on userId.
 * @property {number} docId - Ascending index on docId.
 * @property {boolean} unique - Ensures the combination of userId and docId is unique.
 */
DocumentMetadataSchema.index({ userId: 1, docId: 1 }, { unique: true });

/**
 * Mongoose Model for Document Metadata.
 *
 * Provides an interface for interacting with the `document_metadata` collection in MongoDB.
 * It allows for CRUD operations on document metadata records, ensuring data integrity
 * according to the `DocumentMetadataSchema`.
 *
 * @type {mongoose.Model<DocumentMetadataSchema>}
 */
const DocumentMetadata = mongoose.models.DocumentMetadata || mongoose.model('DocumentMetadata', DocumentMetadataSchema);

/**
 * Exports the DocumentMetadata Mongoose Model.
 * @exports DocumentMetadata
 */
export default DocumentMetadata;