import mongoose from 'mongoose';

/**
 * QueryMemory Model
 *
 * Persists meaningful query→answer pairs from LlamaIndex sessions.
 * Used by the Cross-Session Query Memory service to inject relevant
 * prior context into subsequent queries, enabling conversational continuity
 * across sessions without requiring client-side session management.
 *
 * TTL: 90 days (entries auto-expire to prevent unbounded growth).
 */
const QueryMemorySchema = new mongoose.Schema(
  {
    userId: {
      type: String,
      required: true,
      index: true,
    },
    // The original query text
    query: {
      type: String,
      required: true,
    },
    // The answer generated by the engine
    answer: {
      type: String,
      required: true,
    },
    // Which engine produced this answer
    engine: {
      type: String,
      default: 'vector',
    },
    // Extracted topics from this query (for relevance matching)
    topics: {
      type: [String],
      default: [],
    },
    // Tokenized query words (for fast Jaccard pre-filtering)
    queryTokens: {
      type: [String],
      default: [],
    },
    // Routing confidence at time of recording
    confidence: {
      type: Number,
      default: 0.0,
    },
  },
  {
    timestamps: true,
  }
);

QueryMemorySchema.index({ userId: 1, createdAt: -1 });

// 90-day TTL auto-expiry
QueryMemorySchema.index({ createdAt: 1 }, { expireAfterSeconds: 90 * 24 * 60 * 60 });

const QueryMemory =
  mongoose.models.QueryMemory || mongoose.model('QueryMemory', QueryMemorySchema);

export default QueryMemory;
