import mongoose from 'mongoose';

/**
 * @typedef {object} QueryMemoryDocument
 * @property {string} userId - The ID of the user associated with this query memory entry.
 * @property {string} query - The original query text submitted by the user.
 * @property {string} answer - The answer generated by the LlamaIndex engine in response to the query.
 * @property {string} [engine='vector'] - The identifier of the LlamaIndex engine that produced this answer (e.g., 'vector', 'chat'). Defaults to 'vector'.
 * @property {string[]} [topics=[]] - An array of extracted topics from this query, used for relevance matching in subsequent queries.
 * @property {string[]} [queryTokens=[]] - An array of tokenized words from the query, used for fast Jaccard pre-filtering.
 * @property {number} [confidence=0.0] - The routing confidence score at the time this query memory was recorded.
 * @property {Date} createdAt - The timestamp when this query memory entry was created. Used for TTL expiry.
 * @property {Date} updatedAt - The timestamp when this query memory entry was last updated.
 */

/**
 * Mongoose Schema for the QueryMemory Model.
 *
 * This schema defines the structure for persisting meaningful query-answer pairs
 * from LlamaIndex sessions. It is utilized by the Cross-Session Query Memory
 * service to inject relevant prior context into subsequent queries, thereby
 * enabling conversational continuity across sessions without requiring
 * client-side session management.
 *
 * @description
 * **TTL (Time-To-Live):** Entries in this collection are configured to auto-expire
 * after 90 days from their `createdAt` timestamp to prevent unbounded growth
 * and ensure data relevance.
 *
 * @type {mongoose.Schema<QueryMemoryDocument>}
 */
const QueryMemorySchema = new mongoose.Schema(
  {
    userId: {
      type: String,
      required: true,
      // OPTIMIZATION: Removed redundant single-field index on userId.
      // The compound index { userId: 1, createdAt: -1 } already covers queries filtering by userId alone.
    },
    query: {
      type: String,
      required: true,
    },
    answer: {
      type: String,
      required: true,
    },
    engine: {
      type: String,
      default: 'vector',
    },
    topics: {
      type: [String],
      default: [],
    },
    queryTokens: {
      type: [String],
      default: [],
    },
    confidence: {
      type: Number,
      default: 0.0,
    },
  },
  {
    timestamps: true,
  }
);

// OPTIMIZATION: Compound index for fetching recent history for a user.
QueryMemorySchema.index({ userId: 1, createdAt: -1 });

// OPTIMIZATION: Compound multikey index for fast Jaccard pre-filtering of tokens per user.
QueryMemorySchema.index({ userId: 1, queryTokens: 1 });

// OPTIMIZATION: Compound multikey index for fast topic relevance matching per user.
QueryMemorySchema.index({ userId: 1, topics: 1 });

// 90-day TTL auto-expiry
QueryMemorySchema.index({ createdAt: 1 }, { expireAfterSeconds: 90 * 24 * 60 * 60 });

/**
 * Mongoose Model for QueryMemory.
 *
 * Represents the collection of stored query-answer pairs used for cross-session
 * conversational memory. This model provides the interface for interacting
 * with the `querymemories` collection in MongoDB.
 *
 * @type {mongoose.Model<QueryMemoryDocument>}
 * @constant
 */
const QueryMemory =
  mongoose.models.QueryMemory || mongoose.model('QueryMemory', QueryMemorySchema);

export default QueryMemory;