import mongoose from 'mongoose';

/**
 * @typedef {object} DocumentMetadataSchema
 * @property {string} docId - The unique identifier for the document.
 * @property {string} tenantId - The unique identifier for the tenant account this document belongs to. Essential for platform-level data isolation and management.
 * @property {string} userId - The unique identifier of the user within the tenant who owns this document.
 * @property {'active'|'archived'|'quarantined'} status - The operational status of the document, allowing Platform Owners to manage content (e.g., quarantine for review).
 * @property {string} fileName - The original name of the document file.
 * @property {string} summary - A brief summary of the document's content.
 * @property {string[]} topics - An array of main topics identified within the document.
 * @property {string[]} entities - An array of key entities (e.g., persons, organizations, locations) mentioned in the document.
 * @property {'Elementary'|'Intermediate'|'Advanced'|'Highly Technical'} complexity - The estimated complexity level of the document's content.
 * @property {string} audience - The intended audience for the document (e.g., 'General', 'Developers', 'Researchers').
 * @property {string} temporalContext - Describes the temporal relevance or context of the document (e.g., 'Timeless', '2023 Q4', 'Historical').
 * @property {object} platformMetadata - A flexible object for Platform Owner/Super Admin internal notes, flags, or metadata. Not exposed to tenants.
 * @property {Date} createdAt - The timestamp when the document metadata was created.
 * @property {Date} updatedAt - The timestamp when the document metadata was last updated.
 */

/**
 * Mongoose Schema for Document Metadata.
 *
 * Defines the structure for storing metadata about documents processed by LlamaIndex.
 * This schema is designed for a multi-tenant architecture, enabling robust platform-level
 * oversight and management by a Platform Owner. It includes tenant and user identification,
 * content analysis, contextual information, and administrative controls.
 *
 * @type {mongoose.Schema<DocumentMetadataSchema>}
 */
const DocumentMetadataSchema = new mongoose.Schema(
  {
    /**
     * The unique identifier for the document, typically generated by the LlamaIndex processing pipeline.
     * @type {string}
     * @required
     * @index
     */
    docId: {
      type: String,
      required: true,
      index: true
    },
    /**
     * The identifier for the tenant account. This is the primary key for data partitioning
     * and allows the Platform Owner to perform tenant-specific operations, analytics, and management.
     * @type {string}
     * @required
     * @index
     */
    tenantId: {
      type: String,
      required: true,
      index: true
    },
    /**
     * The unique identifier of the user who owns this document.
     * This allows for user-specific document management within a tenant.
     * @type {string}
     * @required
     */
    userId: {
      type: String,
      required: true
    },
    /**
     * The status of the document, enabling Platform Owner control.
     * 'active': Normal state.
     * 'archived': Not in active use but retained.
     * 'quarantined': Disabled by an admin pending review (e.g., for policy violations).
     * @type {'active'|'archived'|'quarantined'}
     * @default 'active'
     * @index
     */
    status: {
      type: String,
      enum: ['active', 'archived', 'quarantined'],
      default: 'active',
      index: true
    },
    /**
     * The original name of the document file.
     * @type {string}
     * @required
     */
    fileName: {
      type: String,
      required: true
    },
    /**
     * A brief summary of the document's content, generated during processing.
     * @type {string}
     * @required
     */
    summary: {
      type: String,
      required: true
    },
    /**
     * An array of main topics identified within the document.
     * @type {string[]}
     * @default []
     */
    topics: {
      type: [String],
      default: []
    },
    /**
     * An array of key entities (e.g., persons, organizations, locations) mentioned in the document.
     * @type {string[]}
     * @default []
     */
    entities: {
      type: [String],
      default: []
    },
    /**
     * The estimated complexity level of the document's content.
     * @type {'Elementary'|'Intermediate'|'Advanced'|'Highly Technical'}
     * @enum {string[]}
     * @default 'Intermediate'
     */
    complexity: {
      type: String,
      enum: ['Elementary', 'Intermediate', 'Advanced', 'Highly Technical'],
      default: 'Intermediate'
    },
    /**
     * The intended audience for the document.
     * @type {string}
     * @default 'General'
     */
    audience: {
      type: String,
      default: 'General'
    },
    /**
     * Describes the temporal relevance or context of the document.
     * @type {string}
     * @default 'Timeless'
     */
    temporalContext: {
      type: String,
      default: 'Timeless'
    },
    /**
     * A field reserved for Platform Owner/Super Admin use. Can store internal notes,
     * override flags, or other administrative metadata.
     * `select: false` ensures this data is not returned in standard queries,
     * preventing accidental exposure to tenants.
     * @type {object}
     * @default {}
     */
    platformMetadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
      select: false
    }
  },
  {
    /**
     * Mongoose option to automatically add `createdAt` and `updatedAt` timestamps.
     * @type {boolean}
     */
    timestamps: true
  }
);

/**
 * Compound unique index to ensure data integrity. A specific document (`docId`)
 * can only be associated with a user (`userId`) within a tenant (`tenantId`) once.
 */
DocumentMetadataSchema.index({ tenantId: 1, userId: 1, docId: 1 }, { unique: true });

/**
 * Compound index to optimize fetching a specific user's documents within a tenant,
 * sorted by creation date. This is a common query for user-facing interfaces.
 */
DocumentMetadataSchema.index({ tenantId: 1, userId: 1, createdAt: -1 });

/**
 * Index to optimize fetching all documents across the entire platform, sorted by
 * creation date. Essential for the Platform Owner's global activity feed and system-wide monitoring.
 */
DocumentMetadataSchema.index({ createdAt: -1 });

/**
 * Index to optimize Platform Owner queries for documents by status within a tenant.
 * For example, efficiently listing all 'quarantined' documents for a specific tenant.
 */
DocumentMetadataSchema.index({ tenantId: 1, status: 1 });

/**
 * Mongoose Model for Document Metadata.
 *
 * Provides an interface for interacting with the `document_metadata` collection in MongoDB.
 * It allows for CRUD operations on document metadata records, ensuring data integrity
 * according to the `DocumentMetadataSchema`.
 *
 * @type {mongoose.Model<DocumentMetadataSchema>}
 */
const DocumentMetadata = mongoose.models.DocumentMetadata || mongoose.model('DocumentMetadata', DocumentMetadataSchema);

/**
 * Exports the DocumentMetadata Mongoose Model.
 * @exports DocumentMetadata
 */
export default DocumentMetadata;