import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const execPromise = util.promisify(exec);

/**
 * Commits the modified files and pushes them.
 * @param {string} branchName - Name of the branch to push to.
 * @param {string} commitMessage - Commit message generated by LLM.
 * @returns {Promise<{success: boolean, output: string}>}
 */
export async function commitAndPush(branchName, commitMessage, retries = 5, delay = 2000) {
  const backendPath = path.resolve(__dirname, '../../');
  console.log(`Committing changes with message: "${commitMessage}"`);
  try {
    const safeMessage = commitMessage.replace(/"/g, '\\"');
    
    await execPromise('git add .', { cwd: backendPath });
    
    const { stdout: statusOut } = await execPromise('git status --porcelain', { cwd: backendPath });
    if (!statusOut.trim()) {
      return { success: true, output: 'No changes to commit.' };
    }
    
    await execPromise(`git commit -m "${safeMessage}"`, { cwd: backendPath });
    
    let attempt = 0;
    while (attempt < retries) {
      try {
        const { stdout, stderr } = await execPromise(`git push origin HEAD:${branchName}`, { cwd: backendPath });
        return {
          success: true,
          output: `${stdout}\n${stderr}`,
        };
      } catch (pushError) {
        attempt++;
        console.warn(`Git push collision detected (Attempt ${attempt}/${retries}). Rebasing...`);
        try {
          // Rebase local changes to avoid merge commits
          await execPromise(`git pull --rebase origin ${branchName}`, { cwd: backendPath });
        } catch (rebaseError) {
          console.error('Git rebase failed. Aborting rebase...', rebaseError);
          await execPromise('git rebase --abort', { cwd: backendPath }).catch(() => {});
        }
        
        if (attempt >= retries) {
          throw pushError;
        }
        
        // Wait with exponential backoff + jitter
        const sleepTime = delay * Math.pow(2, attempt) + Math.random() * 1000;
        await new Promise(resolve => setTimeout(resolve, sleepTime));
      }
    }
  } catch (error) {
    console.error('Failed to commit and push:', error);
    return {
      success: false,
      output: error.stdout || error.stderr || error.message,
    };
  }
}
