import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const execPromise = util.promisify(exec);

/**
 * Commits the modified files and pushes them.
 * @param {string} branchName - Name of the branch to push to.
 * @param {string} commitMessage - Commit message generated by LLM.
 * @returns {Promise<{success: boolean, output: string}>}
 */
export async function commitAndPush(branchName, commitMessage, retries = 5, delay = 2000) {
  const backendPath = path.resolve(__dirname, '../../');
  console.log(`Committing changes with message: "${commitMessage}"`);
  
  const safeMessage = commitMessage.replace(/"/g, '\\"');
  let attempt = 0;
  
  while (attempt < retries) {
    try {
      // Add files
      await execPromise('git add .', { cwd: backendPath });
      
      // Check status
      const { stdout: statusOut } = await execPromise('git status --porcelain', { cwd: backendPath });
      if (!statusOut.trim()) {
        return { success: true, output: 'No changes to commit.' };
      }
      
      // Commit
      await execPromise(`git commit -m "${safeMessage}"`, { cwd: backendPath });
      
      // Push
      const { stdout, stderr } = await execPromise(`git push origin HEAD:${branchName}`, { cwd: backendPath });
      return {
        success: true,
        output: `${stdout}\n${stderr}`,
      };
    } catch (gitError) {
      attempt++;
      const errorMessage = gitError.stdout || gitError.stderr || gitError.message || '';
      console.warn(`Git operation failed (Attempt ${attempt}/${retries}): ${errorMessage.trim()}`);
      
      // If it's a lock file issue or push collision, try to rebase or clean up
      if (errorMessage.includes('index.lock') || errorMessage.includes('push')) {
        try {
          // Rebase local changes to avoid merge conflicts
          await execPromise(`git pull --rebase origin ${branchName}`, { cwd: backendPath });
        } catch (rebaseError) {
          console.error('Git rebase failed. Aborting rebase...', rebaseError);
          await execPromise('git rebase --abort', { cwd: backendPath }).catch(() => {});
        }
      }
      
      if (attempt >= retries) {
        return {
          success: false,
          output: errorMessage,
        };
      }
      
      // Wait with exponential backoff + jitter
      const sleepTime = delay * Math.pow(2, attempt) + Math.random() * 1000;
      await new Promise(resolve => setTimeout(resolve, sleepTime));
    }
  }
}
