import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const execPromise = util.promisify(exec);

/**
 * Commits the modified files and pushes them.
 * @param {string} branchName - Name of the branch to push to.
 * @param {string} commitMessage - Commit message generated by LLM.
 * @returns {Promise<{success: boolean, output: string}>}
 */
export async function commitAndPush(branchName, commitMessage) {
  const backendPath = path.resolve(__dirname, '../../');
  console.log(`Committing changes with message: "${commitMessage}"`);
  try {
    // Escape commit message quotes
    const safeMessage = commitMessage.replace(/"/g, '\\"');
    
    // Add all changes in backend
    await execPromise('git add .', { cwd: backendPath });
    
    // Check if there are any changes to commit
    const { stdout: statusOut } = await execPromise('git status --porcelain', { cwd: backendPath });
    if (!statusOut.trim()) {
      return { success: true, output: 'No changes to commit.' };
    }
    
    // Commit
    await execPromise(`git commit -m "${safeMessage}"`, { cwd: backendPath });
    
    // Push (assuming origin is configured and auth is handled via secrets/SSH)
    const { stdout, stderr } = await execPromise(`git push origin HEAD:${branchName}`, { cwd: backendPath });
    
    return {
      success: true,
      output: `${stdout}\n${stderr}`,
    };
  } catch (error) {
    console.error('Failed to commit and push:', error);
    return {
      success: false,
      output: error.stdout || error.stderr || error.message,
    };
  }
}
