import { logger } from '../../../shared/logger.js';

/**
 * @typedef {object} A2uiComponentSchema
 * @property {string} type - The type of the component (e.g., 'object').
 * @property {object} properties - An object defining the properties of the component.
 * @property {string[]} required - An array of strings listing the required properties for the component.
 */

/**
 * @typedef {object} A2uiBasicCatalog
 * @property {A2uiComponentSchema} text - Schema for a text component.
 * @property {A2uiComponentSchema} button - Schema for a button component.
 * @property {A2uiComponentSchema} row - Schema for a row layout component.
 * @property {A2uiComponentSchema} column - Schema for a column layout component.
 * @property {A2uiComponentSchema} textField - Schema for a text input field component.
 */

/**
 * The pre-approved Google A2UI standard basic catalog schemas.
 * This constant defines the structure and required properties for a set of fundamental
 * Agent-to-User Interface (A2UI) components that can be generated by an LLM.
 * Each key represents a component type, and its value is a JSON Schema definition.
 * @type {A2uiBasicCatalog}
 */
const A2UI_BASIC_CATALOG = {
  text: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { const: 'text' },
      content: { type: 'string' },
      style: { type: 'object', properties: { size: { type: 'string' }, color: { type: 'string' } } }
    },
    required: ['id', 'type', 'content']
  },
  button: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { const: 'button' },
      label: { type: 'string' },
      action: { type: 'string' }
    },
    required: ['id', 'type', 'label']
  },
  row: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { const: 'row' },
      children: { type: 'array', items: { type: 'string' } }
    },
    required: ['id', 'type', 'children']
  },
  column: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { const: 'column' },
      children: { type: 'array', items: { type: 'string' } }
    },
    required: ['id', 'type', 'children']
  },
  textField: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { const: 'textField' },
      placeholder: { type: 'string' },
      valuePath: { type: 'string' }
    },
    required: ['id', 'type']
  }
};

/**
 * Programmatically generates standard system instructions for A2UI dynamic components.
 * This prompt guides a Large Language Model (LLM) to output declarative JSON for
 * interactive user interfaces, adhering to Google's A2UI specifications.
 *
 * @param {string[]} [allowedComponents] - An optional list of component keys (e.g., ['text', 'button'])
 *                                         to prune the schema and only include approved components in the prompt.
 *                                         If null or empty, all basic catalog components are included.
 * @param {boolean} [includeExamples=true] - Whether to inject few-shot examples into the system instructions
 *                                           to further guide the LLM's output format.
 * @returns {string} A fully compiled system prompt instruction block, ready to be sent to an LLM.
 */
const generateA2uiSystemPrompt = (allowedComponents = null, includeExamples = true) => {
  logger.info('GCP A2UI: Compiling system prompt specifications for Google Agent-to-User Interface...');

  const targetCatalog = {};
  const activeKeys = allowedComponents || Object.keys(A2UI_BASIC_CATALOG);

  for (const key of activeKeys) {
    if (A2UI_BASIC_CATALOG[key]) {
      targetCatalog[key] = A2UI_BASIC_CATALOG[key];
    }
  }

  let prompt = `
=== GOOGLE AGENT-TO-USER INTERFACE (A2UI) STANDARD ===
You are equipped with Google A2UI capabilities. When a user request is best served via an interactive user interface, you must output a declarative JSON representation describing the structural layout, and enclose it in standard A2UI XML tags:

<a2ui-json>
[
  {
    "surfaceUpdate": {
      "root": "main-layout",
      "components": [
        {
          "id": "main-layout",
          "type": "column",
          "children": ["title-text", "action-btn"]
        },
        {
          "id": "title-text",
          "type": "text",
          "content": "Grounded Information Panel"
        },
        {
          "id": "action-btn",
          "type": "button",
          "label": "Click to Explore"
        }
      ]
    }
  }
]
</a2ui-json>

=== SECURITY AND VALIDATION RULES ===
1. All component IDs in the "components" array must be unique.
2. The hierarchy must form a directed acyclic tree with no circular dependencies or self-referencing loops.
3. Nesting depth must not exceed 50 levels.
4. Only use the approved components defined in the JSON Schema catalog below.

=== APPROVED COMPONENT CATALOG ===
${JSON.stringify(targetCatalog, null, 2)}
`;

  if (includeExamples) {
    prompt += `
=== FEW-SHOT EXAMPLES ===
User: Show me a feedback card with a submit button
Assistant: Here is a feedback card:
<a2ui-json>
[
  {
    "surfaceUpdate": {
      "root": "feedback-col",
      "components": [
        {
          "id": "feedback-col",
          "type": "column",
          "children": ["lbl", "input-field", "submit-btn"]
        },
        {
          "id": "lbl",
          "type": "text",
          "content": "Share your thoughts"
        },
        {
          "id": "input-field",
          "type": "textField",
          "placeholder": "Enter your feedback..."
        },
        {
          "id": "submit-btn",
          "type": "button",
          "label": "Submit Feedback"
        }
      ]
    }
  }
]
</a2ui-json>
`;
  }

  return prompt;
};

/**
 * @typedef {object} A2uiValidationReport
 * @property {boolean} success - True if the A2UI payload was successfully parsed and passed all structural validations.
 * @property {boolean} containsUi - True if the raw text contained A2UI tags, regardless of validation success.
 * @property {string} [message] - A descriptive message, typically used when `containsUi` is false.
 * @property {string[]} [errors] - An array of error messages if validation failed (`success` is false).
 * @property {object|null} payload - The parsed JSON object representing the A2UI structure, or null if parsing failed or no UI was found.
 */

/**
 * Extracts, sanitizes, and runs comprehensive validation checks on raw LLM conversational text
 * to identify and validate Google A2UI payloads.
 *
 * This function performs the following steps:
 * 1. Extracts content enclosed within `<a2ui-json>` and `</a2ui-json>` tags.
 * 2. Sanitizes the extracted content by removing common LLM markdown wrappers (e.g., ```json).
 * 3. Parses the content as JSON.
 * 4. Applies a series of structural validation rules:
 *    - Ensures `surfaceUpdate` and `components` arrays exist.
 *    - Checks for unique component IDs.
 *    - Verifies a valid component hierarchy (no circular dependencies, no excessive nesting).
 *    - Detects and reports orphaned components (not reachable from the root).
 *
 * @param {string} rawText - Raw LLM streaming text response chunk that may contain an A2UI payload.
 * @returns {A2uiValidationReport} A validation report containing success status, structured JSON payload, and any structural warnings or errors.
 */
const parseAndValidateA2ui = (rawText) => {
  try {
    if (!rawText) {
      throw new Error('Raw conversational response stream is empty.');
    }

    logger.info('GCP A2UI: Parsing raw text block to extract Google A2UI payload...');

    // Regex-based block extraction following Google specifications
    const match = rawText.match(/<a2ui-json>([\s\S]*?)<\/a2ui-json>/i);
    if (!match) {
      return {
        success: true,
        containsUi: false,
        message: 'No Google A2UI payload detected in the response stream.',
        payload: null
      };
    }

    let rawJson = match[1].trim();

    // Sanitization: Strip accidental markdown code blocks wrapped by the LLM
    rawJson = rawJson.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();

    logger.info('GCP A2UI: Extracted raw JSON string. Running structural validation check...');

    // Parse JSON
    const parsedPayload = JSON.parse(rawJson);

    // Core structural validation rules
    const errors = [];
    const updates = Array.isArray(parsedPayload) ? parsedPayload : [parsedPayload];

    for (const update of updates) {
      const surfaceUpdate = update.surfaceUpdate;
      if (!surfaceUpdate) {
        errors.push('Payload missing "surfaceUpdate" wrapper.');
        continue;
      }

      const rootId = surfaceUpdate.root;
      const components = surfaceUpdate.components || [];

      if (!rootId) {
        errors.push('surfaceUpdate is missing a "root" component pointer.');
      }

      if (!Array.isArray(components) || components.length === 0) {
        errors.push('components must be a non-empty array.');
        continue;
      }

      // 1. Component Unique ID rule
      const idSet = new Set();
      const componentMap = new Map();

      for (const comp of components) {
        if (!comp.id) {
          errors.push('Component is missing an "id" field.');
          continue;
        }

        if (idSet.has(comp.id)) {
          errors.push(`Duplicate component ID detected: "${comp.id}".`);
        }
        idSet.add(comp.id);
        componentMap.set(comp.id, comp);
      }

      // 2. Topology, Orphan and Recursion/Circular reference checks
      const visited = new Set();
      const stack = new Set();

      const checkCycleAndNesting = (componentId, depth = 0) => {
        if (depth > 50) {
          errors.push(`Nesting recursion depth exceeded maximum limit of 50 at ID "${componentId}".`);
          return;
        }

        if (stack.has(componentId)) {
          errors.push(`Circular reference dependency detected at component ID: "${componentId}".`);
          return;
        }

        if (visited.has(componentId)) return; // Already validated

        const comp = componentMap.get(componentId);
        if (!comp) {
          errors.push(`Child component ID "${componentId}" is referenced but not defined in the catalog.`);
          return;
        }

        visited.add(componentId);
        stack.add(componentId);

        // Standard layout structural containers (Row, Column) have children ID arrays
        if (comp.children && Array.isArray(comp.children)) {
          for (const childId of comp.children) {
            checkCycleAndNesting(childId, depth + 1);
          }
        }

        stack.delete(componentId);
      };

      if (rootId && componentMap.has(rootId)) {
        checkCycleAndNesting(rootId);
      } else if (rootId) {
        errors.push(`Declared root component ID "${rootId}" is missing from the components array.`);
      }

      // Detect orphaned components (components not reachable from root)
      for (const compId of idSet) {
        if (!visited.has(compId)) {
          errors.push(`Orphaned component detected: "${compId}" is not reachable from the root component.`);
        }
      }
    }

    if (errors.length > 0) {
      logger.warn(`GCP A2UI: Structural validation failed with ${errors.length} violations.`);
      return {
        success: false,
        containsUi: true,
        errors: errors,
        payload: parsedPayload
      };
    }

    logger.info('GCP A2UI: Structural validation check completed successfully. Payload is clean.');

    return {
      success: true,
      containsUi: true,
      errors: [],
      payload: parsedPayload
    };
  } catch (err) {
    logger.error('GCP A2UI Parsing Exception:', err);
    return {
      success: false,
      containsUi: true,
      errors: [err.message],
      payload: null
    };
  }
};

/**
 * Returns the Google A2UI basic schema catalog object.
 * This provides a reference to the predefined component schemas.
 *
 * @returns {A2uiBasicCatalog} The immutable A2UI basic component catalog.
 */
const getA2uiBasicCatalog = () => {
  return A2UI_BASIC_CATALOG;
};

/**
 * Heuristically corrects typical LLM JSON structural syntax errors.
 * This function attempts to repair common malformations in JSON strings generated by LLMs,
 * such as unescaped newlines, single quotes, unquoted keys, and trailing commas,
 * to make them valid JSON. It also tries to close unclosed brackets/braces.
 *
 * @param {string} rawJson - Raw, potentially malformed JSON string payload from an LLM.
 * @returns {string} A repaired and sanitized JSON string. Returns an empty string if input is null or empty.
 */
const fixA2uiPayload = (rawJson) => {
  if (!rawJson) return '';
  logger.info('GCP A2UI PayloadFixer: Attempting programmatic syntax correction on JSON string...');

  let fixed = rawJson.trim();

  // 1. Repair unescaped newlines inside string literals
  fixed = fixed.replace(/"([^"]*)"/g, (match, group) => {
    return '"' + group.replace(/\n/g, '\\n').replace(/\r/g, '\\r') + '"';
  });

  // 2. Repair single quotes to double quotes for properties and values
  fixed = fixed.replace(/'([^']*)'\s*:/g, '"$1":');
  fixed = fixed.replace(/:\s*'([^']*)'/g, ': "$1"');

  // 3. Repair unquoted property keys
  fixed = fixed.replace(/([{,]\s*)([a-zA-Z0-9_\-]+)\s*:/g, '$1"$2":');

  // 4. Remove trailing commas in objects and arrays
  fixed = fixed.replace(/,\s*([}\]])/g, '$1');

  // 5. Match and close any unclosed trailing brackets/braces using stack matching
  const stack = [];
  let inString = false;
  let escape = false;

  for (let i = 0; i < fixed.length; i++) {
    const char = fixed[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (char === '\\') {
      escape = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (!inString) {
      if (char === '{' || char === '[') {
        stack.push(char === '{' ? '}' : ']');
      } else if (char === '}' || char === ']') {
        if (stack.length > 0 && stack[stack.length - 1] === char) {
          stack.pop();
        }
      }
    }
  }

  while (stack.length > 0) {
    const closeChar = stack.pop();
    fixed += closeChar;
  }

  return fixed;
};

/**
 * @typedef {object} A2uiStreamPartText
 * @property {'text'} type - Indicates this part is plain text.
 * @property {string} content - The extracted plain text content.
 */

/**
 * @typedef {object} A2uiStreamPartPartial
 * @property {'a2ui_partial'} type - Indicates an A2UI payload is currently being buffered but is incomplete.
 * @property {number} bufferedLength - The current length of the buffered A2UI content.
 */

/**
 * @typedef {object} A2uiStreamPartComplete
 * @property {'a2ui_complete'} type - Indicates a complete A2UI payload has been extracted.
 * @property {boolean} success - True if the A2UI JSON was successfully parsed.
 * @property {object} [payload] - The parsed A2UI JSON object if `success` is true.
 * @property {string} [error] - An error message if JSON parsing failed.
 * @property {string} [rawPayload] - The raw A2UI JSON string before parsing, if an error occurred.
 */

/**
 * @typedef {A2uiStreamPartText | A2uiStreamPartPartial | A2uiStreamPartComplete} A2uiStreamPart
 */

/**
 * Stateful stream parser that progressively processes incoming text chunks
 * to extract Google A2UI dynamic components enclosed in `<a2ui-json>` tags.
 * It handles partial tags across chunks and attempts to fix malformed JSON.
 */
class A2uiStreamParser {
  /**
   * Creates an instance of A2uiStreamParser.
   * @param {object} [catalog=null] - An optional catalog object. Currently not used by the parser logic.
   */
  constructor(catalog = null) {
    /**
     * The internal buffer to accumulate text chunks.
     * @type {string}
     */
    this.buffer = '';
    /**
     * A flag indicating whether the parser is currently inside an `<a2ui-json>` block.
     * @type {boolean}
     */
    this.insideTag = false;
    /**
     * The catalog object passed during construction. Currently not used by the parser logic.
     * @type {object|null}
     */
    this.catalog = catalog;
  }

  /**
   * Processes a single chunk of text from a stream.
   * It identifies and extracts A2UI JSON payloads, handling cases where tags
   * or JSON content span across multiple chunks. It also attempts to repair
   * malformed JSON before parsing.
   *
   * @param {string} chunk - The incoming text chunk to process.
   * @returns {A2uiStreamPart[]} An array of processed parts, which can be plain text,
   *                               a partial A2UI payload, or a complete A2UI payload.
   */
  processChunk(chunk) {
    if (!chunk) return [];

    this.buffer += chunk;
    const parts = [];

    while (this.buffer.length > 0) {
      if (!this.insideTag) {
        const tagIndex = this.buffer.toLowerCase().indexOf('<a2ui-json>');

        if (tagIndex === -1) {
          // No opening tag found, treat entire buffer as text
          parts.push({
            type: 'text',
            content: this.buffer
          });
          this.buffer = ''; // Clear buffer as it's all text
          break;
        } else {
          // Opening tag found
          if (tagIndex > 0) {
            // Push text before the tag
            parts.push({
              type: 'text',
              content: this.buffer.substring(0, tagIndex)
            });
          }
          this.insideTag = true;
          this.buffer = this.buffer.substring(tagIndex + '<a2ui-json>'.length);
        }
      } else {
        const closeIndex = this.buffer.toLowerCase().indexOf('</a2ui-json>');

        if (closeIndex === -1) {
          // Inside tag, but no closing tag yet, buffer more
          parts.push({
            type: 'a2ui_partial',
            bufferedLength: this.buffer.length
          });
          break; // Wait for more chunks
        } else {
          // Closing tag found, extract A2UI JSON
          let rawJson = this.buffer.substring(0, closeIndex).trim();
          this.buffer = this.buffer.substring(closeIndex + '</a2ui-json>'.length);
          this.insideTag = false;

          // Sanitization: Strip accidental markdown code blocks wrapped by the LLM
          rawJson = rawJson.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
          const repairedJson = fixA2uiPayload(rawJson);

          try {
            const parsedPayload = JSON.parse(repairedJson);
            parts.push({
              type: 'a2ui_complete',
              success: true,
              payload: parsedPayload
            });
          } catch (err) {
            parts.push({
              type: 'a2ui_complete',
              success: false,
              error: err.message,
              rawPayload: rawJson // Keep raw payload for debugging if parsing fails
            });
          }
        }
      }
    }

    return parts;
  }
}

/**
 * @typedef {object} A2uiStreamState
 * @property {string} buffer - The current accumulated buffer from previous chunks.
 * @property {boolean} insideTag - Flag indicating if the parser is currently inside an A2UI tag.
 */

/**
 * @typedef {object} ParseA2uiStreamChunkResult
 * @property {A2uiStreamPart[]} parts - An array of processed parts from the current chunk.
 * @property {A2uiStreamState} newState - The updated state of the parser to be passed to the next call.
 */

/**
 * Stateless wrapper function for `A2uiStreamParser` that processes a single stream chunk,
 * returning response parts and an updated state map. This allows for external state management.
 *
 * @param {string} chunk - The incoming text chunk to process.
 * @param {A2uiStreamState} [state={ buffer: '', insideTag: false }] - The current state of the stream parser.
 * @returns {ParseA2uiStreamChunkResult} An object containing the processed parts and the new state.
 */
const parseA2uiStreamChunk = (chunk, state = { buffer: '', insideTag: false }) => {
  const parser = new A2uiStreamParser();
  parser.buffer = state.buffer || '';
  parser.insideTag = state.insideTag || false;

  const parts = parser.processChunk(chunk);

  return {
    parts,
    newState: {
      buffer: parser.buffer,
      insideTag: parser.insideTag
    }
  };
};

/**
 * @typedef {object} A2uiRpcPayload
 * @property {string} componentId - The ID of the component that triggered the RPC action.
 * @property {string} action - The action performed on the component (e.g., 'click', 'submit').
 * @property {object} [values] - An object containing any associated values from the UI component (e.g., form input values).
 */

/**
 * @typedef {object} A2uiRpcResponseUpdate
 * @property {boolean} success - Indicates if the RPC action was processed successfully.
 * @property {string} actionProcessed - The action that was processed.
 * @property {string} timestamp - ISO 8601 timestamp of when the action was processed.
 * @property {object} surfaceUpdate - An object describing the updated A2UI surface.
 * @property {string} surfaceUpdate.root - The ID of the root component for the updated UI.
 * @property {Array<object>} surfaceUpdate.components - An array of component definitions for the updated UI.
 */

/**
 * Stateful dispatcher that processes incoming user interface actions (RPCs) from an A2UI client.
 * This function simulates running bound tools or logic based on the `rpcPayload` and
 * returns an updated dynamic layout to the client.
 *
 * @param {object} sessionState - The current session state, which might include existing components and their values.
 *                                This parameter is currently not used in the example implementation but is provided for future extensibility.
 * @param {A2uiRpcPayload} rpcPayload - The RPC trigger packet containing details about the user's interaction.
 * @returns {Promise<A2uiRpcResponseUpdate>} A promise that resolves to an interactive response update,
 *                                           describing how the UI should change.
 */
const handleA2uiRpc = async (sessionState, rpcPayload) => {
  logger.info(`GCP A2UI RPC: Executing action "${rpcPayload.action}" on component "${rpcPayload.componentId}"...`);

  const componentId = rpcPayload.componentId || 'unknown';
  const action = rpcPayload.action || 'click';
  const values = rpcPayload.values || {};

  // Construct a standard response update with a refreshed dynamic surface
  const responseUpdate = {
    success: true,
    actionProcessed: action,
    timestamp: new Date().toISOString(),
    surfaceUpdate: {
      root: 'rpc-status-layout',
      components: [
        {
          id: 'rpc-status-layout',
          type: 'column',
          children: ['status-lbl', 'refresh-btn']
        },
        {
          id: 'status-lbl',
          type: 'text',
          content: `Action "${action}" on component "${componentId}" processed successfully! Recipient received values: ${JSON.stringify(values)}`
        },
        {
          id: 'refresh-btn',
          type: 'button',
          label: 'Continue Interactive Exploration',
          action: 'reset_explore'
        }
      ]
    }
  };

  return responseUpdate;
};

/**
 * @typedef {object} ActivateExtensionResult
 * @property {boolean} success - True if the extension was successfully activated.
 * @property {string} activatedId - The ID of the component that was activated.
 * @property {string[]} catalogKeys - An array of all component keys currently in the active catalog, including the newly added one.
 */

/**
 * Dynamically registers and validates a new custom dynamic UI component in the active catalog.
 * This allows for extending the set of components an LLM can generate.
 *
 * @param {string} extensionId - The unique namespace identifier for the extension component (e.g., 'myCustomCard').
 * @param {A2uiComponentSchema} componentSchema - The JSON Schema defining the new component's structure, properties, and required fields.
 * @returns {ActivateExtensionResult} An object indicating the activation result status, including the activated ID and updated catalog keys.
 * @throws {Error} If `extensionId` or `componentSchema` are not provided.
 */
const tryActivateExtension = (extensionId, componentSchema) => {
  logger.info(`GCP A2UI: Attempting to dynamically activate extension component "${extensionId}"...`);

  if (!extensionId || !componentSchema) {
    throw new Error('Extension ID and Component Schema are required.');
  }

  // Merge the new schema into our active basic catalog configuration
  A2UI_BASIC_CATALOG[extensionId] = componentSchema;

  return {
    success: true,
    activatedId: extensionId,
    catalogKeys: Object.keys(A2UI_BASIC_CATALOG)
  };
};

/**
 * Provides a collection of services for interacting with Google's Agent-to-User Interface (A2UI) standard.
 * This includes generating system prompts for LLMs, parsing and validating A2UI payloads,
 * handling interactive RPC calls, and dynamically extending the A2UI component catalog.
 * @namespace GcpA2uiService
 */
export const GcpA2uiService = {
  generateA2uiSystemPrompt,
  parseAndValidateA2ui,
  getA2uiBasicCatalog,
  fixA2uiPayload,
  parseA2uiStreamChunk,
  A2uiStreamParser,
  handleA2uiRpc,
  tryActivateExtension
};