import { logger } from '../../../shared/logger.js';

/**
 * Programmatically generates standard system instructions for A2A peer communication.
 * This prompt defines the expected XML-wrapped JSON structure for Agent-to-Agent (A2A)
 * communication packets within a Google-native swarm environment. It includes mandatory
 * headers, payload structure, and security token format.
 *
 * @returns {string} A multi-line string containing the A2A system prompt specifications.
 */
const generateA2aSystemPrompt = () => {
  logger.info('GCP A2A: Compiling system prompt specifications for Google Agent-to-Agent swarm workflows...');

  // Dynamically get the current year for the example security token to ensure consistency
  // with how tokens are generated by formatSwarmHandoff and validated by parseAndValidateA2a.
  const currentYear = new Date().getFullYear();

  const prompt = `
=== GOOGLE AGENT-TO-AGENT (A2A) SWARM COMMUNICATIONS STANDARD ===
You are equipped with Google A2A peer communication protocols. When a complex task requires collaborating with or delegating to another specialized agent, you must output a structured A2A message packet wrapped in XML <a2a-packet> tags:

<a2a-packet>
{
  "sender": "PlannerAgent",
  "recipient": "CoderAgent",
  "seqId": "seq_a2a_109283",
  "securityToken": "sec_token_gcp_native_swarm_valid_${currentYear}",
  "payload": {
    "action": "execute_code_generation",
    "parameters": {
      "language": "javascript",
      "objective": "Implement robust express routing for gcp-agui.service.js"
    }
  }
}
</a2a-packet>

=== COLLABORATION AND SECURITY RULES ===
1. Every packet must contain the mandatory headers: "sender", "recipient", "seqId", "securityToken", and "payload".
2. The payload must define the specific "action" and the "parameters" object.
3. The security token must match the registered workflow token context.
`;

  return prompt;
};

/**
 * Extracts, sanitizes, and validates an A2A packet from raw response text.
 * It looks for an XML block `<a2a-packet>...</a2a-packet>`, parses the enclosed JSON,
 * and performs schema and security token validation.
 *
 * @param {string} rawText - The raw text response potentially containing an A2A packet.
 * @returns {object} An object indicating the parsing and validation outcome.
 * @property {boolean} success - True if the packet was successfully parsed and validated, false otherwise.
 * @property {boolean} containsPacket - True if an `<a2a-packet>` block was found, false otherwise.
 * @property {string} [message] - A descriptive message if no packet was found.
 * @property {string[]} [errors] - An array of error messages if validation failed.
 * @property {object|null} packet - The parsed A2A packet object if found and partially parsed, null otherwise.
 * @property {string} packet.sender - The name of the sending agent.
 * @property {string} packet.recipient - The name of the recipient agent.
 * @property {string} packet.seqId - A unique sequence identifier for the packet.
 * @property {string} packet.securityToken - A security token for authentication and integrity.
 * @property {object} packet.payload - The main content of the message.
 * @property {string} packet.payload.action - The specific action the recipient should perform.
 * @property {object} packet.payload.parameters - Parameters relevant to the action.
 */
const parseAndValidateA2a = (rawText) => {
  try {
    if (!rawText) {
      throw new Error('Raw A2A conversation block is empty.');
    }

    logger.info('GCP A2A: Locating and parsing <a2a-packet> XML block...');

    const match = rawText.match(/<a2a-packet>([\s\S]*?)<\/a2a-packet>/i);
    if (!match) {
      return {
        success: true,
        containsPacket: false,
        message: 'No Agent-to-Agent (A2A) packet detected in response stream.',
        packet: null
      };
    }

    let rawJson = match[1].trim();
    rawJson = rawJson.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();

    logger.info('GCP A2A: Running strict packet schema validation checks...');

    const packet = JSON.parse(rawJson);
    const errors = [];

    // Enforce A2A header checklist
    if (!packet.sender) errors.push('A2A Packet missing mandatory header: "sender"');
    if (!packet.recipient) errors.push('A2A Packet missing mandatory header: "recipient"');
    if (!packet.seqId) errors.push('A2A Packet missing mandatory header: "seqId"');
    if (!packet.securityToken) errors.push('A2A Packet missing mandatory header: "securityToken"');
    if (!packet.payload) {
      errors.push('A2A Packet missing mandatory header: "payload"');
    } else {
      if (!packet.payload.action) errors.push('A2A payload missing "action" definition.');
      if (!packet.payload.parameters || typeof packet.payload.parameters !== 'object') {
        errors.push('A2A payload "parameters" must be a valid structured object.');
      }
    }

    // Verify security token format and year.
    // The expected format is "sec_token_gcp_native_swarm_valid_YYYY".
    // This ensures tokens are current and prevents replay attacks with outdated tokens.
    const currentYear = new Date().getFullYear();
    const expectedTokenPrefix = 'sec_token_gcp_native_swarm_valid_';

    if (packet.securityToken) {
      if (!packet.securityToken.startsWith(expectedTokenPrefix)) {
        errors.push('Security token integrity check failed: invalid signature layout.');
      } else {
        const tokenYearStr = packet.securityToken.substring(expectedTokenPrefix.length);
        const tokenYear = parseInt(tokenYearStr, 10);

        // Check if the year part is a valid 4-digit number and matches the current year.
        // A more robust system might allow a small window (e.g., current year or next year),
        // but for simplicity and strict security, we enforce the current year.
        if (isNaN(tokenYear) || tokenYear.toString().length !== 4 || tokenYear !== currentYear) {
          errors.push(`Security token integrity check failed: invalid or outdated year in token. Expected year: ${currentYear}.`);
        }
      }
    }

    if (errors.length > 0) {
      logger.warn(`GCP A2A: Packet verification failed with ${errors.length} validation errors.`);
      return {
        success: false,
        containsPacket: true,
        errors,
        packet
      };
    }

    logger.info('GCP A2A: Packet header verification completed successfully. Packet is secure.');
    return {
      success: true,
      containsPacket: true,
      errors: [],
      packet
    };
  } catch (err) {
    logger.error('GCP A2A Parsing Exception:', err);
    return {
      success: false,
      containsPacket: true,
      errors: [err.message],
      packet: null
    };
  }
};

/**
 * Programmatically formats a secure multi-agent swarm handoff transition packet.
 * This function constructs an A2A packet in the required JSON structure,
 * wraps it in XML `<a2a-packet>` tags, and includes a dynamically generated
 * security token with the current year.
 *
 * @param {string} fromAgent - The name of the initiating subagent.
 * @param {string} toAgent - The name of the target recipient subagent.
 * @param {string} action - The specific objective action the recipient should perform.
 * @param {object} [params={}] - An object containing input task parameters relevant to the action. Defaults to an empty object.
 * @returns {string} The formatted A2A packet as an XML string, ready for transmission.
 */
const formatSwarmHandoff = (fromAgent, toAgent, action, params = {}) => {
  logger.info(`GCP A2A: Packaging swarm handoff from "${fromAgent}" to "${toAgent}"...`);
  
  const packet = {
    sender: fromAgent,
    recipient: toAgent,
    seqId: `seq_a2a_${Math.floor(Math.random() * 1000000)}`,
    securityToken: `sec_token_gcp_native_swarm_valid_${new Date().getFullYear()}`,
    payload: {
      action,
      parameters: params
    }
  };

  return `<a2a-packet>\n${JSON.stringify(packet, null, 2)}\n</a2a-packet>`;
};

/**
 * @typedef {object} GcpA2aService
 * @property {function(): string} generateA2aSystemPrompt - Generates the standard A2A system prompt.
 * @property {function(string): object} parseAndValidateA2a - Extracts, sanitizes, and validates an A2A packet from raw text.
 * @property {function(string, string, string, object): string} formatSwarmHandoff - Formats a secure multi-agent swarm handoff transition packet.
 */

/**
 * Provides a set of utilities for managing Google Agent-to-Agent (A2A) swarm communications.
 * This service includes functions for generating system prompts, parsing and validating
 * incoming A2A packets, and formatting outgoing A2A handoff messages.
 *
 * @type {GcpA2aService}
 */
export const GcpA2aService = {
  generateA2aSystemPrompt,
  parseAndValidateA2a,
  formatSwarmHandoff
};