/**
 * Defines the state schema for the conversational image generation graph.
 * This object is passed between nodes in the graph, holding the conversation's
 * memory and the evolving state of the image generation process.
 * Each property defines a piece of state, how it's updated, and its default value.
 * This structure is compatible with state management libraries like LangGraph.
 */
export const graphState = {
  /**
   * The user's initial idea or prompt for the image.
   * This value is set once and remains constant throughout the conversation for reference.
   * @type {{value: string | null}}
   */
  initialPrompt: { value: null },

  /**
   * The evolving, detailed prompt that gets updated with user feedback and clarifications.
   * This acts as the "memory" of the image concept.
   * The reducer function `(current, update) => update` ensures that this state is always replaced with the newest version.
   * @type {{value: function(string, string): string, default: function(): string}}
   */
  refinedPrompt: {
    value: (x, y) => y,
    default: () => '',
  },

  /**
   * A list of clarifying questions generated by the AI to ask the user for more details.
   * @type {{value: string[] | null}}
   */
  questions: { value: null },

  /**
   * A structured log of the entire conversation for maintaining full context.
   * The reducer function `(current, update) => current.concat(update)` appends new messages to the existing history.
   * The messages are typically instances of `import('@langchain/core/messages').BaseMessage`.
   * @type {{value: function(Array, Array): Array, default: function(): Array}}
   */
  conversationHistory: {
    value: (x, y) => x.concat(y),
    default: () => [],
  },

  /**
   * The user's most recent message or response in the conversation.
   * @type {{value: string | null}}
   */
  userResponse: { value: null },

  /**
   * The final, compiled prompt that is ready to be sent to the image generation model.
   * @type {{value: string | null}}
   */
  finalPrompt: { value: null },

  /**
   * The URL or base64 encoded data of the generated image.
   * @type {{value: string | null}}
   */
  imageUrl: { value: null },

  /**
   * The message to be sent back to the user in the current turn of the conversation.
   * @type {{value: string | null}}
   */
  responseMessage: { value: null },
};