/**
 * @typedef {object} VideoGeneratorState
 * @property {{ value: string | null }} initialPrompt - The user's initial idea for the video. This value remains constant throughout the conversation for reference.
 * @property {{ value: function(string, string): string, default: function(): string }} refinedPrompt - The evolving, detailed prompt that gets updated with user feedback. This serves as the conversation's "memory" for the video generation request. The `value` function takes the previous refined prompt and the new update, returning the new refined prompt. The `default` function provides the initial empty prompt.
 * @property {{ value: string[] | null }} questions - A list of clarifying questions generated by the assistant to ask the user.
 * @property {{ value: function(Array<object>, object): Array<object>, default: function(): Array<object> }} conversationHistory - A structured log of the conversation, providing full context. Each item in the array represents a message turn. The `value` function takes the previous conversation history and a new message object, returning the updated history. The `default` function provides an initial empty array for the history.
 * @property {{ value: string | null }} userResponse - The user's most recent message or input.
 * @property {{ value: string | null }} finalPrompt - The final compiled and approved prompt ready to be sent to the video generation service.
 * @property {{ value: string | null }} videoUrl - The URL or path where the generated video can be accessed.
 * @property {{ value: string | null }} responseMessage - The message to send back to the user in the current turn of the conversation.
 * @property {{ value: string | null }} videoDuration - The desired duration of the video (e.g., "short", "medium", "long", or specific timeframes like "1-2 minutes").
 * @property {{ value: string | null }} videoStyle - The desired visual style or genre of the video (e.g., "cinematic", "animated", "documentary").
 * @property {{ value: string | null }} videoResolution - The desired resolution of the video (e.g., "720p", "1080p", "4K").
 * @property {{ value: string | null }} generationStatus - The current status of the video generation process (e.g., "pending", "in_progress", "completed", "failed").
 * @property {{ value: number | null }} generationProgress - The percentage progress of the video generation process, from 0 to 100.
 */

/**
 * Defines the state for our video generation conversational graph.
 * This object is passed between nodes and holds the conversation's memory.
 *
 * @type {VideoGeneratorState}
 */
export const videoGeneratorState = {
  /**
   * The user's initial idea for the video. This value remains constant throughout the conversation for reference.
   * @type {{ value: string | null }}
   */
  initialPrompt: { value: null },

  /**
   * The evolving, detailed prompt that gets updated with user feedback. This serves as the conversation's "memory" for the video generation request.
   * The `value` function takes the previous refined prompt and the new update, returning the new refined prompt.
   * The `default` function provides the initial empty prompt.
   * @type {{ value: function(string, string): string, default: function(): string }}
   */
  refinedPrompt: {
    value: (x, y) => y, // Always take the new, updated version
    default: () => '',
  },

  /**
   * A list of clarifying questions generated by the assistant to ask the user.
   * @type {{ value: string[] | null }}
   */
  questions: { value: null },

  /**
   * A structured log of the conversation, providing full context. Each item in the array represents a message turn.
   * The `value` function takes the previous conversation history and a new message object, returning the updated history.
   * The `default` function provides an initial empty array for the history.
   * @type {{ value: function(Array<object>, object): Array<object>, default: function(): Array<object> }}
   */
  conversationHistory: {
    value: (x, y) => x.concat(y),
    default: () => [],
  },

  /**
   * The user's most recent message or input.
   * @type {{ value: string | null }}
   */
  userResponse: { value: null },

  /**
   * The final compiled and approved prompt ready to be sent to the video generation service.
   * @type {{ value: string | null }}
   */
  finalPrompt: { value: null },

  /**
   * The URL or path where the generated video can be accessed.
   * @type {{ value: string | null }}
   */
  videoUrl: { value: null },

  /**
   * The message to send back to the user in the current turn of the conversation.
   * @type {{ value: string | null }}
   */
  responseMessage: { value: null },

  // Video-specific parameters
  /**
   * The desired duration of the video (e.g., "short", "medium", "long", or specific timeframes like "1-2 minutes").
   * @type {{ value: string | null }}
   */
  videoDuration: { value: null },
  /**
   * The desired visual style or genre of the video (e.g., "cinematic", "animated", "documentary").
   * @type {{ value: string | null }}
   */
  videoStyle: { value: null },
  /**
   * The desired resolution of the video (e.g., "720p", "1080p", "4K").
   * @type {{ value: string | null }}
   */
  videoResolution: { value: null },

  // Additional video generation metadata
  /**
   * The current status of the video generation process (e.g., "pending", "in_progress", "completed", "failed").
   * @type {{ value: string | null }}
   */
  generationStatus: { value: null },
  /**
   * The percentage progress of the video generation process, from 0 to 100.
   * @type {{ value: number | null }}
   */
  generationProgress: { value: null },
};