import mongoose from 'mongoose';

/**
 * @typedef {object} WorkflowPattern
 * @property {mongoose.Schema.Types.ObjectId} userId - The ID of the user to whom this workflow pattern belongs.
 * @property {string[]} sequence - An ordered list of tool slugs that form the detected pattern (e.g., ['GMAIL_SEND_EMAIL', 'GOOGLECALENDAR_CREATE_EVENT']).
 * @property {number} occurrenceCount - The number of times this exact sequence of tool calls was observed. Defaults to 1.
 * @property {number} successRate - The aggregate success rate (0-100) across all observed runs of this pattern. Defaults to 100.
 * @property {number} avgSequenceLatencyMs - The average total latency of the entire sequence in milliseconds. Defaults to 0.
 * @property {number} estimatedTimeSavingsMs - The estimated time savings in milliseconds per run if this sequence were automated. Defaults to 0.
 * @property {string} geminiSuggestion - A natural language suggestion generated by the Gemini AI for this pattern. Defaults to an empty string.
 * @property {string} patternTitle - A short, descriptive title for the pattern, also Gemini-generated. Defaults to an empty string.
 * @property {boolean} dismissed - Indicates whether the user has acknowledged or dismissed this pattern suggestion. Defaults to false.
 * @property {Date} lastObservedAt - The timestamp of the last time this pattern was observed. Defaults to the current date/time.
 * @property {Date} createdAt - The timestamp when the workflow pattern was first created.
 * @property {Date} updatedAt - The timestamp when the workflow pattern was last updated.
 */

/**
 * WorkflowPattern Model
 *
 * Stores recurring tool-call sequences detected from ActionAuditLog history.
 * Powered by the Composio Workflow Pattern Intelligence Agent.
 *
 * @type {mongoose.Schema<WorkflowPattern>}
 */
const WorkflowPatternSchema = new mongoose.Schema(
  {
    /**
     * The ID of the user to whom this workflow pattern belongs.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref User
     * @required true
     * @index true
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    /**
     * An ordered list of tool slugs that form the detected pattern.
     * For example: ['GMAIL_SEND_EMAIL', 'GOOGLECALENDAR_CREATE_EVENT'].
     * @type {string[]}
     * @required true
     */
    sequence: {
      type: [String],
      required: true,
    },
    /**
     * The number of times this exact sequence of tool calls was observed.
     * @type {number}
     * @default 1
     */
    occurrenceCount: {
      type: Number,
      default: 1,
    },
    /**
     * The aggregate success rate (0-100) across all observed runs of this pattern.
     * @type {number}
     * @min 0
     * @max 100
     * @default 100
     */
    successRate: {
      type: Number,
      min: 0,
      max: 100,
      default: 100,
    },
    /**
     * The average total latency of the entire sequence in milliseconds.
     * @type {number}
     * @default 0
     */
    avgSequenceLatencyMs: {
      type: Number,
      default: 0,
    },
    /**
     * The estimated time savings in milliseconds per run if this sequence were automated.
     * @type {number}
     * @default 0
     */
    estimatedTimeSavingsMs: {
      type: Number,
      default: 0,
    },
    /**
     * A natural language suggestion generated by the Gemini AI for this pattern.
     * @type {string}
     * @default ''
     */
    geminiSuggestion: {
      type: String,
      default: '',
    },
    /**
     * A short, descriptive title for the pattern, also Gemini-generated.
     * @type {string}
     * @default ''
     */
    patternTitle: {
      type: String,
      default: '',
    },
    /**
     * Indicates whether the user has acknowledged or dismissed this pattern suggestion.
     * @type {boolean}
     * @default false
     */
    dismissed: {
      type: Boolean,
      default: false,
    },
    /**
     * The timestamp of the last time this pattern was observed.
     * Used for TTL indexing to expire old patterns.
     * @type {Date}
     * @default Date.now
     */
    lastObservedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    /**
     * Mongoose schema options.
     * @property {boolean} timestamps - Automatically adds `createdAt` and `updatedAt` fields.
     */
    timestamps: true,
  }
);

/**
 * Compound index to ensure uniqueness for a given user and sequence.
 * This prevents duplicate workflow patterns for the same user and tool sequence.
 * @index {userId: 1, sequence: 1}
 */
WorkflowPatternSchema.index({ userId: 1, sequence: 1 });

/**
 * TTL (Time-To-Live) index to automatically expire patterns that have not been re-observed
 * within a specified period (60 days in this case).
 * @index {lastObservedAt: 1}
 * @expireAfterSeconds 60 * 24 * 60 * 60 (60 days)
 */
WorkflowPatternSchema.index({ lastObservedAt: 1 }, { expireAfterSeconds: 60 * 24 * 60 * 60 });

/**
 * Represents the WorkflowPattern model in the database.
 * If the model already exists, it uses the existing one; otherwise, it creates a new one.
 * @type {mongoose.Model<WorkflowPattern>}
 */
const WorkflowPattern =
  mongoose.models.WorkflowPattern ||
  mongoose.model('WorkflowPattern', WorkflowPatternSchema);

export default WorkflowPattern;