import mongoose from 'mongoose';
import crypto from 'crypto';

/**
 * @typedef {object} WorkflowPattern
 * @property {mongoose.Schema.Types.ObjectId} workspaceId - The ID of the workspace to which this user and pattern belong.
 * @property {mongoose.Schema.Types.ObjectId} userId - The ID of the user to whom this workflow pattern belongs.
 * @property {string[]} sequence - An ordered list of tool slugs that form the detected pattern (e.g., ['GMAIL_SEND_EMAIL', 'GOOGLECALENDAR_CREATE_EVENT']).
 * @property {string} sequenceHash - A SHA-256 hash of the sequence array, used for efficient indexing and uniqueness constraints.
 * @property {number} occurrenceCount - The number of times this exact sequence of tool calls was observed. Defaults to 1.
 * @property {number} successRate - The aggregate success rate (0-100) across all observed runs of this pattern. Defaults to 100.
 * @property {number} avgSequenceLatencyMs - The average total latency of the entire sequence in milliseconds. Defaults to 0.
 * @property {number} estimatedTimeSavingsMs - The estimated time savings in milliseconds per run if this sequence were automated. Defaults to 0.
 * @property {string} geminiSuggestion - A natural language suggestion generated by the Gemini AI for this pattern. Defaults to an empty string.
 * @property {string} patternTitle - A short, descriptive title for the pattern, also Gemini-generated. Defaults to an empty string.
 * @property {string} status - The current status of the pattern suggestion ('SUGGESTED' or 'AUTOMATED').
 * @property {mongoose.Schema.Types.ObjectId} [workflowId] - If automated, the ID of the corresponding workflow.
 * @property {boolean} dismissed - Indicates whether the user has acknowledged or dismissed this pattern suggestion. Defaults to false.
 * @property {Date} lastObservedAt - The timestamp of the last time this pattern was observed. Defaults to the current date/time.
 * @property {Date} createdAt - The timestamp when the workflow pattern was first created.
 * @property {Date} updatedAt - The timestamp when the workflow pattern was last updated.
 */

/**
 * WorkflowPattern Model
 *
 * Stores recurring tool-call sequences detected from ActionAuditLog history.
 * This data powers the Manager Dashboard for workspace metrics and automation suggestions.
 * Powered by the Composio Workflow Pattern Intelligence Agent.
 *
 * @type {mongoose.Schema<WorkflowPattern>}
 */
const WorkflowPatternSchema = new mongoose.Schema(
  {
    /**
     * The ID of the workspace to which this user and pattern belong.
     * Facilitates efficient querying of metrics at the workspace level for the Manager Dashboard.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref Workspace
     * @required true
     * @index true
     */
    workspaceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Workspace', // Assumes a 'Workspace' model exists
      required: true,
      index: true,
    },
    /**
     * The ID of the user to whom this workflow pattern belongs.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref User
     * @required true
     * @index true
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    /**
     * An ordered list of tool slugs that form the detected pattern.
     * For example: ['GMAIL_SEND_EMAIL', 'GOOGLECALENDAR_CREATE_EVENT'].
     * @type {string[]}
     * @required true
     */
    sequence: {
      type: [String],
      required: true,
    },
    /**
     * A SHA-256 hash of the sequence array, used for efficient indexing and uniqueness constraints.
     * This is automatically generated before saving.
     * @type {string}
     * @private
     */
    sequenceHash: {
      type: String,
      required: true, // Required for the unique index to work reliably.
    },
    /**
     * The number of times this exact sequence of tool calls was observed.
     * @type {number}
     * @default 1
     * @min 1
     */
    occurrenceCount: {
      type: Number,
      default: 1,
      min: 1,
    },
    /**
     * The aggregate success rate (0-100) across all observed runs of this pattern.
     * @type {number}
     * @min 0
     * @max 100
     * @default 100
     */
    successRate: {
      type: Number,
      min: 0,
      max: 100,
      default: 100,
    },
    /**
     * The average total latency of the entire sequence in milliseconds.
     * @type {number}
     * @default 0
     * @min 0
     */
    avgSequenceLatencyMs: {
      type: Number,
      default: 0,
      min: 0,
    },
    /**
     * The estimated time savings in milliseconds per run if this sequence were automated.
     * @type {number}
     * @default 0
     * @min 0
     */
    estimatedTimeSavingsMs: {
      type: Number,
      default: 0,
      min: 0,
    },
    /**
     * A natural language suggestion generated by the Gemini AI for this pattern.
     * @type {string}
     * @default ''
     * @trim true
     */
    geminiSuggestion: {
      type: String,
      default: '',
      trim: true,
    },
    /**
     * A short, descriptive title for the pattern, also Gemini-generated.
     * @type {string}
     * @default ''
     * @trim true
     */
    patternTitle: {
      type: String,
      default: '',
      trim: true,
    },
    /**
     * The current status of the pattern suggestion. This provides managers with richer insights
     * into which automation opportunities have been acted upon.
     * 'SUGGESTED': An opportunity for automation has been identified.
     * 'AUTOMATED': A workflow has been created based on this pattern.
     * @type {string}
     * @enum ['SUGGESTED', 'AUTOMATED']
     * @default 'SUGGESTED'
     * @index true
     */
    status: {
      type: String,
      enum: ['SUGGESTED', 'AUTOMATED'],
      default: 'SUGGESTED',
      index: true,
    },
    /**
     * If the pattern has been automated (status is 'AUTOMATED'), this links to the
     * corresponding Workflow document, closing the loop from suggestion to implementation.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref Workflow
     */
    workflowId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Workflow', // Assumes a 'Workflow' model exists
      default: null,
    },
    /**
     * Indicates whether the user has acknowledged or dismissed this pattern suggestion.
     * @type {boolean}
     * @default false
     */
    dismissed: {
      type: Boolean,
      default: false,
    },
    /**
     * The timestamp of the last time this pattern was observed.
     * Used for TTL indexing to expire old patterns.
     * @type {Date}
     * @default Date.now
     */
    lastObservedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    /**
     * Mongoose schema options.
     * @property {boolean} timestamps - Automatically adds `createdAt` and `updatedAt` fields.
     */
    timestamps: true,
  }
);

/**
 * Mongoose pre-validation hook to automatically generate the sequence hash.
 * Hashing the sequence provides a consistent, indexable string representation of the array,
 * which is more performant for ensuring uniqueness than indexing the array itself.
 */
WorkflowPatternSchema.pre('validate', function (next) {
  if (this.isModified('sequence') && this.sequence) {
    const sequenceString = JSON.stringify(this.sequence);
    this.sequenceHash = crypto
      .createHash('sha256')
      .update(sequenceString)
      .digest('hex');
  }
  next();
});

/**
 * Compound index to ensure a pattern sequence is unique for a given user.
 * This prevents duplicate workflow patterns for the same user and tool sequence, ensuring data integrity.
 * Uses a hash of the sequence for improved performance.
 * @index {userId: 1, sequenceHash: 1}
 * @unique
 */
WorkflowPatternSchema.index({ userId: 1, sequenceHash: 1 }, { unique: true });

/**
 * TTL (Time-To-Live) index to automatically expire patterns that have not been re-observed
 * within a specified period. This keeps the collection lean and relevant for the dashboard.
 * @index {lastObservedAt: 1}
 * @expireAfterSeconds 5184000 (60 days)
 */
WorkflowPatternSchema.index({ lastObservedAt: 1 }, { expireAfterSeconds: 5184000 });

/**
 * Represents the WorkflowPattern model in the database.
 * If the model already exists, it uses the existing one; otherwise, it creates a new one.
 * @type {mongoose.Model<WorkflowPattern>}
 */
const WorkflowPattern =
  mongoose.models.WorkflowPattern ||
  mongoose.model('WorkflowPattern', WorkflowPatternSchema);

export default WorkflowPattern;