import mongoose from 'mongoose';

/**
 * @typedef {Object} StepResult
 * @property {number} step - The sequential number of the step within the workflow.
 * @property {string} app - The name of the application or service used in this step.
 * @property {string} action - The specific action performed by the app in this step.
 * @property {'pending'|'running'|'completed'|'failed'|'skipped'} status - The status of this individual step.
 * @property {Date} [startTime] - The timestamp when this step started execution.
 * @property {Date} [endTime] - The timestamp when this step finished execution.
 * @property {number} [duration] - The duration of this step's execution in milliseconds.
 * @property {mongoose.Schema.Types.Mixed} [parameters] - The input parameters used for this step.
 * @property {mongoose.Schema.Types.Mixed} [result] - The output result from this step's execution.
 * @property {Object} [error] - Details if an error occurred during this step.
 * @property {string} [error.message] - The error message.
 * @property {string} [error.code] - The error code.
 * @property {mongoose.Schema.Types.Mixed} [error.details] - Additional error details.
 * @property {number} [retryCount=0] - The number of times this step has been retried.
 */

/**
 * @typedef {Object} ExecutionResult
 * @property {boolean} [success=false] - Indicates if the overall workflow execution was successful.
 * @property {mongoose.Schema.Types.Mixed} [data] - General data related to the execution outcome.
 * @property {string} [summary] - A summary message of the execution result.
 * @property {mongoose.Schema.Types.Mixed} [outputData] - The final output data generated by the workflow.
 */

/**
 * @typedef {Object} ErrorDetails
 * @property {'connection_error'|'parameter_error'|'execution_error'|'timeout_error'|'system_error'} [type] - The type of error that occurred.
 * @property {string} [message] - The error message.
 * @property {number} [step] - The step number where the error occurred.
 * @property {Date} [timestamp] - The timestamp when the error was recorded.
 * @property {string} [stackTrace] - The stack trace of the error.
 * @property {boolean} [isRetryable=true] - Indicates if the error is considered retryable.
 */

/**
 * @typedef {Object} ResourceUsage
 * @property {number} [memoryUsed] - Memory used during execution in MB.
 * @property {number} [cpuTime] - CPU time used during execution in milliseconds.
 * @property {number} [apiCalls=0] - Number of API calls made during execution.
 * @property {number} [dataTransferred] - Data transferred during execution in bytes.
 */

/**
 * @typedef {Object} ConnectedAccountUsed
 * @property {string} app - The name of the application.
 * @property {string} connectedAccountId - The ID of the connected account used.
 * @property {string} status - The status of the connection (e.g., 'active', 'revoked').
 */

/**
 * @typedef {Object} ExecutionContext
 * @property {string} [userAgent] - User agent string of the client initiating the execution.
 * @property {string} [ipAddress] - IP address of the client initiating the execution.
 * @property {string} [sessionId] - Session ID associated with the execution.
 * @property {string} [conversationId] - Conversation ID if the execution is part of a larger conversation.
 */

/**
 * @typedef {Object} LogEntry
 * @property {Date} [timestamp] - The timestamp of the log entry.
 * @property {'debug'|'info'|'warn'|'error'} level - The severity level of the log.
 * @property {string} message - The log message.
 * @property {number} [step] - The step number related to the log entry, if applicable.
 * @property {mongoose.Schema.Types.Mixed} [details] - Additional details for the log entry.
 */

/**
 * Mongoose schema for Workflow Execution.
 * Represents a single execution instance of a workflow, tracking its progress, status, results, and resources.
 *
 * @property {string} executionId - Unique identifier for this specific workflow execution.
 * @property {mongoose.Schema.Types.ObjectId} [workspaceId] - The ID of the workspace where this execution belongs.
 * @property {string} workflowId - The ID of the workflow definition that was executed.
 * @property {mongoose.Schema.Types.ObjectId} userId - The ID of the user who initiated or owns this execution.
 * @property {'manual'|'scheduled'|'retry'} executionType - The type of execution (e.g., manual, scheduled, retry).
 * @property {'user_click'|'cron_job'|'api_call'|'retry_mechanism'} triggerSource - The source that triggered this execution.
 * @property {Date} executionStartTime - The timestamp when the workflow execution started.
 * @property {Date} [executionEndTime] - The timestamp when the workflow execution ended.
 * @property {number} [executionDuration=0] - The total duration of the execution in milliseconds.
 * @property {'queued'|'running'|'completed'|'failed'|'cancelled'|'timeout'} [status='queued'] - The current status of the workflow execution.
 * @property {number} [currentStep=0] - The current step number being executed or last completed.
 * @property {number} totalSteps - The total number of steps defined in the workflow.
 * @property {number} [completedSteps=0] - The number of steps that have been completed (or failed/skipped).
 * @property {Array<StepResult>} [stepResults] - An array detailing the results and status of each individual step.
 * @property {ExecutionResult} [executionResult] - Overall result of the workflow execution.
 * @property {ErrorDetails} [errorDetails] - Detailed information if the workflow execution encountered an error.
 * @property {ResourceUsage} [resourceUsage] - Metrics on resource consumption during execution.
 * @property {number} [retryCount=0] - The number of times this execution has been retried.
 * @property {number} [maxRetries=3] - The maximum number of retries allowed for this execution.
 * @property {Date} [nextRetryTime] - The timestamp when the next retry attempt is scheduled.
 * @property {Array<ConnectedAccountUsed>} [connectedAccountsUsed] - List of connected accounts utilized during this execution.
 * @property {ExecutionContext} [executionContext] - Contextual information about the environment where the execution was initiated.
 * @property {Array<LogEntry>} [logs] - A chronological list of log entries for debugging and auditing.
 * @property {Date} createdAt - Timestamp when the document was created.
 * @property {Date} updatedAt - Timestamp when the document was last updated.
 */
const WorkflowExecutionSchema = new mongoose.Schema(
  {
    // Execution identification
    /**
     * Unique identifier for this specific workflow execution.
     * @type {string}
     * @required
     * @unique
     * @index
     */
    executionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    /**
     * The ID of the workspace where this execution belongs.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref Workspace
     * @index
     */
    workspaceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Workspace',
      index: true,
    },
    /**
     * The ID of the workflow definition that was executed.
     * @type {string}
     * @required
     * @index
     */
    workflowId: {
      type: String,
      required: true,
      index: true,
    },
    /**
     * The ID of the user who initiated or owns this execution.
     * @type {mongoose.Schema.Types.ObjectId}
     * @ref User
     * @required
     * @index
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Execution metadata
    /**
     * The type of execution (e.g., manual, scheduled, retry).
     * @type {'manual'|'scheduled'|'retry'}
     * @required
     */
    executionType: {
      type: String,
      enum: ['manual', 'scheduled', 'retry'],
      required: true,
    },
    /**
     * The source that triggered this execution.
     * @type {'user_click'|'cron_job'|'api_call'|'retry_mechanism'}
     * @required
     */
    triggerSource: {
      type: String,
      enum: ['user_click', 'cron_job', 'api_call', 'retry_mechanism'],
      required: true,
    },

    // Timing information
    /**
     * The timestamp when the workflow execution started.
     * @type {Date}
     * @required
     * @default Date.now
     */
    executionStartTime: {
      type: Date,
      required: true,
      default: Date.now,
    },
    /**
     * The timestamp when the workflow execution ended.
     * @type {Date}
     */
    executionEndTime: {
      type: Date,
    },
    /**
     * The total duration of the execution in milliseconds.
     * @type {number}
     * @default 0
     */
    executionDuration: {
      type: Number, // in milliseconds
      default: 0,
    },

    // Execution status and progress
    /**
     * The current status of the workflow execution.
     * @type {'queued'|'running'|'completed'|'failed'|'cancelled'|'timeout'}
     * @default 'queued'
     */
    status: {
      type: String,
      enum: [
        'queued',
        'running',
        'completed',
        'failed',
        'cancelled',
        'timeout',
      ],
      default: 'queued',
    },
    /**
     * The current step number being executed or last completed.
     * @type {number}
     * @default 0
     */
    currentStep: {
      type: Number,
      default: 0,
    },
    /**
     * The total number of steps defined in the workflow.
     * @type {number}
     * @required
     */
    totalSteps: {
      type: Number,
      required: true,
    },
    /**
     * The number of steps that have been completed (or failed/skipped).
     * @type {number}
     * @default 0
     */
    completedSteps: {
      type: Number,
      default: 0,
    },

    // Step execution details
    /**
     * An array detailing the results and status of each individual step.
     * @type {Array<StepResult>}
     */
    stepResults: [
      {
        /** @type {number} */
        step: {
          type: Number,
          required: true,
        },
        /** @type {string} */
        app: {
          type: String,
          required: true,
        },
        /** @type {string} */
        action: {
          type: String,
          required: true,
        },
        /** @type {'pending'|'running'|'completed'|'failed'|'skipped'} */
        status: {
          type: String,
          enum: ['pending', 'running', 'completed', 'failed', 'skipped'],
          required: true,
        },
        /** @type {Date} */
        startTime: {
          type: Date,
        },
        /** @type {Date} */
        endTime: {
          type: Date,
        },
        /** @type {number} */
        duration: {
          type: Number, // in milliseconds
        },
        /** @type {mongoose.Schema.Types.Mixed} */
        parameters: {
          type: mongoose.Schema.Types.Mixed,
        },
        /** @type {mongoose.Schema.Types.Mixed} */
        result: {
          type: mongoose.Schema.Types.Mixed,
        },
        /** @type {Object} */
        error: {
          /** @type {string} */
          message: String,
          /** @type {string} */
          code: String,
          /** @type {mongoose.Schema.Types.Mixed} */
          details: mongoose.Schema.Types.Mixed,
        },
        /** @type {number} */
        retryCount: {
          type: Number,
          default: 0,
        },
      },
    ],

    // Overall execution results
    /**
     * Overall result of the workflow execution.
     * @type {ExecutionResult}
     */
    executionResult: {
      /** @type {boolean} */
      success: {
        type: Boolean,
        default: false,
      },
      /** @type {mongoose.Schema.Types.Mixed} */
      data: {
        type: mongoose.Schema.Types.Mixed,
      },
      /** @type {string} */
      summary: {
        type: String,
      },
      /** @type {mongoose.Schema.Types.Mixed} */
      outputData: {
        type: mongoose.Schema.Types.Mixed,
      },
    },

    // Error handling
    /**
     * Detailed information if the workflow execution encountered an error.
     * @type {ErrorDetails}
     */
    errorDetails: {
      /** @type {'connection_error'|'parameter_error'|'execution_error'|'timeout_error'|'system_error'} */
      type: {
        type: String,
        enum: [
          'connection_error',
          'parameter_error',
          'execution_error',
          'timeout_error',
          'system_error',
        ],
      },
      /** @type {string} */
      message: {
        type: String,
      },
      /** @type {number} */
      step: {
        type: Number,
      },
      /** @type {Date} */
      timestamp: {
        type: Date,
      },
      /** @type {string} */
      stackTrace: {
        type: String,
      },
      /** @type {boolean} */
      isRetryable: {
        type: Boolean,
        default: true,
      },
    },

    // Resource usage
    /**
     * Metrics on resource consumption during execution.
     * @type {ResourceUsage}
     */
    resourceUsage: {
      /** @type {number} */
      memoryUsed: {
        type: Number, // in MB
      },
      /** @type {number} */
      cpuTime: {
        type: Number, // in milliseconds
      },
      /** @type {number} */
      apiCalls: {
        type: Number,
        default: 0,
      },
      /** @type {number} */
      dataTransferred: {
        type: Number, // in bytes
      },
    },

    // Retry information
    /**
     * The number of times this execution has been retried.
     * @type {number}
     * @default 0
     */
    retryCount: {
      type: Number,
      default: 0,
    },
    /**
     * The maximum number of retries allowed for this execution.
     * @type {number}
     * @default 3
     */
    maxRetries: {
      type: Number,
      default: 3,
    },
    /**
     * The timestamp when the next retry attempt is scheduled.
     * @type {Date}
     */
    nextRetryTime: {
      type: Date,
    },

    // Connected accounts at execution time
    /**
     * List of connected accounts utilized during this execution.
     * @type {Array<ConnectedAccountUsed>}
     */
    connectedAccountsUsed: [
      {
        /** @type {string} */
        app: String,
        /** @type {string} */
        connectedAccountId: String,
        /** @type {string} */
        status: String,
      },
    ],

    // Execution context
    /**
     * Contextual information about the environment where the execution was initiated.
     * @type {ExecutionContext}
     */
    executionContext: {
      /** @type {string} */
      userAgent: String,
      /** @type {string} */
      ipAddress: String,
      /** @type {string} */
      sessionId: String,
      /** @type {string} */
      conversationId: String,
    },

    // Logging and debugging
    /**
     * A chronological list of log entries for debugging and auditing.
     * @type {Array<LogEntry>}
     */
    logs: [
      {
        /** @type {Date} */
        timestamp: {
          type: Date,
          default: Date.now,
        },
        /** @type {'debug'|'info'|'warn'|'error'} */
        level: {
          type: String,
          enum: ['debug', 'info', 'warn', 'error'],
          required: true,
        },
        /** @type {string} */
        message: {
          type: String,
          required: true,
        },
        /** @type {number} */
        step: Number,
        /** @type {mongoose.Schema.Types.Mixed} */
        details: mongoose.Schema.Types.Mixed,
      },
    ],
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes for performance
/**
 * Index for efficient lookup of workflow executions by workflow ID and sorted by start time.
 * @index
 */
WorkflowExecutionSchema.index({ workflowId: 1, executionStartTime: -1 });
/**
 * Index for efficient lookup of workflow executions by user ID and status.
 * @index
 */
WorkflowExecutionSchema.index({ userId: 1, status: 1 });
/**
 * Index for efficient lookup of workflow executions by status and sorted by start time.
 * @index
 */
WorkflowExecutionSchema.index({ status: 1, executionStartTime: 1 });
/**
 * Index for efficient lookup of workflow executions by execution type and trigger source.
 * @index
 */
WorkflowExecutionSchema.index({ executionType: 1, triggerSource: 1 });
/**
 * Index for efficient lookup of workflow executions by next retry time and status.
 * @index
 */
WorkflowExecutionSchema.index({ nextRetryTime: 1, status: 1 });
/**
 * Index for efficient lookup of workflow executions by workspace ID and sorted by start time.
 * @index
 */
WorkflowExecutionSchema.index({ workspaceId: 1, executionStartTime: -1 });

// Virtuals
/**
 * Virtual property that calculates the progress percentage of the workflow execution.
 * @member {number} progressPercentage
 * @memberof WorkflowExecution
 * @instance
 * @returns {number} The progress percentage (0-100).
 */
WorkflowExecutionSchema.virtual('progressPercentage').get(function () {
  if (this.totalSteps === 0) return 0;
  return Math.round((this.completedSteps / this.totalSteps) * 100);
});

/**
 * Virtual property that indicates if the workflow execution is currently running or queued.
 * @member {boolean} isRunning
 * @memberof WorkflowExecution
 * @instance
 * @returns {boolean} True if the status is 'queued' or 'running', false otherwise.
 */
WorkflowExecutionSchema.virtual('isRunning').get(function () {
  return ['queued', 'running'].includes(this.status);
});

/**
 * Virtual property that indicates if the workflow execution has reached a final state.
 * @member {boolean} isCompleted
 * @memberof WorkflowExecution
 * @instance
 * @returns {boolean} True if the status is 'completed', 'failed', 'cancelled', or 'timeout', false otherwise.
 */
WorkflowExecutionSchema.virtual('isCompleted').get(function () {
  return ['completed', 'failed', 'cancelled', 'timeout'].includes(this.status);
});

/**
 * Virtual property that calculates the elapsed execution time in milliseconds.
 * If the workflow is queued, returns 0. If completed, returns the duration between start and end.
 * If running, returns the duration from start to the current time.
 * @member {number} executionTime
 * @memberof WorkflowExecution
 * @instance
 * @returns {number} The execution time in milliseconds.
 */
WorkflowExecutionSchema.virtual('executionTime').get(function () {
  // If the workflow is still queued, execution hasn't truly started, so duration is 0.
  if (this.status === 'queued') {
    return 0;
  }
  // If execution has ended, calculate the duration.
  if (this.executionEndTime && this.executionStartTime) {
    return this.executionEndTime.getTime() - this.executionStartTime.getTime();
  }
  // If execution is running but not yet ended, calculate duration from start to now.
  // executionStartTime is required and defaults to Date.now, so it should always exist.
  if (this.isRunning && this.executionStartTime) {
    return Date.now() - this.executionStartTime.getTime();
  }
  // Default case for other statuses or if times are unexpectedly missing.
  return 0;
});

// Methods
/**
 * Marks the workflow execution as 'running' and sets its `executionStartTime`.
 * @memberof WorkflowExecution
 * @instance
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.startExecution = function () {
  this.status = 'running';
  this.executionStartTime = new Date();
  return this.save();
};

/**
 * Marks the workflow execution as 'completed' or 'failed' and sets its `executionEndTime` and `executionDuration`.
 * Updates the overall `executionResult` based on the success parameter and provided result data.
 * @memberof WorkflowExecution
 * @instance
 * @param {boolean} success - True if the execution completed successfully, false otherwise.
 * @param {Object} [result=null] - Optional object containing `data`, `summary`, and `outputData` for the execution result.
 * @param {mongoose.Schema.Types.Mixed} [result.data] - General data related to the execution outcome.
 * @param {string} [result.summary] - A summary message of the execution result.
 * @param {mongoose.Schema.Types.Mixed} [result.outputData] - The final output data generated by the workflow.
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.completeExecution = function (
  success,
  result = null
) {
  this.status = success ? 'completed' : 'failed';
  this.executionEndTime = new Date();
  // Ensure executionStartTime is available before calculating duration
  if (this.executionStartTime) {
    this.executionDuration =
      this.executionEndTime.getTime() - this.executionStartTime.getTime();
  } else {
    this.executionDuration = 0; // Default to 0 if start time is missing
  }
  this.executionResult.success = success;

  if (result) {
    this.executionResult.data = result.data;
    this.executionResult.summary = result.summary;
    this.executionResult.outputData = result.outputData;
  }

  return this.save();
};

/**
 * Updates the progress of the workflow execution by adding or modifying a step result.
 * Also recalculates the `completedSteps` count.
 * @memberof WorkflowExecution
 * @instance
 * @param {number} stepNumber - The sequential number of the step being updated.
 * @param {Object} stepResult - An object containing the details of the step's outcome.
 * @param {string} stepResult.app - The name of the application or service used in this step.
 * @param {string} stepResult.action - The specific action performed by the app in this step.
 * @param {'pending'|'running'|'completed'|'failed'|'skipped'} stepResult.status - The status of this individual step.
 * @param {Date} [stepResult.startTime] - The timestamp when this step started execution.
 * @param {Date} [stepResult.endTime] - The timestamp when this step finished execution.
 * @param {number} [stepResult.duration] - The duration of this step's execution in milliseconds.
 * @param {mongoose.Schema.Types.Mixed} [stepResult.parameters] - The input parameters used for this step.
 * @param {mongoose.Schema.Types.Mixed} [stepResult.result] - The output result from this step's execution.
 * @param {Object} [stepResult.error] - Details if an error occurred during this step.
 * @param {string} [stepResult.error.message] - The error message.
 * @param {string} [stepResult.error.code] - The error code.
 * @param {mongoose.Schema.Types.Mixed} [stepResult.error.details] - Additional error details.
 * @param {number} [stepResult.retryCount] - The number of times this step has been retried.
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.updateProgress = function (
  stepNumber,
  stepResult
) {
  // Update current step
  this.currentStep = stepNumber;

  // Add or update step result
  const existingIndex = this.stepResults.findIndex(
    (sr) => sr.step === stepNumber
  );
  if (existingIndex >= 0) {
    this.stepResults[existingIndex] = {
      ...this.stepResults[existingIndex],
      ...stepResult,
    };
  } else {
    this.stepResults.push({ step: stepNumber, ...stepResult });
  }

  // Update completed steps count
  this.completedSteps = this.stepResults.filter((sr) =>
    ['completed', 'failed', 'skipped'].includes(sr.status)
  ).length;

  return this.save();
};

/**
 * Adds a new log entry to the `logs` array of the workflow execution.
 * @memberof WorkflowExecution
 * @instance
 * @param {'debug'|'info'|'warn'|'error'} level - The severity level of the log.
 * @param {string} message - The log message.
 * @param {number} [step=null] - The step number related to the log entry, if applicable.
 * @param {mongoose.Schema.Types.Mixed} [details=null] - Additional details for the log entry.
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.addLog = function (
  level,
  message,
  step = null,
  details = null
) {
  this.logs.push({
    timestamp: new Date(),
    level,
    message,
    step,
    details,
  });

  return this.save();
};

/**
 * Cancels the workflow execution, setting its status to 'cancelled' and recording the end time and duration.
 * Also adds an informational log entry about the cancellation.
 * @memberof WorkflowExecution
 * @instance
 * @param {string} [reason='User cancelled'] - The reason for cancellation.
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.cancel = function (reason = 'User cancelled') {
  this.status = 'cancelled';
  this.executionEndTime = new Date();
  // Ensure executionStartTime is available before calculating duration
  if (this.executionStartTime) {
    this.executionDuration =
      this.executionEndTime.getTime() - this.executionStartTime.getTime();
  } else {
    this.executionDuration = 0; // Default to 0 if start time is missing
  }
  
  // Push directly to logs array to avoid double-saving the document
  this.logs.push({
    timestamp: new Date(),
    level: 'info',
    message: reason,
  });

  return this.save();
};

/**
 * Schedules a retry for the workflow execution if `retryCount` is less than `maxRetries`.
 * Increments `retryCount`, sets `nextRetryTime`, and changes status to 'queued'.
 * If `maxRetries` is reached, sets status to 'failed'.
 * @memberof WorkflowExecution
 * @instance
 * @param {number} [delayMinutes=5] - The delay in minutes before the next retry attempt.
 * @returns {Promise<WorkflowExecution>} The saved WorkflowExecution document.
 */
WorkflowExecutionSchema.methods.scheduleRetry = function (delayMinutes = 5) {
  if (this.retryCount >= this.maxRetries) {
    this.status = 'failed';
    return this.save();
  }

  this.retryCount += 1;
  this.nextRetryTime = new Date(Date.now() + delayMinutes * 60 * 1000);
  this.status = 'queued';

  return this.save();
};

// Static methods
/**
 * Finds workflow executions for a given workflow ID, sorted by `executionStartTime` in descending order.
 * @memberof WorkflowExecution
 * @static
 * @param {string} workflowId - The ID of the workflow definition.
 * @param {number} [limit=50] - The maximum number of results to return.
 * @returns {mongoose.Query<Array<WorkflowExecution>>} A Mongoose query.
 */
WorkflowExecutionSchema.statics.findByWorkflow = function (
  workflowId,
  limit = 50
) {
  return this.find({ workflowId })
    .sort({ executionStartTime: -1 })
    .limit(limit);
};

/**
 * Finds workflow executions for a given user ID, optionally filtered by status, and sorted by `executionStartTime` in descending order.
 * @memberof WorkflowExecution
 * @static
 * @param {mongoose.Schema.Types.ObjectId} userId - The ID of the user.
 * @param {'queued'|'running'|'completed'|'failed'|'cancelled'|'timeout'} [status=null] - Optional status to filter by.
 * @param {number} [limit=100] - The maximum number of results to return.
 * @returns {mongoose.Query<Array<WorkflowExecution>>} A Mongoose query.
 */
WorkflowExecutionSchema.statics.findByUser = function (
  userId,
  status = null,
  limit = 100
) {
  const query = { userId };
  if (status) query.status = status;

  return this.find(query).sort({ executionStartTime: -1 }).limit(limit);
};

/**
 * Finds workflow executions that are 'queued', have a `nextRetryTime` in the past,
 * have been retried at least once, and are still within their `maxRetries` limit.
 * These are candidates for a retry mechanism.
 * @memberof WorkflowExecution
 * @static
 * @returns {mongoose.Query<Array<WorkflowExecution>>} A Mongoose query for pending retries.
 */
WorkflowExecutionSchema.statics.findPendingRetries = function () {
  // Find queued executions that are past their nextRetryTime and still within their maxRetries limit.
  // Using $expr for field-to-field comparison (retryCount <= maxRetries) requires MongoDB 3.6+.
  return this.find({
    status: 'queued',
    nextRetryTime: { $lte: new Date() },
    retryCount: { $gt: 0 }, // Only consider documents that have been retried at least once
    $expr: { $lte: ['$retryCount', '$maxRetries'] }, // Ensure retryCount is less than or equal to document's maxRetries
  });
};

/**
 * Generates a unique execution ID string.
 * @memberof WorkflowExecution
 * @static
 * @returns {string} A unique execution ID.
 */
WorkflowExecutionSchema.statics.generateExecutionId = function () {
  return `exec_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

/**
 * Aggregates statistics for workflow executions of a specific workflow ID.
 * Groups by status and calculates count, average duration, and last execution time for each status.
 * @memberof WorkflowExecution
 * @static
 * @param {string} workflowId - The ID of the workflow definition.
 * @returns {mongoose.Aggregate<Array<Object>>} A Mongoose aggregation pipeline.
 * @example
 * // Returns an array like:
 * // [
 * //   { _id: 'completed', count: 10, avgDuration: 15000, lastExecution: <Date> },
 * //   { _id: 'failed', count: 2, avgDuration: 5000, lastExecution: <Date> }
 * // ]
 */
WorkflowExecutionSchema.statics.getExecutionStats = function (workflowId) {
  return this.aggregate([
    { $match: { workflowId } },
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
        avgDuration: { $avg: '$executionDuration' },
        lastExecution: { $max: '$executionStartTime' },
      },
    },
  ]);
};

/**
 * Aggregates statistics for workflow executions of a specific workspace.
 * Groups by status and calculates count, average duration, and last execution time for each status.
 * Useful for workspace metrics dashboards.
 * @memberof WorkflowExecution
 * @static
 * @param {mongoose.Schema.Types.ObjectId|string} workspaceId - The ID of the workspace.
 * @returns {mongoose.Aggregate<Array<Object>>} A Mongoose aggregation pipeline.
 */
WorkflowExecutionSchema.statics.getWorkspaceExecutionStats = function (workspaceId) {
  const oid = typeof workspaceId === 'string' ? new mongoose.Types.ObjectId(workspaceId) : workspaceId;
  return this.aggregate([
    { $match: { workspaceId: oid } },
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
        avgDuration: { $avg: '$executionDuration' },
        lastExecution: { $max: '$executionStartTime' },
      },
    },
  ]);
};

/**
 * Represents a WorkflowExecution in the database.
 * This model provides an interface for interacting with workflow execution documents.
 * @class WorkflowExecution
 * @augments mongoose.Model
 */
const WorkflowExecution = mongoose.model(
  'WorkflowExecution',
  WorkflowExecutionSchema
);

/**
 * @exports WorkflowExecution
 */
export default WorkflowExecution;