import mongoose from 'mongoose';

/**
 * WorkflowPattern Model
 *
 * Stores recurring tool-call sequences detected from ActionAuditLog history.
 * Powered by the Composio Workflow Pattern Intelligence Agent.
 */
const WorkflowPatternSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    // Ordered list of tool slugs that form the pattern (e.g. ['GMAIL_SEND_EMAIL', 'GOOGLECALENDAR_CREATE_EVENT'])
    sequence: {
      type: [String],
      required: true,
    },
    // Number of times this exact sequence was observed
    occurrenceCount: {
      type: Number,
      default: 1,
    },
    // Aggregate success rate across all observed runs of this pattern
    successRate: {
      type: Number,
      min: 0,
      max: 100,
      default: 100,
    },
    // Average total latency of the entire sequence (ms)
    avgSequenceLatencyMs: {
      type: Number,
      default: 0,
    },
    // Estimated time savings if this sequence was automated (ms per run)
    estimatedTimeSavingsMs: {
      type: Number,
      default: 0,
    },
    // Natural language suggestion generated by Gemini
    geminiSuggestion: {
      type: String,
      default: '',
    },
    // A short title for the pattern (also Gemini-generated)
    patternTitle: {
      type: String,
      default: '',
    },
    // Whether the user has acknowledged/dismissed this suggestion
    dismissed: {
      type: Boolean,
      default: false,
    },
    // Last time this pattern was observed
    lastObservedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

// Compound index: one record per user per unique sequence (serialized)
WorkflowPatternSchema.index({ userId: 1, sequence: 1 });

// TTL: auto-expire patterns not re-observed within 60 days
WorkflowPatternSchema.index({ lastObservedAt: 1 }, { expireAfterSeconds: 60 * 24 * 60 * 60 });

const WorkflowPattern =
  mongoose.models.WorkflowPattern ||
  mongoose.model('WorkflowPattern', WorkflowPatternSchema);

export default WorkflowPattern;
