import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateOTP, registrationOtpTemplate, forgetPassOtpTemplate, deleteUserOtpTemplate } from './auth.utils.js';
import otpGenerator from 'otp-generator';
import config from '../../../../config/index.js';

// Mock otp-generator
vi.mock('otp-generator', () => ({
  generate: vi.fn(),
}));

// Mock config
vi.mock('../../../../config/index.js', () => ({
  default: {
    client_url: 'http://localhost:3000', // Default mock client URL for tests
  },
}));

describe('Auth Utils', () => {

  beforeEach(() => {
    // Reset mocks before each test
    vi.clearAllMocks();
    // Ensure config.client_url is reset to a default for tests that rely on it
    config.client_url = 'http://localhost:3000';
  });

  describe('generateOTP', () => {
    it('should generate a 6-digit numeric OTP', async () => {
      const mockOtp = '123456';
      // Mock the synchronous function as if it were async, matching the original code's await
      otpGenerator.generate.mockResolvedValue(mockOtp);

      const otp = await generateOTP();

      expect(otpGenerator.generate).toHaveBeenCalledTimes(1);
      expect(otpGenerator.generate).toHaveBeenCalledWith(6, {
        lowerCaseAlphabets: false,
        upperCaseAlphabets: false,
        specialChars: false,
      });
      expect(otp).toBe(mockOtp);
      expect(otp).toMatch(/^\d{6}$/); // Ensure it's 6 digits
    });

    it('should handle different OTPs generated by the library', async () => {
      const mockOtp = '987654';
      otpGenerator.generate.mockResolvedValue(mockOtp);

      const otp = await generateOTP();

      expect(otp).toBe(mockOtp);
      expect(otp).toMatch(/^\d{6}$/);
    });
  });

  describe('registrationOtpTemplate', () => {
    const testEmail = 'test@example.com';
    const testToken = '123456';
    const defaultFrontendUrl = 'http://localhost:3000';

    it('should return a mailData object with correct structure and content', () => {
      const result = registrationOtpTemplate(testEmail, testToken);

      expect(result).toBeInstanceOf(Object);
      expect(result).toHaveProperty('userEmail', testEmail);
      expect(result).toHaveProperty('sub', 'Verify Your Account');
      expect(result).toHaveProperty('message');
      expect(typeof result.message).toBe('string');
    });

    it('should include the token and verification link in the message', () => {
      const result = registrationOtpTemplate(testEmail, testToken);
      const expectedVerificationLink = `${defaultFrontendUrl}/register?code=${testToken}`;

      expect(result.message).toContain(testToken);
      expect(result.message).toContain(expectedVerificationLink);
      expect(result.message).toContain(`href="${expectedVerificationLink}"`);
    });

    it('should use the fallback client_url if config.client_url is not defined', () => {
      config.client_url = undefined; // Simulate undefined client_url
      const result = registrationOtpTemplate(testEmail, testToken);
      const fallbackFrontendUrl = 'https://insoassistant.com';
      const expectedVerificationLink = `${fallbackFrontendUrl}/register?code=${testToken}`;

      expect(result.message).toContain(fallbackFrontendUrl);
      expect(result.message).toContain(expectedVerificationLink);
      expect(result.message).toContain(`href="${expectedVerificationLink}"`);
    });

    it('should contain specific HTML elements and text', () => {
      const result = registrationOtpTemplate(testEmail, testToken);
      expect(result.message).toContain('Email Verification');
      expect(result.message).toContain('Dear user,');
      expect(result.message).toContain('Thank you for signing up on Inso AI!');
      expect(result.message).toContain('Verify Account');
      expect(result.message).toContain('This email was sent by Inso AI.');
    });
  });

  describe('forgetPassOtpTemplate', () => {
    const testEmail = 'forget@example.com';
    const testUser = { username: 'JohnDoe' };
    const testOtp = '654321';

    it('should return a mailData object with correct structure and content', () => {
      const result = forgetPassOtpTemplate(testEmail, testUser, testOtp);

      expect(result).toBeInstanceOf(Object);
      expect(result).toHaveProperty('userEmail', testEmail);
      expect(result).toHaveProperty('sub', 'Verify Your One-Time Password (OTP)');
      expect(result).toHaveProperty('message');
      expect(typeof result.message).toBe('string');
    });

    it('should include the OTP and username in the message', () => {
      const result = forgetPassOtpTemplate(testEmail, testUser, testOtp);

      expect(result.message).toContain(testOtp);
      expect(result.message).toContain(`Dear ${testUser.username},`);
    });

    it('should use "User" as fallback if username is not provided', () => {
      const userWithoutUsername = {};
      const result = forgetPassOtpTemplate(testEmail, userWithoutUsername, testOtp);

      expect(result.message).toContain('Dear User,');
      expect(result.message).toContain(testOtp);
    });

    it('should contain specific HTML elements and text', () => {
      const result = forgetPassOtpTemplate(testEmail, testUser, testOtp);
      expect(result.message).toContain('Verify Your OTP');
      expect(result.message).toContain('To complete your reset password, please enter the following OTP:');
      expect(result.message).toContain('This code is valid for 10 minutes.');
      expect(result.message).toContain('This email was sent by Inso AI.');
    });
  });

  describe('deleteUserOtpTemplate', () => {
    const testUser = { email: 'delete@example.com', username: 'JaneDoe' };
    const testOtp = '998877';

    it('should return a mailData object with correct structure and content', () => {
      const result = deleteUserOtpTemplate(testUser, testOtp);

      expect(result).toBeInstanceOf(Object);
      expect(result).toHaveProperty('userEmail', testUser.email);
      expect(result).toHaveProperty('sub', 'Delete Account OTP');
      expect(result).toHaveProperty('message');
      expect(typeof result.message).toBe('string');
    });

    it('should include the OTP and username in the message', () => {
      const result = deleteUserOtpTemplate(testUser, testOtp);

      expect(result.message).toContain(testOtp);
      expect(result.message).toContain(`Dear ${testUser.username},`);
    });

    it('should use "User" as fallback if username is not provided', () => {
      const userWithoutUsername = { email: 'delete_no_name@example.com' };
      const result = deleteUserOtpTemplate(userWithoutUsername, testOtp);

      expect(result.message).toContain('Dear User,');
      expect(result.message).toContain(testOtp);
      expect(result.userEmail).toBe(userWithoutUsername.email);
    });

    it('should handle undefined user object gracefully', () => {
      const result = deleteUserOtpTemplate(undefined, testOtp);

      expect(result.userEmail).toBeUndefined();
      expect(result.message).toContain('Dear User,'); // Fallback for username
      expect(result.message).toContain(testOtp);
    });

    it('should contain specific HTML elements and text', () => {
      const result = deleteUserOtpTemplate(testUser, testOtp);
      expect(result.message).toContain('Verify Your OTP');
      expect(result.message).toContain('To proceed with deleting your account, please enter the following OTP:');
      expect(result.message).toContain('This code is valid for 10 minutes.');
      expect(result.message).toContain('This email was sent by Inso AI.');
    });
  });
});