/**
 * @file This file contains helper functions for formatting responses and data related to deep research operations.
 * It ensures consistent data structures for API responses, errors, statistics, and PDF downloads within the application.
 * @module deep_research_helpers
 */

/**
 * Formats a deep research answer into a consistent API response structure.
 * This function standardizes the output for successful deep research queries, making it easier for clients to consume.
 * @param {string} answer - The primary research answer or content generated by the deep research process.
 * @param {string} conversationId - A unique identifier for the ongoing research conversation, linking messages and responses.
 * @param {number} messageCount - The total number of messages exchanged in the current conversation, including the current response.
 * @param {Object} [additionalData={}] - Optional additional data to include in the response. This can contain
 *   supplementary information such as `sources`, `relatedTopics`, `sentiment`, or other contextual details.
 * @returns {Object} A formatted object containing the research answer, conversation details, and any additional data.
 * @property {string} answer - The research answer content.
 * @property {string} conversationId - The ID of the conversation.
 * @property {number} messageCount - The number of messages in the conversation.
 * @property {Object} [additionalData] - Any extra data passed in, merged into the top-level object.
 */
export const formatDeepResearchResponse = (
  answer,
  conversationId,
  messageCount,
  additionalData = {}
) => {
  return {
    answer,
    conversationId,
    messageCount,
    ...additionalData,
  };
};

/**
 * Formats an error message related to deep research into a consistent API error response structure.
 * This function standardizes error reporting for deep research operations, providing clear and structured error feedback.
 * @param {string} error - The error message describing what went wrong during the deep research process.
 * @param {string} conversationId - The ID of the conversation where the error occurred, useful for debugging.
 * @param {'guest'|'authenticated'} userType - The type of user who initiated the request (e.g., 'guest' for unauthenticated, 'authenticated' for logged-in users).
 * @returns {Object} A formatted error object including the error message, conversation ID, user type, and a timestamp.
 * @property {string} error - The descriptive error message.
 * @property {string} conversationId - The ID of the conversation where the error occurred.
 * @property {'guest'|'authenticated'} userType - The type of user.
 * @property {string} timestamp - An ISO 8601 formatted timestamp indicating when the error response was generated.
 */
export const formatDeepResearchError = (error, conversationId, userType) => {
  return {
    error,
    conversationId,
    userType,
    timestamp: new Date().toISOString(),
  };
};

/**
 * Formats raw deep research statistics into a more readable and consistent structure.
 * This function aggregates and presents key metrics related to deep research usage, often for dashboard or reporting purposes.
 * @param {Object} stats - An object containing raw statistics from the data source or service.
 * @param {number} [stats.totalDeepResearchConversations=0] - The total number of deep research conversations initiated.
 * @param {number} [stats.totalDeepResearchMessages=0] - The total number of messages exchanged across all deep research conversations.
 * @param {number} [stats.averageMessagesPerConversation=0] - The average number of messages per deep research conversation.
 * @returns {Object} A formatted object containing aggregated deep research statistics.
 * @property {number} totalResearches - The total count of deep research conversations.
 * @property {number} totalMessages - The total count of messages in deep research.
 * @property {number} averageMessagesPerResearch - The average messages per research conversation.
 * @property {string} lastUpdated - An ISO 8601 formatted timestamp indicating when these statistics were last updated or generated.
 */
export const formatDeepResearchStats = (stats = {}) => { // Added default empty object for stats to prevent TypeError if stats is null/undefined
  return {
    totalResearches: stats.totalDeepResearchConversations || 0,
    totalMessages: stats.totalDeepResearchMessages || 0,
    averageMessagesPerResearch: stats.averageMessagesPerConversation || 0,
    lastUpdated: new Date().toISOString(),
  };
};

/**
 * Formats PDF download data into a consistent API response structure.
 * This function standardizes the metadata provided when a PDF is generated or ready for download,
 * ensuring clients receive consistent information about the downloadable file.
 * @param {Object} pdfData - An object containing raw PDF information from the generation service.
 * @param {string} pdfData.filename - The suggested name for the generated PDF file.
 * @param {number} pdfData.size - The size of the PDF file in bytes.
 * @param {string} pdfData.downloadUrl - The URL from which the PDF can be downloaded by the client.
 * @returns {Object} A formatted object containing PDF download details.
 * @property {string} filename - The name of the PDF file.
 * @property {number} size - The size of the PDF file in bytes.
 * @property {string} downloadUrl - The URL to download the PDF.
 * @property {string} generatedAt - An ISO 8601 formatted timestamp indicating when the PDF response was generated.
 */
export const formatPDFResponse = (pdfData = {}) => { // Added default empty object for pdfData to prevent TypeError if pdfData is null/undefined
  return {
    filename: pdfData.filename,
    size: pdfData.size,
    downloadUrl: pdfData.downloadUrl,
    generatedAt: new Date().toISOString(),
  };
};

/**
 * An aggregate object containing all deep research helper functions.
 * This object provides a convenient way to import and access all related utility functions
 * for formatting deep research responses, errors, statistics, and PDF data.
 * @constant
 * @type {Object}
 * @property {function(string, string, number, Object): Object} formatDeepResearchResponse - Function to format deep research success responses.
 * @property {function(string, string, 'guest'|'authenticated'): Object} formatDeepResearchError - Function to format deep research error responses.
 * @property {function(Object): Object} formatDeepResearchStats - Function to format deep research statistics.
 * @property {function(Object): Object} formatPDFResponse - Function to format PDF download responses.
 */
export const deepResearchHelpers = {
  formatDeepResearchResponse,
  formatDeepResearchError,
  formatDeepResearchStats,
  formatPDFResponse,
};