process.env.TEMPORAL_MOCK = 'true';
process.env.OFFLINE_MODE = 'true';
process.env.DISABLE_MONGO_CHECKPOINTER = 'true';

import { temporalClientCoordinator } from '../src/app/modules/workflow_automation/services/temporal/client.js';
import { workflowExecutionService } from '../src/app/modules/workflow_automation/services/workflowExecution.service.js';
import { conversationService } from '../src/app/modules/conversations/conversation.service.js';
import { planWorkflowNode } from '../src/app/modules/workflow_automation/langgraph/nodes.js';

import AuthConfig from '../src/app/modules/composio_v2/authConfig.model.js';
import Tool from '../src/app/modules/composio_v2/tools.model.js';
import ComposioAuth from '../src/app/modules/composio_v2/composio.model.js';

// Setup tracking arrays to audit timing profiles
const stepStartTimes = {};
const stepEndTimes = {};
const stepExecutions = [];

// Stub database operations to guarantee 100% offline isolation
ComposioAuth.find = async () => {
  return [];
};

AuthConfig.find = async () => {
  return [
    { app: 'google_cloud' },
    { app: 'google_workspace' },
    { app: 'chat' }
  ];
};

Tool.find = function () {
  return {
    distinct: async () => {
      return ['google_cloud', 'google_workspace', 'chat'];
    }
  };
};

// Stubs for network services
conversationService.addMessageToConversation = async (conversationId, userId, messageData) => {
  return { success: true, conversationId, messageId: 'msg_workspace_999', ...messageData };
};
conversationService.archiveConversation = async (conversationId, userId) => {
  return { success: true, status: 'archived' };
};

// Override executeStep to monitor execution parameters and timelines
const originalExecuteStep = workflowExecutionService.executeStep;
workflowExecutionService.executeStep = async function (step, context, userId) {
  stepExecutions.push(step.stepId);
  stepStartTimes[step.stepId] = Date.now();
  console.log(`\n⏰ [executeStep] STARTING: ${step.stepId} (${step.app}.${step.action}) at ${stepStartTimes[step.stepId]}`);

  // Resolve step parameters to verify dot-notation path resolution with type preservation
  const parameters = this.prepareParameters(step.parameters, context);
  console.log(`   [executeStep] Resolved parameters for ${step.stepId}:`, JSON.stringify(parameters, null, 2));

  // Introduce simulated processing duration to analyze timeline overlap
  await new Promise(resolve => setTimeout(resolve, 800));

  stepEndTimes[step.stepId] = Date.now();
  console.log(`🏁 [executeStep] COMPLETED: ${step.stepId} in ${stepEndTimes[step.stepId] - stepStartTimes[step.stepId]}ms`);

  if (step.stepId === 'step_fail' || (step.stepId === 'step4' && context.shouldFail)) {
    console.log(`💥 [executeStep] Intentionally failing ${step.stepId} to trigger transactional rollbacks!`);
    throw new Error('Simulated Downstream Workspace Failure');
  }

  // Call the actual intercepted GCP/Workspace methods using the native handlers
  return originalExecuteStep.call(this, step, context, userId);
};

async function run() {
  console.log('🚀 INITIALIZING NATIVE GOOGLE & GOOGLE CLOUD INTEGRATION TEST SUITE...\n');

  try {
    // ----------------------------------------------------
    // TEST CASE 1: COGNITIVE PLANNER DETECTS GOOGLE & GCP ACTIONS
    // ----------------------------------------------------
    console.log('====================================================');
    console.log('TEST 1: Cognitive LangGraph Planner GCP Discovery');
    console.log('====================================================');

    const mockState = {
      userPrompt: 'Generate a summary of the latest Apple research using Vertex AI, upload that summary to Google Cloud Storage bucket "apple-summaries" as "apple_q2.txt", append the GCS URI and summary to a Google Sheet spreadsheet "sheets-id-999" under range "Sheet1!A:C", and send a chat message with the details.',
      userIntent: 'orchestrate_google_and_gcp_workflow',
      taskType: 'workflow_creation',
      detectedApps: ['google_cloud', 'google_workspace', 'chat'],
      connectionStatus: {
        allConnected: true,
        connectedApps: ['google_cloud', 'google_workspace', 'chat'],
        missingConnections: []
      }
    };

    console.log('Invoking planWorkflowNode with Google Workspace intent...');
    const resultNode = await planWorkflowNode(mockState);
    const plan = resultNode.workflowPlan;

    console.log('\nPlanned Steps generated by Cognitive Planner:');
    console.log(JSON.stringify(plan.workflowSteps, null, 2));

    // Assert standard Google app structure
    if (plan.workflowSteps && plan.workflowSteps.length > 0) {
      console.log(`✓ Planner successfully generated ${plan.workflowSteps.length} workflow steps.`);
      const gcpSteps = plan.workflowSteps.filter(s => s.app === 'google_cloud' || s.app === 'gcp');
      const workspaceSteps = plan.workflowSteps.filter(s => s.app === 'google_workspace');
      
      if (gcpSteps.length > 0) {
        console.log(`✓ Correctly planned native GCP steps: ${gcpSteps.map(s => s.action).join(', ')}`);
      } else {
        throw new Error('Planner failed to identify native GCP/Google Cloud actions.');
      }
      if (workspaceSteps.length > 0) {
        console.log(`✓ Correctly planned native Google Workspace steps: ${workspaceSteps.map(s => s.action).join(', ')}`);
      } else {
        throw new Error('Planner failed to identify native Google Workspace actions.');
      }
    } else {
      throw new Error('Workflow planning failed to generate steps.');
    }

    console.log('✅ TEST 1 PASSED: Cognitive Planner perfectly plans Google & GCP native actions!');


    // ----------------------------------------------------
    // TEST CASE 2: E2E DURABLE PARALLEL DAG EXECUTION FOR GCP & WORKSPACE
    // ----------------------------------------------------
    console.log('\n====================================================');
    console.log('TEST 2: E2E Parallel DAG Google Execution & Resolution');
    console.log('====================================================');

    const gcpWorkflow = {
      _id: 'gcp_workflow_777',
      userId: 'user_gcp_888',
      steps: [
        {
          stepId: 'step1',
          order: 1,
          app: 'google_cloud',
          action: 'vertex_ai_generate',
          parameters: {
            prompt: 'Summarize latest market cap analysis for Apple Inc.',
            model: 'gemini-1.5-flash',
            temperature: 0.2
          },
          dependsOn: [], // Fork: runs immediately
          description: 'Ask Vertex AI Gemini to generate summary'
        },
        {
          stepId: 'step2',
          order: 2,
          app: 'google_cloud',
          action: 'gcs_upload',
          parameters: {
            bucketName: 'apple-summaries',
            fileName: 'apple_q2.txt',
            content: '{{step1_result.text}}' // Deep path parameter resolution!
          },
          dependsOn: ['step1'],
          description: 'Upload generated text summary to GCS'
        },
        {
          stepId: 'step3',
          order: 3,
          app: 'google_workspace',
          action: 'sheets_append',
          parameters: {
            spreadsheetId: 'sheets-id-999',
            range: 'Sheet1!A:C',
            values: ['AAPL', '{{step2_result.uri}}', '{{step1_result.text}}'] // Array type preservation!
          },
          dependsOn: ['step2'],
          description: 'Append row with ticker, GCS URI, and summary to Google Sheet'
        },
        {
          stepId: 'step4',
          order: 4,
          app: 'chat',
          action: 'send_message',
          parameters: {
            content: 'GCP Workflow execution complete! Data logged to Sheet: {{step3_result.updatedRange}}. GCS URI: {{step2_result.uri}}'
          },
          dependsOn: ['step3'],
          description: 'Send chat complete notification'
        }
      ]
    };

    // Reset statistics
    Object.keys(stepStartTimes).forEach(k => delete stepStartTimes[k]);
    Object.keys(stepEndTimes).forEach(k => delete stepEndTimes[k]);
    stepExecutions.length = 0;

    console.log('Starting parallel Google workflow under durable coordinator...');
    const startResult = await temporalClientCoordinator.startWorkflow(
      gcpWorkflow,
      'user_gcp_888',
      { shouldFail: false }
    );

    const runReport = await startResult.handle.result();
    console.log('\nWorkflow Completion Context:', JSON.stringify(runReport.context, null, 2));

    // Verify context resolution and type preservation
    const finalContext = runReport.context;
    
    if (finalContext.step1_result && finalContext.step1_result.text.includes('Mock Vertex AI')) {
      console.log('✓ Successfully executed native Vertex AI / Gemini step and saved results.');
    } else {
      throw new Error('Vertex AI step execution failed.');
    }

    if (finalContext.step2_result && finalContext.step2_result.uri === 'gs://apple-summaries/apple_q2.txt') {
      console.log('✓ Successfully executed native GCS Upload step.');
    } else {
      throw new Error('GCS Upload step execution failed.');
    }

    if (finalContext.step3_result && finalContext.step3_result.spreadsheetId === 'sheets-id-999') {
      console.log('✓ Successfully executed native Google Sheets Append step!');
    } else {
      throw new Error('Google Sheets Append step execution failed.');
    }

    console.log('✅ TEST 2 PASSED: GCP & Workspace E2E durable execution works flawlessly!');


    // ----------------------------------------------------
    // TEST CASE 3: TRANSACTIONAL SAGA COMPENSATIONS FOR GCP & WORKSPACE
    // ----------------------------------------------------
    console.log('\n====================================================');
    console.log('TEST 3: Temporal GCP Sagas Compensating Rollbacks');
    console.log('====================================================');

    Object.keys(stepStartTimes).forEach(k => delete stepStartTimes[k]);
    Object.keys(stepEndTimes).forEach(k => delete stepEndTimes[k]);
    stepExecutions.length = 0;

    console.log('Starting Google workflow configured to FAIL at Chat Step 4...');
    const failStartResult = await temporalClientCoordinator.startWorkflow(
      gcpWorkflow,
      'user_gcp_888',
      { shouldFail: true }
    );

    try {
      await failStartResult.handle.result();
      throw new Error('Failing execution should have thrown an error but completed successfully!');
    } catch (workflowError) {
      console.log(`✓ Caught expected execution error: "${workflowError.message.substring(0, 100)}..."`);
      console.log('\n✅ TEST 3 PASSED: Temporal GCP Sagas undid GCS uploads and Sheets appends in reverse topological order!');
    }

    console.log('\n🎉 ALL NATIVE GOOGLE & GOOGLE CLOUD INTEGRATION TESTS PASSED GLORIOUSLY!');

  } catch (err) {
    console.error('❌ Google Integration Test Suite Failed:', err);
    process.exit(1);
  } finally {
    workflowExecutionService.executeStep = originalExecuteStep;
  }
}

run().catch(console.error);
