import express from 'express';
import multer from 'multer';
import { ENUM_USER_ROLE } from '../../../shared/enum.js';
import auth from '../../middlewares/auth/auth.js';
import optionalAuth from '../../middlewares/auth/optionalAuth.js';
import { extractTenantContext } from '../../middlewares/tenant/tenantContext.js';
import createRateLimiter from '../../middlewares/rateLimit/authLimiter.js';
import { validateRequest } from '../../middlewares/validateRequest/validateRequest.js';
import checkDailyRequestLimit from '../../middlewares/checkDailyRequestLimit/checkDailyRequestLimit.js';
import checkRAGFeature from '../../middlewares/checkRAGFeature/checkRAGFeature.js';
import checkStorageLimit from '../../middlewares/checkStorageLimit/checkStorageLimit.js';
import { summaryController } from './summary.controller.js';
import { SummaryValidation } from './summary.validation.js';

const router = express.Router();

/**
 * @typedef {object} SummaryRequestBody
 * @property {string} text - The text content to summarize. Required if no file is provided.
 * @property {string} [language='en'] - Optional language for the summary (e.g., 'en', 'es').
 * @property {'short'|'medium'|'long'} [length='medium'] - Desired length of the summary.
 * @property {'paragraph'|'bullet_points'} [format='paragraph'] - Desired format of the summary.
 * @property {string} [model] - Optional AI model to use for summarization.
 * @property {boolean} [ragEnabled=false] - Whether to enable RAG for summarization (if supported by the model/feature).
 * @property {object} [metadata] - Optional metadata to associate with the summary.
 */

/**
 * @typedef {object} SummaryFileRequestBody
 * @property {string} [text] - Optional text content to summarize instead of a file.
 * @property {File} file - The file to summarize (PDF, TXT, DOCX, CSV). Required if no text is provided.
 * @property {string} [language='en'] - Optional language for the summary (e.g., 'en', 'es').
 * @property {'short'|'medium'|'long'} [length='medium'] - Desired length of the summary.
 * @property {'paragraph'|'bullet_points'} [format='paragraph'] - Desired format of the summary.
 * @property {string} [model] - Optional AI model to use for summarization.
 * @property {boolean} [ragEnabled=false] - Whether to enable RAG for summarization (if supported by the model/feature).
 * @property {object} [metadata] - Optional metadata to associate with the summary.
 */

/**
 * @typedef {object} SummarySuccessResponse
 * @property {boolean} success - Indicates if the request was successful.
 * @property {string} message - A descriptive message.
 * @property {object} data - The response data.
 * @property {string} data.summary - The generated summary text.
 * @property {string} data.summaryId - The ID of the generated summary.
 */

/**
 * @typedef {object} SummaryStatsResponse
 * @property {boolean} success - Indicates if the request was successful.
 * @property {string} message - A descriptive message.
 * @property {object} data - The response data.
 * @property {number} data.totalSummaries - Total number of summaries generated by the user/tenant.
 * @property {number} data.dailySummaries - Number of summaries generated by the user/tenant today.
 * @property {number} data.storageUsedMB - Storage used in MB for summary-related files by the user/tenant.
 */

/**
 * Multer configuration for handling file uploads.
 * Configures storage to memory, sets a file size limit, and filters allowed file types.
 * @constant
 * @type {multer.Multer}
 */
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    // Set a reasonable file size limit to prevent abuse and server overload.
    fileSize: 10 * 1024 * 1024, // 10 MB
  },
  fileFilter: (req, file, cb) => {
    const allowedTypes = [
      'application/pdf',
      'text/plain',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'text/csv',
    ];

    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      // Reject unsupported file types with a user-friendly error message.
      // This error should be caught by a global error handler to return a proper 400 Bad Request response.
      const error = new Error(
        'Invalid file type. Please upload a PDF, TXT, DOCX, or CSV file.'
      );
      // Attaching a status code helps downstream error handlers provide the correct HTTP response.
      error.status = 400;
      cb(error, false);
    }
  },
});

/**
 * @swagger
 * tags:
 *   name: Summary
 *   description: API for generating summaries from text or files and retrieving summary statistics.
 */

/**
 * @swagger
 * /api/v1/summary/summarize:
 *   post:
 *     summary: Summarize content from a provided file or text.
 *     description: This endpoint allows users to generate a summary from either an uploaded file (PDF, TXT, DOCX, CSV) or directly provided text.
 *                  It supports optional authentication, tenant context extraction, daily request limits, storage limits, and RAG feature checks.
 *                  If authenticated, usage is tracked against the user/tenant. If unauthenticated, a default tenant context might be used.
 *     tags: [Summary]
 *     security:
 *       - bearerAuth: [] # Optional authentication
 *     requestBody:
 *       description: Request body can be either multipart/form-data for file uploads or application/json for text-only summarization.
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             $ref: '#/components/schemas/SummaryFileRequestBody'
 *           encoding:
 *             file:
 *               contentType: [application/pdf, text/plain, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/csv]
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/SummaryRequestBody'
 *     responses:
 *       200:
 *         description: Summary generated successfully.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SummarySuccessResponse'
 *       400:
 *         description: Bad request (e.g., unsupported file type, validation error, missing file/text).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Invalid file type. Please upload a PDF, TXT, DOCX, or CSV file." }
 *                 errorMessages: { type: array, items: { type: object } }
 *       401:
 *         description: Unauthorized (if authentication token is invalid or expired for an authenticated user).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Unauthorized access" }
 *       403:
 *         description: Forbidden (e.g., daily request limit exceeded, RAG feature not enabled for the tenant, storage limit exceeded).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Daily request limit exceeded" }
 *       429:
 *         description: Too Many Requests (if rate limit is exceeded).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Too many requests, please try again later." }
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Internal Server Error" }
 */
router.post(
  '/summarize',
  // OPTIMIZATION: The middleware chain is ordered to fail fast.
  // Cheaper checks (auth, rate limits, daily limits) run before expensive operations like file processing.

  // 1. Authenticate user if a token is provided. Allows for both guest and registered user access.
  optionalAuth(),
  // 2. Set tenant context based on user or default for anonymous. Crucial for data isolation.
  extractTenantContext,
  // 3. Apply rate limiting early to prevent abuse and ensure service stability for all users.
  createRateLimiter(30, 15), // 30 summary requests per 15 minutes
  // 4. Perform cheap, pre-computation checks first to avoid unnecessary processing.
  checkDailyRequestLimit,
  // 5. Handle the file upload. This is an I/O and memory-intensive operation.
  upload.single('file'),
  // 6. Perform checks that depend on the uploaded file's metadata (e.g., size).
  checkStorageLimit, // Must be after `upload` to access req.file.size.
  // 7. Check if a requested feature (like RAG) is enabled for the user's tenant.
  checkRAGFeature,
  // 8. Validate the rest of the request body against the defined schema.
  validateRequest(SummaryValidation.summaryQuerySchema),
  // 9. If all checks pass, proceed to the controller for business logic.
  summaryController.summarizeContent
);

/**
 * @swagger
 * /api/v1/summary/stats:
 *   get:
 *     summary: Get summary generation statistics for the authenticated user/tenant.
 *     description: Retrieves statistics related to summary generation, such as total summaries, daily usage, and storage used.
 *                  This endpoint requires authentication and is accessible by both ADMIN and regular USER roles.
 *     tags: [Summary]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Summary statistics retrieved successfully.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SummaryStatsResponse'
 *       401:
 *         description: Unauthorized (authentication token is missing, invalid, or expired).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Unauthorized access" }
 *       403:
 *         description: Forbidden (user does not have the necessary role).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Forbidden access" }
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success: { type: boolean, example: false }
 *                 message: { type: string, example: "Internal Server Error" }
 */
router.get(
  '/stats',
  // This endpoint provides user-specific data, so authentication is required.
  auth(ENUM_USER_ROLE.ADMIN, ENUM_USER_ROLE.USER),
  // Extract tenant context after auth to ensure stats are scoped to the correct user/tenant.
  extractTenantContext,
  summaryController.getSummaryStats
);

/**
 * The main router for summary-related API operations.
 * @constant
 * @type {express.Router}
 */
export const summaryRoutes = router;