/**
 * MCP Application Catalog Blueprints
 * 
 * Declares standard, optimized configurations for official and popular open-source MCP servers.
 * Spawns these packages programmatically using standard server-side node/npx executions.
 *
 * AUTO-GENERATED BY sync_mcp_composio.js - DO NOT EDIT MANUALLY
 */

/**
 * @typedef {Object} McpServerBlueprint
 * @property {string} id - Unique identifier for the MCP server.
 * @property {string} name - Human-readable name of the MCP server.
 * @property {string} description - Detailed description of the server's capabilities and integration points.
 * @property {string} command - The executable command used to spawn the server (typically "npx").
 * @property {string[]} args - Arguments passed to the command. May contain dynamic placeholders like `{{tenantId}}` for multi-tenant workspace isolation.
 * @property {string[]} requiredEnv - Array of environment variable keys required for the server to function.
 * @property {Record<string, string>} env - Default environment variable mappings or empty placeholders.
 * @property {string[]} [requiredArgs] - Optional list of arguments that must be supplied dynamically.
 */

/**
 * MCP Application Catalog Blueprints.
 * 
 * A dictionary of standard, optimized configurations for official and popular open-source MCP servers.
 * These blueprints are used to spawn server instances programmatically using standard server-side Node.js/npx executions.
 * 
 * @type {Record<string, McpServerBlueprint>}
 * 
 * @note Multi-tenant context: Certain blueprints (like `filesystem`) utilize the `{{tenantId}}` placeholder 
 * in their arguments to enforce strict workspace isolation between different tenants.
 */
export const mcpCatalog = {
  "filesystem": {
    "id": "filesystem",
    "name": "Filesystem Interface",
    "description": "Secure, local filesystem access to read and write files within pre-approved workspace directories.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-filesystem",
      "storage/users/{{tenantId}}/workspace"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "google-maps": {
    "id": "google-maps",
    "name": "Google Maps Platform",
    "description": "Integrates Google Maps API to search places, compute transit routes, calculate travel times, and view geocoding data.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-google-maps"
    ],
    "requiredEnv": [
      "MAPS_API_KEY"
    ],
    "env": {
      "MAPS_API_KEY": ""
    }
  },
  "slack": {
    "id": "slack",
    "name": "Slack Integration",
    "description": "Access, search, post messages, and manage channels inside Slack workspaces programmatically.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-slack"
    ],
    "requiredEnv": [
      "SLACK_BOT_TOKEN"
    ],
    "env": {
      "SLACK_BOT_TOKEN": ""
    }
  },
  "linear": {
    "id": "linear",
    "name": "Linear System Connector",
    "description": "Query, create, and update issues, projects, and cycles inside Linear workspace trackers.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-linear"
    ],
    "requiredEnv": [
      "LINEAR_API_KEY"
    ],
    "env": {
      "LINEAR_API_KEY": ""
    }
  },
  "gcal": {
    "id": "gcal",
    "name": "Google Calendar Integration",
    "description": "Access, schedule, and sync events inside Google Calendar accounts securely.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-google-calendar"
    ],
    "requiredEnv": [
      "GOOGLE_CALENDAR_CREDENTIALS"
    ],
    "env": {
      "GOOGLE_CALENDAR_CREDENTIALS": ""
    }
  },
  "katzilla": {
    "id": "katzilla",
    "name": "Katzilla Data API",
    "description": "Access 300+ free, public, and government datasets (economic data from FRED/BLS, health from CDC/FDA, science from NASA/arXiv, environmental from EPA/NOAA) behind a single API key.",
    "command": "npx",
    "args": [
      "-y",
      "@katzilla/mcp"
    ],
    "requiredEnv": [
      "KATZILLA_API_KEY"
    ],
    "env": {
      "KATZILLA_API_KEY": ""
    }
  },
  "astronomy-oracle": {
    "id": "astronomy-oracle",
    "name": "Astronomy Oracle",
    "description": "Accurate astronomical catalog data and observing session planner (13,000+ deep-sky objects from OpenNGC with visibility and rise/transit/set calculations).",
    "command": "npx",
    "args": [
      "-y",
      "astronomy-oracle"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "myinstants": {
    "id": "myinstants",
    "name": "MyInstants Soundboard",
    "description": "Meme soundboard integration to search, browse, and play millions of meme sounds from myinstants.com.",
    "command": "npx",
    "args": [
      "-y",
      "myinstants-mcp"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "imagen": {
    "id": "imagen",
    "name": "Imagen AI Graphic Engine",
    "description": "High-fidelity AI image generation from text prompts using Google's Imagen 3.0 API with professional camera, lighting, and style controls.",
    "command": "npx",
    "args": [
      "-y",
      "imagen3-mcp"
    ],
    "requiredEnv": [
      "IMAGEN_API_KEY" // Corrected API key name for Imagen integration
    ],
    "env": {
      "IMAGEN_API_KEY": "" // Corrected API key name for Imagen integration
    }
  },
  "spotify-bulk": {
    "id": "spotify-bulk",
    "name": "Spotify Bulk Planner",
    "description": "Advanced bulk Spotify operations with confidence-scored song matching, library exports, and batch playlist generators.",
    "command": "npx",
    "args": [
      "-y",
      "spotify-bulk-actions-mcp"
    ],
    "requiredEnv": [
      "SPOTIFY_CLIENT_ID",
      "SPOTIFY_CLIENT_SECRET"
    ],
    "env": {
      "SPOTIFY_CLIENT_ID": "",
      "SPOTIFY_CLIENT_SECRET": ""
    }
  },
  "everything": {
    "id": "everything",
    "name": "Everything Integration",
    "description": "Reference / test server with prompts, resources, and tools.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-everything"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "fetch": {
    "id": "fetch",
    "name": "Fetch Integration",
    "description": "Web content fetching and conversion for efficient LLM usage.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-fetch"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "git": {
    "id": "git",
    "name": "Git Integration",
    "description": "Tools to read, search, and manipulate Git repositories.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-git"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "memory": {
    "id": "memory",
    "name": "Memory Integration",
    "description": "Knowledge graph-based persistent memory system.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-memory"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "sequential-thinking": {
    "id": "sequential-thinking",
    "name": "Sequential Thinking Integration",
    "description": "Dynamic and reflective problem-solving through thought sequences.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-sequential-thinking"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "time": {
    "id": "time",
    "name": "Time Integration",
    "description": "Time and timezone conversion capabilities.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-time"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "aws-kb-retrieval": {
    "id": "aws-kb-retrieval",
    "name": "AWS KB Retrieval Integration",
    "description": "Retrieval from AWS Knowledge Base using Bedrock Agent Runtime.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-aws-kb-retrieval"
    ],
    "requiredEnv": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_REGION"
    ],
    "env": {
      "AWS_ACCESS_KEY_ID": "",
      "AWS_SECRET_ACCESS_KEY": "",
      "AWS_REGION": ""
    }
  },
  "brave-search": {
    "id": "brave-search",
    "name": "Brave Search Integration",
    "description": "Web and local search using Brave's Search API.  Has been replaced by the [official server](https://github.com/brave/brave-search-mcp-server).",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-brave-search"
    ],
    "requiredEnv": [
      "BRAVE_API_KEY"
    ],
    "env": {
      "BRAVE_API_KEY": ""
    }
  },
  "everart": {
    "id": "everart",
    "name": "EverArt Integration",
    "description": "AI image generation using various models.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-everart"
    ],
    "requiredEnv": [
      "EVERART_API_KEY"
    ],
    "env": {
      "EVERART_API_KEY": ""
    }
  },
  "github": {
    "id": "github",
    "name": "GitHub Integration",
    "description": "Repository management, file operations, and GitHub API integration.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-github"
    ],
    "requiredEnv": [
      "GITHUB_PERSONAL_ACCESS_TOKEN"
    ],
    "env": {
      "GITHUB_PERSONAL_ACCESS_TOKEN": ""
    }
  },
  "gitlab": {
    "id": "gitlab",
    "name": "GitLab Integration",
    "description": "GitLab API, enabling project management.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-gitlab"
    ],
    "requiredEnv": [
      "GITLAB_PERSONAL_ACCESS_TOKEN"
    ],
    "env": {
      "GITLAB_PERSONAL_ACCESS_TOKEN": ""
    }
  },
  "google-drive": {
    "id": "google-drive",
    "name": "Google Drive Integration",
    "description": "File access and search capabilities for Google Drive.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-google-drive"
    ],
    "requiredEnv": [
      "GOOGLE_DRIVE_CREDENTIALS" // Corrected credentials name for Google Drive integration
    ],
    "env": {
      "GOOGLE_DRIVE_CREDENTIALS": "" // Corrected credentials name for Google Drive integration
    }
  },
  "postgresql": {
    "id": "postgresql",
    "name": "PostgreSQL Integration",
    "description": "Read-only database access with schema inspection.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-postgresql"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "puppeteer": {
    "id": "puppeteer",
    "name": "Puppeteer Integration",
    "description": "Browser automation and web scraping.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-puppeteer"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "redis": {
    "id": "redis",
    "name": "Redis Integration",
    "description": "Interact with Redis key-value stores.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-redis"
    ],
    "requiredEnv": [
      "REDIS_URL"
    ],
    "env": {
      "REDIS_URL": ""
    }
  },
  "sentry": {
    "id": "sentry",
    "name": "Sentry Integration",
    "description": "Retrieving and analyzing issues from Sentry.io.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-sentry"
    ],
    "requiredEnv": [
      "SENTRY_AUTH_TOKEN"
    ],
    "env": {
      "SENTRY_AUTH_TOKEN": ""
    }
  },
  "sqlite": {
    "id": "sqlite",
    "name": "SQLite Integration",
    "description": "Database interaction and business intelligence capabilities.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-sqlite"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "postgres": {
    "id": "postgres",
    "name": "Postgres Database Connector",
    "description": "Queries, maps, and executes safe database scripts on PostgreSQL database engines.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-postgres"
    ],
    "requiredArgs": [
      "databaseUrl"
    ],
    "env": {},
    "requiredEnv": []
  },
  "playwright": {
    "id": "playwright",
    "name": "Playwright Web Automation",
    "description": "Playwright headless browser automation, form-filling, clicking, and full single-page application (SPA) interaction.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-playwright"
    ],
    "requiredEnv": [],
    "env": {}
  },
  "evernote": {
    "id": "evernote",
    "name": "Evernote Notes Integration",
    "description": "Access, search, and manage Evernote notes, folders, and notebooks programmatically inside your chat sessions.",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-evernote"
    ],
    "requiredEnv": [
      "EVERNOTE_API_KEY"
    ],
    "env": {
      "EVERNOTE_API_KEY": ""
    }
  }
};