import { generalChatAssistant } from './core.agents.js';
import {
  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst
} from './search.agents.js';

// ─── Massive.com Financial Intelligence Agents (20 specialists) ───────────────
import {
  massiveEquityAnalyst,
  massiveOptionsStrategist,
  massiveCryptoAnalyst,
  massiveForexTrader,
  massiveMacroEconomist,
  massiveTechnicalChartist,
  massiveFundamentalsAudit,
  massivePortfolioAdvisor
} from './massive.agents.js';
import {
  massiveMarketSentinel,
  massiveEarningsSpecialist,
  massiveDividendIncomePlanner,
  massiveShortSqueezeScanner,
  massiveSectorRotationAdvisor,
  massiveValueInvestor,
  massiveGrowthInvestor,
  massiveCommodityAnalyst,
  massiveETFAnalyst,
  massiveIPOAnalyst,
  massiveMomentumTrader,
  massiveRiskArbitrageur
} from './massive.agents.extended.js';
import {
  massiveInsiderFlowTracker,
  massiveOptionsFlowAlert,
  massiveFixedIncomeDesk,
  massiveREITAnalyst,
  massiveGlobalMarketsDesk,
  massiveQuantScreener,
  massiveCryptoDefiResearcher,
  massiveBehavioralCoach,
  massiveEconomicCalendarAgent,
  massiveAlternativesAdvisor,
  massiveTaxStrategyAdvisor,
  massiveRetirementPlanner
} from './massive.agents.pro.js';
import {
  startupFounderCoach,
  productManagerAdvisor,
  marketingGrowthStrategist,
  negotiationStrategist,
  businessPlanArchitect,
  clinicalResearchAdvisor,
  environmentalESGAnalyst,
  cybersecurityThreatAnalyst,
  dataPrivacyCompliance,
  scienceTutorAgent,
  creativeWritingDirector,
  careerStrategistCoach
} from './expert.agents.js';

import {
  sportsArbitrageScanner,
  sportsParlayArchitect,
  sportsSharpMoneyAnalyst,
  sportsPlayerPropsPredictor,
  sportsValueBettingQuant,
  sportsDFSExpert,
  sportsLiveOddsOrchestrator,
  sportsFuturesSpeculator
} from './predictiondata.agents.js';

import {
  realestatePropertyQuant,
  realestateMarketAnalyst,
  realestateSkipTracer
} from './realestate.agents.js';


import {
  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent
} from './data.agents.js';

import {
  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent
} from './intelligence.agents.js';
import {
  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter
} from './background.agents.js';

import {
  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect
} from './cloud.agents.js';

import {
  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert
} from './development.agents.js';

import {
  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter
} from './utility.agents.js';
import {
  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher
} from './specialized.agents.js';

// Compile all custom modular agents for global registry loading
export const customAgents = [
  generalChatAssistant,

  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst,

  // ── Massive.com Financial Intelligence Agents (20 specialists) ──────────────
  // Core 8: equity, options, crypto, forex, macro, technicals, fundamentals, portfolio
  massiveEquityAnalyst,
  massiveOptionsStrategist,
  massiveCryptoAnalyst,
  massiveForexTrader,
  massiveMacroEconomist,
  massiveTechnicalChartist,
  massiveFundamentalsAudit,
  massivePortfolioAdvisor,
  // Extended 12: sentiment, earnings, dividend, short squeeze, sector, value,
  // growth, commodity, ETF, IPO, momentum, risk arbitrage
  massiveMarketSentinel,
  massiveEarningsSpecialist,
  massiveDividendIncomePlanner,
  massiveShortSqueezeScanner,
  massiveSectorRotationAdvisor,
  massiveValueInvestor,
  massiveGrowthInvestor,
  massiveCommodityAnalyst,
  massiveETFAnalyst,
  massiveIPOAnalyst,
  massiveMomentumTrader,
  massiveRiskArbitrageur,
  // Pro 12: insider flow, options flow, fixed income, REIT, global markets,
  // quant screener, DeFi, behavioral, calendar, alternatives, tax, retirement
  massiveInsiderFlowTracker,
  massiveOptionsFlowAlert,
  massiveFixedIncomeDesk,
  massiveREITAnalyst,
  massiveGlobalMarketsDesk,
  massiveQuantScreener,
  massiveCryptoDefiResearcher,
  massiveBehavioralCoach,
  massiveEconomicCalendarAgent,
  massiveAlternativesAdvisor,
  massiveTaxStrategyAdvisor,
  massiveRetirementPlanner,
  // Expert 12: startup, product, growth, negotiation, business plan, medical research,
  // ESG, cybersecurity, privacy, science, creative writing, career
  startupFounderCoach,
  productManagerAdvisor,
  marketingGrowthStrategist,
  negotiationStrategist,
  businessPlanArchitect,
  clinicalResearchAdvisor,
  environmentalESGAnalyst,
  cybersecurityThreatAnalyst,
  dataPrivacyCompliance,
  scienceTutorAgent,
  creativeWritingDirector,
  careerStrategistCoach,

  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent,

  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent,

  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter,

  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect,

  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert,

  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter,

  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher,

  // ── PredictionData.io Sports Swarm Agents ──────────────────────────────────
  sportsArbitrageScanner,
  sportsParlayArchitect,
  sportsSharpMoneyAnalyst,
  sportsPlayerPropsPredictor,
  sportsValueBettingQuant,
  sportsDFSExpert,
  sportsLiveOddsOrchestrator,
  sportsFuturesSpeculator,

  // ── RealEstateAPI.com Real Estate Swarm Agents ─────────────────────────────
  realestatePropertyQuant,
  realestateMarketAnalyst,
  realestateSkipTracer
];

export {
  generalChatAssistant,

  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst,

  // ── Massive.com Financial Intelligence Agents ──────────────────────────────
  massiveEquityAnalyst,
  massiveOptionsStrategist,
  massiveCryptoAnalyst,
  massiveForexTrader,
  massiveMacroEconomist,
  massiveTechnicalChartist,
  massiveFundamentalsAudit,
  massivePortfolioAdvisor,
  massiveMarketSentinel,
  massiveEarningsSpecialist,
  massiveDividendIncomePlanner,
  massiveShortSqueezeScanner,
  massiveSectorRotationAdvisor,
  massiveValueInvestor,
  massiveGrowthInvestor,
  massiveCommodityAnalyst,
  massiveETFAnalyst,
  massiveIPOAnalyst,
  massiveMomentumTrader,
  massiveRiskArbitrageur,
  massiveInsiderFlowTracker,
  massiveOptionsFlowAlert,
  massiveFixedIncomeDesk,
  massiveREITAnalyst,
  massiveGlobalMarketsDesk,
  massiveQuantScreener,
  massiveCryptoDefiResearcher,
  massiveBehavioralCoach,
  massiveEconomicCalendarAgent,
  massiveAlternativesAdvisor,
  massiveTaxStrategyAdvisor,
  massiveRetirementPlanner,

  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent,

  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent,

  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter,

  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect,

  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert,

  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter,

  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher,

  // ── Expert Domain Intelligence Agents (Batch 4) ──────────────────────────
  startupFounderCoach,
  productManagerAdvisor,
  marketingGrowthStrategist,
  negotiationStrategist,
  businessPlanArchitect,
  clinicalResearchAdvisor,
  environmentalESGAnalyst,
  cybersecurityThreatAnalyst,
  dataPrivacyCompliance,
  scienceTutorAgent,
  creativeWritingDirector,
  careerStrategistCoach,

  // ── PredictionData.io Sports Swarm Agents ──────────────────────────────────
  sportsArbitrageScanner,
  sportsParlayArchitect,
  sportsSharpMoneyAnalyst,
  sportsPlayerPropsPredictor,
  sportsValueBettingQuant,
  sportsDFSExpert,
  sportsLiveOddsOrchestrator,
  sportsFuturesSpeculator,

  // ── RealEstateAPI.com Real Estate Swarm Agents ─────────────────────────────
  realestatePropertyQuant,
  realestateMarketAnalyst,
  realestateSkipTracer
};
