import { generalChatAssistant } from './core.agents.js';
import {
  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst
} from './search.agents.js';

import {
  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent
} from './data.agents.js';

import {
  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent
} from './intelligence.agents.js';
import {
  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter
} from './background.agents.js';

import {
  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect
} from './cloud.agents.js';

import {
  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert
} from './development.agents.js';

import {
  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter
} from './utility.agents.js';
import {
  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher
} from './specialized.agents.js';

// Compile all custom modular agents for global registry loading
export const customAgents = [
  generalChatAssistant,

  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst,

  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent,

  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent,

  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter,

  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect,

  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert,

  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter,

  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher
];

export {
  generalChatAssistant,

  realtimeSearchAgent,
  perplexityDeepSearcher,
  youtubeResearcher,
  academicScholar,
  financialSearchAgent,
  academicSearchAgent,
  liveIntelAggregator,
  academicMetaAnalyst,

  dataProcessorAgent,
  dataEtlSynthesizer,
  dbOptimizer,
  postgresDba,
  pdfIngestionAnalyst,
  realEstateAdvisor,
  schemaMapperAgent,
  payloadTransformerAgent,

  intelligenceAgent,
  manusStrategicPlanner,
  mathTutor,
  leetcodeCoach,
  systemDesignExpert,
  pentestAuditor,
  architecturalReasoningAgent,
  mathLogicProverAgent,

  securityAuditAgent,
  perfMonitorAgent,
  cacheOptimizerAgent,
  selfCriticAgent,
  contextCompressorAgent,
  queryDisambiguator,
  factValidationCritic,
  toolRoutingOrchestrator,
  semanticCachePrewarmer,
  responseDensityOptimizer,
  authoritativeSourceGrounder,
  semanticDriftCorrector,
  semanticRelevanceScorer,
  contextAttentionPruner,
  sentimentToneGuard,
  logicCoherenceChecker,
  ingestionRouter,

  gcpGrounding,
  terraformArchitect,
  gcpGkeExpert,
  gcpServerlessExpert,
  gcpSecurityExpert,
  gcpDatabaseExpert,
  gcpDataExpert,
  gcpMigrationSpecialist,
  gcpFinopsExpert,
  gcpMlopsExpert,
  gcpCloudRunArchitect,

  coder,
  codeDebugger,
  apiDesigner,
  observabilityEngineer,
  cicdArchitect,
  rustDeveloper,
  goDeveloper,
  pythonDataScientist,
  containerSecurityExpert,
  linuxSystemsExpert,
  googleChromeExtensionDeveloper,
  googleAppsScriptDeveloper,
  googleFlutterDeveloper,
  gitGitExpert,

  summarizer,
  translator,
  transcriber,
  documenter,
  brainstormer,
  creativeCopywriter,
  uxStrategist,
  seoContentSpecialist,
  emailCorrespondenceExpert,
  youtubeTranscriptSummarizer,
  resumeCvCoach,
  socialMediaWriter,
  pressReleaseWriter,
  grantProposalWriter,

  dietNutritionExpert,
  workoutFitnessCoach,
  travelItineraryArchitect,
  financialBudgetPlanner,
  legalCeaseDesistDrafter,
  financialAnalyst,
  marketResearcher,
  patentIntelResearcher,
  financialSecAuditor,
  legalRegulatoryResearcher
};
